---
title: "All iEEG Subjects"
output: html_document
date: "2024-04-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,  # don't print the code chunk
  warning = FALSE,  # don't print warnings
  message = FALSE,  # don't print messages
  fig.width = 8,  # set default width of figures
  fig.height = 5,  # set default height of figures
  fig.align = "center",  # always align figure in center
  fig.pos = "H",  # always plot figure at the exact location of the code chunk
  cache = FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(caret)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(viridis)
library(lmtest)
library(survival)
library(effectsize)
library(scales)
library(JMbayes2)
library(rmarkdown)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", "clean_behavioral_data.R"))
source(path(here(), "R", "create_distance_df.R"))
source(path(here(), "R", "joint_modeling_functions.R"))
source(path(here(), "R", "jm_visualization_functions.R"))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
nCores <- 8
registerDoParallel(nCores)

```


```{r load-data, results='asis', echo=FALSE, eval = T}

## Load Data ##
hc_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_hc_all_subs_logged_iti_onset.csv"))
game_data_distance <-  read_csv(path(here(), "munge", "all_subs_complete_distance_df.csv"))

## Clean ieeg data ##
game_data_distance <- game_data_distance %>%
  filter(subject != "BJH026") %>% # no hc data
  filter(trial_time <= 5.10) 

permuted <- FALSE
```


```{r model-prep}

numsub_base_ids <- seq(1000, 15000, by = 1000)

## Prep DF for Joint Model Fitting and select predictor variables ##
joint_dist_df <-  game_data_distance %>%
  mutate(subject = factor(subject)) %>%
  mutate(numsub_id = as.numeric(as.factor(subject)) * 1000) %>%
  filter(Direction != "Still") %>%
  filter(dots_eaten != 0) %>%
  filter(died == 0) %>%
  group_by(subject, trial_numeric) %>%
  # prep time variables
  mutate(jm_time = trial_time - first(trial_time)) %>%
  mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
  mutate(turnaround_time_tmp = if_else(event == 1, jm_time, 0)) %>%
  mutate(turnaround_time = max(turnaround_time_tmp)) %>%
  ungroup() %>%
  filter(turnaround_time != 0) %>% # exclude trials where they just ran into the ghost
  filter(jm_time <= turnaround_time) %>%
  select(subject, numsub_id, trial_numeric, distance_to_ghost, Direction, last_away, points_remaining, event, turnaround_time,
         away_choice, trial_time, jm_time, TrialType, reward_groups) %>%
  mutate(EVENT = 1) %>%
  group_by(subject) %>%
  mutate(points_remaining = scale(points_remaining)) %>%
  mutate(distance_to_ghost = scale(distance_to_ghost)) %>%
  ungroup() %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  mutate(jm_time = round(jm_time, 2))

## only ieeg trials
hc_sub_trials <- hc_theta_data %>%
  mutate(subject = factor(subject)) %>%
  mutate(numsub_id = as.numeric(as.factor(subject)) * 1000) %>%
  mutate(trial_ids = numsub_id + trial_numeric) %>%
  pull(trial_ids) %>%
  unique()

joint_dist_df <- joint_dist_df %>%
  mutate(trial_ids = numsub_id + trial_numeric) %>%
  filter(trial_ids %in% hc_sub_trials)

```


```{r make-split}

current_seed <- sample(1:100, 1)
split_df <- joint_dist_df %>% select(subject, trial_ids, turnaround_time, reward_groups) %>% distinct()
split_df <- split_df %>%
  group_by(subject) %>%
  mutate(turnaround_time_cat = 
           cut(turnaround_time, breaks = quantile(turnaround_time, 
                                                  probs = seq(0, 1, by = 0.2)), include.lowest = TRUE)) %>%
  ungroup() %>%
  mutate(strata = paste(subject, reward_groups, turnaround_time_cat, sep="_"))

set.seed(current_seed)  # for reproducibility
folds <- createFolds(split_df$strata, k = 5, list = TRUE, returnTrain = TRUE)
fold <- 1

seed_fold <- paste0(current_seed, "-", fold)


split_index <- folds[[fold]]
train_trials <- split_df[split_index, 'trial_ids'] %>% pull(trial_ids)
test_trials <- split_df[-split_index, 'trial_ids'] %>% pull(trial_ids)

# Print train/test info
print(paste0("Train: ", length(train_trials), " Test: ", length(test_trials)))

## Prep Train/Test DFs ##
# longitudinal dfs
train_long_data <- joint_dist_df %>%
  filter(trial_ids %in% train_trials)
test_long_data <- joint_dist_df %>%
  filter(trial_ids %in% test_trials)

# survival dfs
cox_df <- joint_dist_df %>%
    mutate(event = 1) %>%
    select(subject, trial_ids, trial_numeric, turnaround_time, event, EVENT) %>%
    distinct()

train_cox_df <- cox_df %>%
  filter(trial_ids %in% train_trials)
test_cox_df <- cox_df %>%
  filter(trial_ids %in% test_trials)



```

```{r fit-full-model}

# longitudinal model #
control = lmeControl(maxIter = 6000, niterEM = 6000, msMaxIter = 6000)
lm_threat <- lme(distance_to_ghost ~ jm_time, data = train_long_data, 
                 random = ~jm_time | trial_ids, control = control)
lm_reward <- lme(points_remaining ~ jm_time, data = train_long_data, 
                 random = ~jm_time | trial_ids, control = control)

# survival model #
cox_fit <- coxph(Surv(turnaround_time, EVENT) ~ 1, cluster = subject, data = train_cox_df)

# joint model #
jm_fit <- jm(cox_fit, list(lm_threat, lm_reward), time_var = "jm_time", 
             data_Surv = train_cox_df, 
             n_burnin = 2000, n_iter = 40000, n_chains =8, cores = 6)

# print summary #
print(kable(summary(lm_threat)$tTable, caption = "Threat Model") %>% kable_styling())
print(kable(summary(lm_reward)$tTable, caption = "Reward Model") %>% kable_styling())
print(summary(jm_fit))

# save joint model #
saveRDS(jm_fit, path(here(), "data", "joint_models", paste0("all_iEEG_behave_1.rds")))
  

traceplot(jm_fit)  
  
```


```{r fit-snity-check-model}

train_sub_long_data <- train_long_data

train_sub_cox_df <- train_cox_df 


# longitudinal model #
control = lmeControl(maxIter = 6000, niterEM = 6000, msMaxIter = 6000)
lm_threat_nm <- lme(distance_to_ghost ~ jm_time, data = train_sub_long_data, 
                 random = ~jm_time | trial_ids, control = control)
lm_reward_nm <- lme(points_remaining ~ jm_time, data = train_sub_long_data, 
                 random = ~jm_time | trial_ids, control = control)

# survival model #
cox_fit_nm <- coxph(Surv(turnaround_time, EVENT) ~ 1, 
                 data = train_sub_cox_df)

# joint model #
jm_fit_nm <- jm(cox_fit_nm, list(lm_threat_nm, lm_reward_nm), 
             time_var = "jm_time", id_var = "trial_ids",
             data_Surv = train_sub_cox_df, 
             n_burnin = 2000, n_iter = 40000, n_chains =8, cores = 6)

# print summary #
summary(lm_threat_nm)
summary(lm_reward_nm)
summary(jm_fit_nm)



```

```{r fit-snity-check-model}

train_sub_long_data <- train_long_data %>%
  mutate(trial_factor = factor(trial_numeric))

train_sub_cox_df <- train_cox_df %>%
  mutate(trial_factor = factor(trial_numeric))

# longitudinal model #
control = lmeControl(maxIter = 6000, niterEM = 6000, msMaxIter = 6000)
lm_threat_fc <- lme(distance_to_ghost ~ jm_time, data = train_sub_long_data, 
                 random = ~jm_time | trial_factor, control = control)
lm_reward_fc <- lme(points_remaining ~ jm_time, data = train_sub_long_data, 
                 random = ~jm_time | trial_factor, control = control)

# survival model #
cox_fit_fc <- coxph(Surv(turnaround_time, EVENT) ~ 1, 
                 data = train_sub_cox_df)

# joint model #
jm_fit_fc <- jm(cox_fit_fc, list(lm_threat_fc, lm_reward_fc), 
             time_var = "jm_time", id_var = "trial_factor",
             data_Surv = train_sub_cox_df, 
             n_burnin = 2000, n_iter = 40000, n_chains =8, cores = 6)

# print summary #
summary(lm_threat_fc)
summary(lm_reward_fc)
summary(jm_fit_fc)



```



```{r fit-snity-check-model}

train_sub_long_data <- train_long_data %>%
  mutate(trial_factor = factor(paste0("BJH016_", trial_numeric)))

train_sub_cox_df <- train_cox_df %>%
  mutate(trial_factor = factor(paste0("BJH016_", trial_numeric)))

# longitudinal model #
control = lmeControl(maxIter = 6000, niterEM = 6000, msMaxIter = 6000)
lm_threat_fc <- lme(distance_to_ghost ~ jm_time, data = train_sub_long_data, 
                 random = ~jm_time | trial_factor, control = control)
lm_reward_fc <- lme(points_remaining ~ jm_time, data = train_sub_long_data, 
                 random = ~jm_time | trial_factor, control = control)

# survival model #
cox_fit_fc <- coxph(Surv(turnaround_time, EVENT) ~ 1, 
                 data = train_sub_cox_df)

# joint model #
jm_fit_fc <- jm(cox_fit_fc, list(lm_threat_fc, lm_reward_fc), 
             time_var = "jm_time", id_var = "trial_factor",
             data_Surv = train_sub_cox_df, 
             n_burnin = 2000, n_iter = 40000, n_chains =8, cores = 6)

# print summary #
summary(lm_threat_fc)
summary(lm_reward_fc)
summary(jm_fit_fc)



```

```{r fit-snity-check-model}

train_sub_long_data <- train_long_data %>%
  mutate(trial_ids = factor(paste0("BJH027_", trial_numeric)))

train_sub_cox_df <- train_cox_df %>%
  mutate(trial_ids = factor(paste0("BJH027_", trial_numeric)))

# longitudinal model #
control = lmeControl(maxIter = 6000, niterEM = 6000, msMaxIter = 6000)
lm_threat <- lme(distance_to_ghost ~ jm_time, data = train_sub_long_data, 
                 random = ~jm_time | trial_ids, control = control)
lm_reward <- lme(points_remaining ~ jm_time, data = train_sub_long_data, 
                 random = ~jm_time | trial_ids, control = control)

# survival model #
cox_fit <- coxph(Surv(turnaround_time, EVENT) ~ 1, 
                 data = train_sub_cox_df)

# joint model #
jm_fit <- jm(cox_fit, list(lm_threat, lm_reward), 
             time_var = "jm_time", id_var = "trial_ids",
             data_Surv = train_sub_cox_df, 
             n_burnin = 2000, n_iter = 40000, n_chains =8, cores = 6)

# print summary #
summary(lm_threat)
summary(lm_reward)
summary(jm_fit)



```


```{r fit-model-over-10-splits, results='asis', echo=FALSE, eval = T}

auc_list <- c()
ici_list <- c()
e50_list <- c()
e90_list <- c()
brier_list <- c()
core_list <- c()
dic_list <- c()
pred_time_list <- c()
num_test_trials <- c()
num_train_trials <- c()
seed_list <- c()
survival_df <- tibble("subject"= c(), "seed" = c(), "predictor" = c(), "Mean" = c(), "StDev" = c(), "Min2.5" = c(), "Max97.5" = c(), "P" = c(), "RHat" = c())


## Prep DF for Joint Model Fitting and select predictor variables ##
joint_dist_df <- prep_joint_df(game_data_distance, current_subject, permuted)

# only ieeg trials
# hc_sub_trials <- hc_theta_data %>%
#   filter(subject == current_subject) %>%
#   pull(trial_numeric) %>%
#   unique()
# 
# joint_dist_df <- joint_dist_df %>%
#   filter(trial_numeric %in% hc_sub_trials)

# theta modeling
sub_theta_df <- hc_theta_data %>%
  filter(subject == current_subject) %>%
  filter(!is.na(theta)) %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  group_by(trial_time, trial_numeric) %>%
  mutate(mean_theta = mean(theta)) %>%
  select(-theta, -electrode) %>%
  distinct() %>%
  group_by(trial_numeric) %>%
  ### permuted theta 
  mutate(
    shift_amount = sample(1:n(), size = 1), # Ensure one shift value per group
    theta_shifted = map2_dbl(.x = shift_amount, .y = row_number(), ~ {
      shifted_index <- (.y + .x) %% n()
      if (shifted_index == 0) shifted_index <- n()
      mean_theta[shifted_index]
    })
  ) %>%
  ungroup() %>%
  select(-mean_theta) %>%
  rename(mean_theta = theta_shifted) %>%
  # mutate(trial_time = trial_time - .4) %>% #lagged
  mutate(trial_time = round(trial_time, 2)) %>%
  ungroup()

joint_dist_df <- inner_join(sub_theta_df, joint_dist_df, by = c("subject", "trial_numeric", "trial_time"))

## Create Test/Train ##
current_seed <- sample(1:100, 1)
split_df <- joint_dist_df %>% select(trial_numeric, turnaround_time, reward_groups) %>% distinct()
folds <- create_test_train(split_df, current_seed)

for(fold in c(1:5)){

    cat(paste0("\n\n## ", current_subject, " - ", current_seed, "\n"))
    seed_fold <- paste0(current_seed, "-", fold)
    seed_list <- c(seed_list, seed_fold)
    
    split_index <- folds[[fold]]
    train_trials <- split_df[split_index, 'trial_numeric'] %>% pull(trial_numeric)
    test_trials <- split_df[-split_index, 'trial_numeric'] %>% pull(trial_numeric)
    
    # Print train/test info
    print(paste0("Train: ", length(train_trials), " Test: ", length(test_trials)))
    cat(paste0("\n\n"))
    
    ## Prep Train/Test DFs ##
    # longitudinal dfs
    train_long_data <- joint_dist_df %>%
      filter(trial_numeric %in% train_trials)
    test_long_data <- joint_dist_df %>%
      filter(trial_numeric %in% test_trials)

    # survival dfs
    cox_df <- create_survival_df(joint_dist_df %>% mutate(trial_numeric = round(trial_numeric, 2)))
    train_cox_df <- cox_df %>%
      filter(trial_numeric %in% train_trials)
    test_cox_df <- cox_df %>%
      filter(trial_numeric %in% test_trials)

    ## Fit Joint Model ##
    file_name <- paste0(current_subject, "_", permuted, "_", seed_fold)
    jm_fit <- fit_joint_time_theta_models(train_long_data, train_cox_df, file_name)

    ## Print summary ##
    tmp <- kable(summary(jm_fit)$Survival, caption = "Joint Model",  format = "html")  %>%
      kable_styling()
    print(tmp)
    cat(paste0("\n\n"))

    dic_list <- c(dic_list, jm_fit$fit_stats$marginal$DIC)
    survival_df <- rbind(survival_df,
                                     summary(jm_fit)$Survival %>%
                                       mutate(predictor = rownames(summary(jm_fit)$Survival)) %>%
                                       select(predictor, Mean, StDev, `2.5%`, `97.5%`, P, `Rhat`) %>%
                                       mutate(seed = current_seed) %>%
                                       mutate(subject = current_subject))


    # prediction times
    prediction_time <- median(split_df$turnaround_time)
    pred_time_list <- c(pred_time_list, prediction_time)

    ## train/test perdiction times ##
    min_time <- min(test_cox_df$turnaround_time)
    max_time <- max(test_cox_df$turnaround_time)
    print(paste0("Prediction Time: ", prediction_time))
    print(paste0("Min Test Time: ", min_time))
    print(paste0("Max Test Time: ", max_time))
    cat(paste0("\n\n"))

    ### Calibration/Discrimintation ###
    ## Loop over different prediction times ##
    auc <- c()
    ici <- c()
    e50 <- c()
    e90 <- c()
    brier <- c()
    timepoints <- unique(test_cox_df$turnaround_time)
    test_times <- quantile(timepoints[timepoints > .5], probs = c(.4, .5, .6))
    for(pred_time in test_times){
      # AUC #
      tmp_auc <- tvAUC(jm_fit, newdata = test_long_data, Tstart = .5,
                   Thoriz = pred_time, idVar = 'trial_numeric')
      auc <- c(auc, tmp_auc$auc)

      ## Calibration ##
      toi <- pred_time - .5
      # calibration plot
      calibration_plot(jm_fit, newdata = test_long_data, Tstart = .5, Thoriz = pred_time, idVar = 'trial_numeric')
      # calibration metrics
      tmp_cal <- calibration_metrics(jm_fit, newdata = test_long_data, Tstart = .5, Dt = toi, idVar = 'trial_numeric')
      ici <- c(ici, tmp_cal[1])
      e50 <- c(e50, tmp_cal[2])
      e90 <- c(e90, tmp_cal[3])

      # rbier scores
      tmp_brier <- tvBrier(jm_fit, newdata = test_long_data, Tstart = .5, Dt = toi, integrated = F)
      brier <- c(brier, tmp_brier$Brier)

    }

    ### Print AUC ###
    auc_list <- c(auc_list, mean(auc))
    print(paste0("AUC: ", mean(auc)))
    cat(paste0("\n\n"))
    print("All AUCs: ")
    print(sort(auc))
    cat(paste0("\n\n"))

    ### Print Calibration ###
    ici_list <- c(ici_list, mean(ici))
    print(paste0("ICI: ", mean(ici)))
    e50_list <- c(e50_list, mean(e50))
    print(paste0("E50: ", mean(e50)))
    e90_list <- c(e90_list, mean(e90))
    print(paste0("E90: ", mean(e90)))
    cat(paste0("\n\n"))

    ### Brier Scores ###
    brier_list <- c(brier_list, mean(brier))
    print(paste0("Brier Score: ", mean(brier)))
    print("All Bier Scores: ")
    print(sort(brier))
    cat(paste0("\n\n"))

    ## Custom Checks ##

    # get predictions
    test_predictions <- predict_on_test_set(jm_fit, test_long_data, test_cox_df)

    # plot prediction plot
    ggthemr("solarized")
    plot_survival_predictions(test_predictions, current_subject)

    # plot correlation plot
    cor <- plot_correlation_plot(test_predictions, current_subject)
    core_list <- c(core_list, cor)

}

```














