---
title: "Basic Predictors"
output: html_document
date: "2024-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,  # don't print the code chunk
  warning = FALSE,  # don't print warnings
  message = FALSE,  # don't print messages
  fig.width = 8,  # set default width of figures
  fig.height = 5,  # set default height of figures
  fig.align = "center",  # always align figure in center
  fig.pos = "H",  # always plot figure at the exact location of the code chunk
  cache = FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(caret)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(viridis)
library(lmtest)
library(survival)
library(effectsize)
library(scales)
library(JMbayes2)
library(rmarkdown)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", "clean_behavioral_data.R"))
source(path(here(), "R", "create_distance_df.R"))
source(path(here(), "R", "joint_modeling_functions.R"))
source(path(here(), "R", "jm_visualization_functions.R"))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# # ## parallelization ##
# nCores <- 8
# registerDoParallel(nCores)

```


```{r load-data, results='asis', echo=FALSE, eval = T}

## Load Data ##
hc_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_hc_all_subs_logged_iti_onset.csv"))
game_data_distance <-  read_csv(path(here(), "munge", "all_subs_complete_distance_df.csv"))

## Clean ieeg data ##
game_data_distance <- game_data_distance %>%
  filter(subject != "BJH026")
```


```{r prep-dfs, results='asis', echo=FALSE, eval = T}

current_subject <- "BJH016"
permuted <- FALSE

## Prep DF for Joint Model Fitting and select predictor variables ##
joint_dist_df <- prep_joint_df(game_data_distance, current_subject, permuted)

# only ieeg trials
hc_sub_trials <- hc_theta_data %>%
  filter(subject == current_subject) %>%
  pull(trial_numeric) %>%
  unique()

sub_theta_df <- hc_theta_data %>%
  filter(subject == current_subject) %>%
  filter(!is.na(theta)) %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  group_by(trial_time, trial_numeric) %>%
  mutate(mean_theta = mean(theta)) %>%
  select(-theta, -electrode) %>%
  distinct() %>%
  ungroup()

joint_dist_df <- inner_join(sub_theta_df, joint_dist_df, by = c("subject", "trial_numeric", "trial_time"))


```


```{r}

threat_long_plot <- joint_dist_df %>%
  mutate(jm_time = round(jm_time, 2)) %>%
  ggplot(., aes(x = jm_time, y = distance_to_ghost)) +
  geom_line(aes(group = trial_numeric), alpha = .5, color = "#86C8B7") +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme_bw() +
  theme(axis.text = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
        axis.title = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
        plot.title = element_text(family = "Gill Sans", color = '#2D2327', size = 18)) +  
  labs(x = "Trial Time", y = "Distance to ghost") +
  ggtitle("Linear Models of Threat")


reward_long_plot <- joint_dist_df %>%
  mutate(jm_time = round(jm_time, 2)) %>%
  ggplot(., aes(x = jm_time, y = points_remaining)) +
  geom_line(aes(group = trial_numeric), alpha = .5, color = "#FB6087") +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme_bw() +
  theme(axis.text = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
        axis.title = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
        plot.title = element_text(family = "Gill Sans", color = '#2D2327', size = 18)) +  
  labs(x = "Trial Time", y = "Points remaning in the trial") +
  ggtitle("Linear Models of Reward")


ggsave(path(here(), "figures", "survival", "threat_long_plot.png"), threat_long_plot, width = 5.5, height = 3.75)
ggsave(path(here(), "figures", "survival", "reward_long_plot.png"), reward_long_plot, width = 5.5, height = 3.75)

```

```{r}

predict_on_test_set <- function(jm_fit, test_long_data, test_cox_df){
# This function generates predictions on a test set for a fitted joint model.
#
# The function takes three arguments:
# - jm_fit: A fitted joint model object. This model should be previously fitted using longitudinal and survival data.
# - test_long_data: A dataframe containing the test longitudinal data. This dataframe should include the same
#   variables used for fitting the joint model.
# - test_cox_df: A dataframe containing the test survival data.
#
# The function performs the following operations:
# 1. Filters the test_long_data to include only observations where 'trial_time' is less than 0.5. The model uses these 500ms 
#    to predict the turning time in a given heald out trial
# 2. Selects relevant columns from test_long_data, excluding 'turnaround_time' and 'EVENT', so there is no way it could use 
#    that info to make its predictions
# 3. Uses the 'predict' function on the 'jm_fit' model, passing the preprocessed test longitudinal data. It
#    specifies to process events, return the modified test data with predictions, identifies the unique ID variable,
#    and sets the time points for prediction as a sequence from 0.5 to 2.5 in steps of 0.05.
# 4. Renames the 'turnaround_time' column to 'turntime_real' in the test_cox_df for clarity and selects only
#    the necessary columns ('trial_numeric' and 'turntime_real') for joining with the predictions.
# 5. Performs a left join of the test predictions with the survival data (test_cox_df) based on 'trial_numeric' to
#    combine predictions with actual survival times.
# 6. Arranges the resulting dataframe by 'turntime_real' to ensure predictions are sorted by the actual survival times.
# 7. Converts the 'trial_numeric' variable to a factor, with levels specified as the unique values of 'trial_numeric',
#    for better handling in subsequent analyses or plots.
#
# Finally, the function returns the dataframe 'test_predictions', which contains the survival predictions alongside
# the actual survival times, ready for evaluation or further analysis.
  
  test_pred_df <- test_long_data %>% 
    filter(turnaround_time > 0.5) %>%
    filter(trial_time < .5) %>%
    mutate(EVENT = 0) %>%
    mutate(turnaround_time = .5)
  
  test_predictions <- predict(jm_fit, 
                        newdata = test_pred_df, process = "event", return_newdata = TRUE, 
                        idVar = "trial_numeric", times = seq(.5, 5, .05))
  
  test_cox_df <- test_cox_df %>% rename(turntime_real = turnaround_time) %>% select(trial_numeric, turntime_real)
  test_predictions <- left_join(test_predictions, test_cox_df, by = "trial_numeric")
  
  test_predictions <- test_predictions %>%
    arrange(turntime_real) %>%
    mutate(trial_numeric = factor(trial_numeric, levels = unique(trial_numeric)))
  
  return(test_predictions)
  
}

plot_survival_predictions <- function(test_predictions, current_subject){
# This function creates and plots survival predictions for a given subject from a test predictions dataframe.
#
# Arguments:
# - test_predictions: A dataframe containing survival predictions. This dataframe should include columns for
#   'trial_time' (time points of the prediction), 'pred_CIF' (predicted cumulative incidence function values),
#   'trial_numeric' (identifier for the trial), and 'turntime_real' (actual time to event).
# - current_subject: A character string or numeric value representing the subject for whom the plot is generated.
#   This is used to customize the plot title to indicate the subject's predictions being displayed.
#
# The function performs the following steps to create the plot:
# 1. Initializes a ggplot object using the 'test_predictions' dataframe. It sets 'trial_time' as the x-axis,
#    'pred_CIF' as the y-axis, and uses 'trial_numeric' to color-code the points, providing a visual distinction
#    between trials.
# 2. Adds a shaded rectangle from 0 to 0.5 on the x-axis and 0 to 1 on the y-axis using 'geom_rect'. This rectangle
#    represents the 500ms window during which the model made its predictions, highlighting the prediction interval.
# 3. Uses 'geom_vline' to draw vertical lines at the 'turntime_real' for each trial, indicating the true turnaround
#    time. The lines are color-coded by 'trial_numeric' and set to a transparency of 0.7.
# 4. Plots the predicted probabilities as points on the graph with 'geom_point', allowing for a direct visual
#    comparison between the predicted and actual turnaround times.
# 5. Applies the Viridis color scale to the plot, enhancing visual clarity and accessibility.
# 6. Customizes the plot's appearance (background, text color, text size, legend positioning, title) for better
#    readability and professional presentation.
# 7. Sets the y-axis limits to 0-1 and x-axis limits to 0-2.5, framing the plot within the relevant range of
#    probabilities and time.
# 8. Adds a title to the plot using 'ggtitle', including the subject identifier to specify whose predictions are
#    being visualized.
# 9. Labels the x-axis as "Time" and the y-axis as "Probability of Turning Around", clearly indicating what the
#    plot represents.
#
# The function concludes by printing the plot, making it visible for review or further analysis. This plot can be
# used to assess the accuracy of survival predictions against actual outcomes, particularly in the context of
# longitudinal and survival data analysis.
  
  
  prediction_plot <- ggplot(test_predictions, aes(x = trial_time, y = pred_CIF, color = as.numeric(trial_numeric))) +
    # representing the 500ms window the model was given in order to make its predictions
    geom_rect(aes(xmin=0, xmax=.5, ymin=0, ymax=1), fill = "lightgrey", alpha = .5, color = 'lightgrey') +
    # true turnaround time
    geom_vline(aes(xintercept = turntime_real, color = as.numeric(trial_numeric), alpha = .7)) +
    # predicted probabilities on turnaround time
    geom_point() +
    scale_color_viridis() +  # Using Viridis color scale
    theme(panel.background = element_rect(fill = "white"),
          legend.position = "none",
          axis.text = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
          plot.title = element_text(family = "Gill Sans", color = '#2D2327', size = 20),
          plot.subtitle = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
          axis.title = element_text(family = "Gill Sans", color = '#2D2327', size = 18)) +
    ylim(0, 1) + xlim(0, 3) + labs(color = "Test Trial") +
    ggtitle(paste0("Prediction on held out trials: ", current_subject)) +
    labs(x = "Time (s)", y = "Probability of Turning Around")
  
  print(prediction_plot)
  
  return(prediction_plot)
  
  
}

plot_correlation_plot <- function(test_predictions, current_subject){
# This function creates and displays a scatter plot comparing actual and predicted turnaround times
# for a specific subject given their test predictions dataset.
#
# Arguments:
# - test_predictions: A dataframe containing the test predictions. It must include at least 'trial_numeric'
#   as a trial identifier, 'turntime_real' as the actual turnaround time, 'pred_CIF' as the predicted cumulative
#   incidence function values, and 'trial_time' as the predicted time points.
# - current_subject: A character string or numeric value representing the subject for whom the plot is generated,
#   only used in the plot title.
#
# The function performs the following operations:
# 1. Prepares the data by calculating the absolute difference between 'pred_CIF' and 0.5 to find predictions
#    closest to a 50% cumulative incidence function, indicating a critical threshold for decision-making in
#    survival analysis. This step identifies the predicted turnaround time closest to this critical value for
#    each trial.
# 2. Filters the dataset to retain only the rows with the predicted turnaround time closest to the critical
#    threshold of 50% for each trial.
# 3. Selects distinct rows based on 'trial_numeric', 'turntime_real', and the calculated 'turntime_pred' to ensure
#    a clean dataset for plotting and correlation analysis.
# 4. Calculates the Pearson correlation coefficient ('cor_score') between the actual and predicted turnaround times
#    to quantify the linear relationship between these variables.
# 5. Generates a scatter plot using 'ggplot2' with actual turnaround times on the x-axis and predicted turnaround
#    times on the y-axis. Points are sized for visibility, and the plot background is set to white for clarity.
# 6. The plot is further customized with labels for both axes, set limits for x and y axes to focus on relevant
#    ranges, and a title that includes the current subject and the calculated correlation score.
#
# The function concludes by printing the scatter plot, allowing for visual inspection of the relationship between
# actual and predicted turnaround times. This visualization aids in evaluating the predictive performance of the
# model, specifically how well it can predict the turnaround time for the given subject.
  
  
  scatter_pred_df <- test_predictions %>%
    mutate(near_50 = abs(pred_CIF - .5)) %>%
    group_by(trial_numeric) %>%
    mutate(closest_to_50 = min(near_50)) %>%
    filter(closest_to_50 == near_50) %>%
    mutate(turntime_pred = trial_time) %>%
    ungroup() %>%
    select(trial_numeric, turntime_real, turntime_pred) %>%
    distinct()
  
  cor_score <- cor(log(scatter_pred_df$turntime_real), log(scatter_pred_df$turntime_pred))

  scatter_pred_plot <- scatter_pred_df %>%
    ggplot(., aes(x = log(turntime_real), y = log(turntime_pred))) +
    geom_point(size = 4) +
    geom_smooth(method = "lm", formula = "y ~x", color = "black", se = F) +
    theme(panel.background = element_rect(fill = "white"),
          legend.position = "none",
          axis.text = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
          plot.title = element_text(family = "Gill Sans", color = '#2D2327', size = 20),
          plot.subtitle = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
          axis.title = element_text(family = "Gill Sans", color = '#2D2327', size = 18)) +
    labs(x = "True Turnaround Time (logged)", y = "Predicted Turnaround Time (logged)") +
    ylim(.5, 2.5) + xlim(.5, 2.5) +
    ggtitle(paste0("Prediction Scatterplot: ", current_subject, "; Correlation: ", round(cor_score, 2)))
  
  print(scatter_pred_plot)
  
  return(scatter_pred_plot)
  
}
  
  
```


```{r, fig.width=6, fig.height=6}


current_subject <- "BJH016"
permuted <- FALSE

## Prep DF for Joint Model Fitting and select predictor variables ##
joint_dist_df <- prep_joint_orig_df(game_data_distance, current_subject, permuted)

# only ieeg trials
hc_sub_trials <- hc_theta_data %>%
  filter(subject == current_subject) %>%
  pull(trial_numeric) %>%
  unique()

joint_dist_df <- joint_dist_df %>%
  filter(trial_numeric %in% hc_sub_trials)

current_seed <- 53
fold <- 1
seed_fold <- paste0(current_seed, "-", fold)

## Fit Joint Model ##
file_name <- paste0(current_subject, "_", permuted, "_", seed_fold)
jm_fit <- readRDS(path(here(), "data", "joint_models", paste0(file_name, ".rds")))
summary(jm_fit)

## Prep Train/Test DFs ##
# longitudinal dfs
tmp <- jm_fit$model_data
train_long_data <- joint_dist_df %>%
  filter(trial_numeric %in% unique(tmp$idT))
test_long_data <- joint_dist_df %>%
  filter(!trial_numeric %in% unique(tmp$idT))

# survival dfs
cox_df <- create_survival_df(joint_dist_df %>% mutate(trial_numeric = round(trial_numeric, 2)))
train_cox_df <- cox_df %>%
  filter(trial_numeric %in% unique(tmp$idT))
test_cox_df <- cox_df %>%
  filter(!trial_numeric %in% unique(tmp$idT))



timepoints <- unique(test_cox_df$turnaround_time)
test_times <- quantile(timepoints[timepoints > .5], probs = c(.4, .5, .6))

roc_plot <- tvROC(jm_fit, newdata = test_long_data, Tstart = .5,
                   Thoriz = test_times[2], idVar = 'trial_numeric')


plot(roc_plot)

# get predictions
test_predictions <- predict_on_test_set(jm_fit, test_long_data, test_cox_df)




```


```{r, fig.width = 9, fig.height = 7}

# plot prediction plot
ggthemr("solarized")
surv_plot <- plot_survival_predictions(test_predictions, current_subject)


cns_pred_surv_plot <- surv_plot +
  theme(legend.position =  c(.8, 1.02)) +
  guides(alpha = F, color = guide_colourbar(direction = "horizontal", label = F)) +
  labs(color = "") +
  ggtitle("Prediction on 24 held out trials", subtitle = "vertical lines indicate true turnaround times\n") 
  
ggsave(path(here(), "figures", "survival", "survival_prediction_plot.png"), cns_pred_surv_plot, width = 9.25, height = 7.5)


```


```{r, fig.width = 7, fig.height = 7}

# plot correlation plot
cor_plot <- plot_correlation_plot(test_predictions, current_subject)


cns_cor_plot <- cor_plot +
  ylim(-.25, 1.5) + xlim(-.25, 1.5) +
  ggtitle("Correlation between true and predicted\nchoice to avoid", subtitle = "pearson correlation: 0.55\n") 
  


ggsave(path(here(), "figures", "survival", "correlation_prediction_plot.png"), cns_cor_plot, width = 6.75, height = 7.5)


```

width = 9.25, height = 7.5)
```{r, fig.width = 7, fig.height = 4}

png(path(here(), "figures", "survival", "fig3_3_roc_behave_plot.png"), width = 7, height = 7.5, units = 'in', res = 300)



# Customizing margins and adding titles manually
par(mar = c(5, 5.5, 4, 2) + 0.1, family = "Gill Sans")

plot(roc_plot, pch = 30, col = "#278BD2", cex = 1.4,
     ylab = "Sensitivity", xlab = "1 - Specificity",
     font.lab = 1.25, # Change according to the available fonts in your R session
     col.lab = "#2D2327", col.axis = "#2D2327",
     cex.lab = 1.8, cex.axis = 1.4,
     bg = "white")

# Adding a linear model line similar to geom_smooth
# abline(lm(y ~ x), col = "black")


title(main = "ROC Curve ~ AUC = .80",
      col.main = "#2D2327", font.main = 2, cex.main = 1.8)


dev.off()

```
```{r, fig.width = 7, fig.height = 4, format= 'asis'}

## take this and put it in overleaf for a pretty table
jm_fit_table <- summary(jm_fit)$Survival
rownames(jm_fit_table) <- c("Distance to Ghost", "Points Remaining")


```


## Theta Modeling 

```{r}

predict_on_test_set <- function(jm_fit, test_long_data, test_cox_df){
# This function generates predictions on a test set for a fitted joint model.
#
# The function takes three arguments:
# - jm_fit: A fitted joint model object. This model should be previously fitted using longitudinal and survival data.
# - test_long_data: A dataframe containing the test longitudinal data. This dataframe should include the same
#   variables used for fitting the joint model.
# - test_cox_df: A dataframe containing the test survival data.
#
# The function performs the following operations:
# 1. Filters the test_long_data to include only observations where 'jm_time' is less than 0.5. The model uses these 500ms 
#    to predict the turning time in a given heald out trial
# 2. Selects relevant columns from test_long_data, excluding 'turnaround_time' and 'EVENT', so there is no way it could use 
#    that info to make its predictions
# 3. Uses the 'predict' function on the 'jm_fit' model, passing the preprocessed test longitudinal data. It
#    specifies to process events, return the modified test data with predictions, identifies the unique ID variable,
#    and sets the time points for prediction as a sequence from 0.5 to 2.5 in steps of 0.05.
# 4. Renames the 'turnaround_time' column to 'turntime_real' in the test_cox_df for clarity and selects only
#    the necessary columns ('trial_numeric' and 'turntime_real') for joining with the predictions.
# 5. Performs a left join of the test predictions with the survival data (test_cox_df) based on 'trial_numeric' to
#    combine predictions with actual survival times.
# 6. Arranges the resulting dataframe by 'turntime_real' to ensure predictions are sorted by the actual survival times.
# 7. Converts the 'trial_numeric' variable to a factor, with levels specified as the unique values of 'trial_numeric',
#    for better handling in subsequent analyses or plots.
#
# Finally, the function returns the dataframe 'test_predictions', which contains the survival predictions alongside
# the actual survival times, ready for evaluation or further analysis.
  
  test_pred_df <- test_long_data %>% 
    filter(turnaround_time > 0.5) %>%
    filter(jm_time < .5) %>%
    mutate(EVENT = 0) %>%
    mutate(turnaround_time = .5)
  
  test_predictions <- predict(jm_fit, 
                        newdata = test_pred_df, process = "event", return_newdata = TRUE, 
                        idVar = "trial_numeric", times = seq(.5, 5, .05))
  
  test_cox_df <- test_cox_df %>% rename(turntime_real = turnaround_time) %>% select(trial_numeric, turntime_real)
  test_predictions <- left_join(test_predictions, test_cox_df, by = "trial_numeric")
  
  test_predictions <- test_predictions %>%
    arrange(turntime_real) %>%
    mutate(trial_numeric = factor(trial_numeric, levels = unique(trial_numeric)))
  
  return(test_predictions)
  
}

plot_survival_predictions <- function(test_predictions, current_subject){
# This function creates and plots survival predictions for a given subject from a test predictions dataframe.
#
# Arguments:
# - test_predictions: A dataframe containing survival predictions. This dataframe should include columns for
#   'jm_time' (time points of the prediction), 'pred_CIF' (predicted cumulative incidence function values),
#   'trial_numeric' (identifier for the trial), and 'turntime_real' (actual time to event).
# - current_subject: A character string or numeric value representing the subject for whom the plot is generated.
#   This is used to customize the plot title to indicate the subject's predictions being displayed.
#
# The function performs the following steps to create the plot:
# 1. Initializes a ggplot object using the 'test_predictions' dataframe. It sets 'jm_time' as the x-axis,
#    'pred_CIF' as the y-axis, and uses 'trial_numeric' to color-code the points, providing a visual distinction
#    between trials.
# 2. Adds a shaded rectangle from 0 to 0.5 on the x-axis and 0 to 1 on the y-axis using 'geom_rect'. This rectangle
#    represents the 500ms window during which the model made its predictions, highlighting the prediction interval.
# 3. Uses 'geom_vline' to draw vertical lines at the 'turntime_real' for each trial, indicating the true turnaround
#    time. The lines are color-coded by 'trial_numeric' and set to a transparency of 0.7.
# 4. Plots the predicted probabilities as points on the graph with 'geom_point', allowing for a direct visual
#    comparison between the predicted and actual turnaround times.
# 5. Applies the Viridis color scale to the plot, enhancing visual clarity and accessibility.
# 6. Customizes the plot's appearance (background, text color, text size, legend positioning, title) for better
#    readability and professional presentation.
# 7. Sets the y-axis limits to 0-1 and x-axis limits to 0-2.5, framing the plot within the relevant range of
#    probabilities and time.
# 8. Adds a title to the plot using 'ggtitle', including the subject identifier to specify whose predictions are
#    being visualized.
# 9. Labels the x-axis as "Time" and the y-axis as "Probability of Turning Around", clearly indicating what the
#    plot represents.
#
# The function concludes by printing the plot, making it visible for review or further analysis. This plot can be
# used to assess the accuracy of survival predictions against actual outcomes, particularly in the context of
# longitudinal and survival data analysis.
  
  
  prediction_plot <- ggplot(test_predictions, aes(x = jm_time, y = pred_CIF, color = as.numeric(trial_numeric))) +
    # representing the 500ms window the model was given in order to make its predictions
    geom_rect(aes(xmin=0, xmax=.5, ymin=0, ymax=1), fill = "lightgrey", alpha = .5, color = 'lightgrey') +
    # true turnaround time
    geom_vline(aes(xintercept = turntime_real, color = as.numeric(trial_numeric), alpha = .7)) +
    # predicted probabilities on turnaround time
    geom_point() +
    scale_color_viridis() +  # Using Viridis color scale
    theme(panel.background = element_rect(fill = "white"),
          legend.position = "none",
          axis.text = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
          plot.title = element_text(family = "Gill Sans", color = '#2D2327', size = 20),
          plot.subtitle = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
          axis.title = element_text(family = "Gill Sans", color = '#2D2327', size = 18)) +
    ylim(0, 1) + xlim(0, 3) + labs(color = "Test Trial") +
    ggtitle(paste0("Prediction on held out trials: ", current_subject)) +
    labs(x = "Time (s)", y = "Probability of Turning Around")
  
  print(prediction_plot)
  
  return(prediction_plot)
  
  
}

plot_correlation_plot <- function(test_predictions, current_subject){
# This function creates and displays a scatter plot comparing actual and predicted turnaround times
# for a specific subject given their test predictions dataset.
#
# Arguments:
# - test_predictions: A dataframe containing the test predictions. It must include at least 'trial_numeric'
#   as a trial identifier, 'turntime_real' as the actual turnaround time, 'pred_CIF' as the predicted cumulative
#   incidence function values, and 'jm_time' as the predicted time points.
# - current_subject: A character string or numeric value representing the subject for whom the plot is generated,
#   only used in the plot title.
#
# The function performs the following operations:
# 1. Prepares the data by calculating the absolute difference between 'pred_CIF' and 0.5 to find predictions
#    closest to a 50% cumulative incidence function, indicating a critical threshold for decision-making in
#    survival analysis. This step identifies the predicted turnaround time closest to this critical value for
#    each trial.
# 2. Filters the dataset to retain only the rows with the predicted turnaround time closest to the critical
#    threshold of 50% for each trial.
# 3. Selects distinct rows based on 'trial_numeric', 'turntime_real', and the calculated 'turntime_pred' to ensure
#    a clean dataset for plotting and correlation analysis.
# 4. Calculates the Pearson correlation coefficient ('cor_score') between the actual and predicted turnaround times
#    to quantify the linear relationship between these variables.
# 5. Generates a scatter plot using 'ggplot2' with actual turnaround times on the x-axis and predicted turnaround
#    times on the y-axis. Points are sized for visibility, and the plot background is set to white for clarity.
# 6. The plot is further customized with labels for both axes, set limits for x and y axes to focus on relevant
#    ranges, and a title that includes the current subject and the calculated correlation score.
#
# The function concludes by printing the scatter plot, allowing for visual inspection of the relationship between
# actual and predicted turnaround times. This visualization aids in evaluating the predictive performance of the
# model, specifically how well it can predict the turnaround time for the given subject.
  
  
  scatter_pred_df <- test_predictions %>%
    mutate(near_50 = abs(pred_CIF - .5)) %>%
    group_by(trial_numeric) %>%
    mutate(closest_to_50 = min(near_50)) %>%
    filter(closest_to_50 == near_50) %>%
    mutate(turntime_pred = jm_time) %>%
    ungroup() %>%
    select(trial_numeric, turntime_real, turntime_pred) %>%
    distinct()
  
  cor_score <- cor(log(scatter_pred_df$turntime_real),
                   log(scatter_pred_df$turntime_pred))

  scatter_pred_plot <- scatter_pred_df %>%
    ggplot(., aes(x = log(turntime_real), y = log(turntime_pred))) +
    geom_point(size = 4) +
    geom_smooth(method = "lm", formula = "y ~x", color = "black", se = F) +
    theme(panel.background = element_rect(fill = "white"),
          legend.position = "none",
          axis.text = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
          plot.title = element_text(family = "Gill Sans", color = '#2D2327', size = 20),
          plot.subtitle = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
          axis.title = element_text(family = "Gill Sans", color = '#2D2327', size = 18)) +
    labs(x = "True Turnaround Time (logged)", y = "Predicted Turnaround Time (logged)") +
    ylim(.5, 2.5) + xlim(.5, 2.5) +
    ggtitle(paste0("Prediction Scatterplot: ", current_subject, "; Correlation: ", round(cor_score, 2)))
  
  print(scatter_pred_plot)
  
  return(scatter_pred_plot)
  
}
  
  
```



```{r, fig.width=6, fig.height=6}


current_subject <- "BJH016"
permuted <- FALSE

## Prep DF for Joint Model Fitting and select predictor variables ##
joint_dist_df <- prep_joint_df(game_data_distance, current_subject, permuted)

# only ieeg trials
hc_sub_trials <- hc_theta_data %>%
  filter(subject == current_subject) %>%
  pull(trial_numeric) %>%
  unique()

joint_dist_df <- joint_dist_df %>%
  filter(trial_numeric %in% hc_sub_trials)

current_seed <- 1
fold <- 4
seed_fold <- paste0(current_seed, "-", fold)

# only ieeg trials
hc_sub_trials <- hc_theta_data %>%
  filter(subject == current_subject) %>%
  pull(trial_numeric) %>%
  unique()

sub_theta_df <- hc_theta_data %>%
  filter(subject == current_subject) %>%
  filter(!is.na(theta)) %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  group_by(trial_time, trial_numeric) %>%
  mutate(mean_theta = mean(theta)) %>%
  select(-theta, -electrode) %>%
  distinct() %>%
  group_by(trial_numeric) %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  ungroup()

joint_dist_df <- inner_join(sub_theta_df, joint_dist_df, by = c("subject", "trial_numeric", "trial_time"))

## Fit Joint Model ##
file_name <- paste0(current_subject, "_", permuted, "_", seed_fold)
jm_theta_fit <- readRDS(path(here(), "data", "joint_models", paste0(file_name, "_theta_time.rds")))
summary(jm_theta_fit)

## Prep Train/Test DFs ##
# longitudinal dfs
tmp <- jm_theta_fit$model_data
train_long_data <- joint_dist_df %>%
  filter(trial_numeric %in% unique(tmp$idT))
test_long_data <- joint_dist_df %>%
  filter(!trial_numeric %in% unique(tmp$idT))

# survival dfs
cox_df <- create_survival_df(joint_dist_df %>% mutate(trial_numeric = round(trial_numeric, 2)))
train_cox_df <- cox_df %>%
  filter(trial_numeric %in% unique(tmp$idT))
test_cox_df <- cox_df %>%
  filter(!trial_numeric %in% unique(tmp$idT))



timepoints <- unique(test_cox_df$turnaround_time)
test_times <- quantile(timepoints[timepoints > .5], probs = c(.4, .5, .6))

roc_plot <- tvROC(jm_theta_fit, newdata = test_long_data, Tstart = .5,
                   Thoriz = test_times[2], idVar = 'trial_numeric')

auc <- tvAUC(jm_theta_fit, newdata = test_long_data, Tstart = .5,
                   Thoriz = test_times[2], idVar = 'trial_numeric')


plot(roc_plot)

# get predictions
test_predictions <- predict_on_test_set(jm_theta_fit, test_long_data, test_cox_df)

```

```{r, fig.width = 9, fig.height = 7}

# plot prediction plot
ggthemr("solarized")
surv_plot <- plot_survival_predictions(test_predictions, current_subject)


cns_pred_surv_plot <- surv_plot +
  theme(legend.position =  c(.8, 1.02)) +
  guides(alpha = F, color = guide_colourbar(direction = "horizontal", label = F)) +
  labs(color = "") +
  ggtitle("Prediction on 24 held out trials", subtitle = "vertical lines indicate true turnaround times\n") 
  
ggsave(path(here(), "figures", "survival", "survival_theta_prediction_plot.png"), cns_pred_surv_plot, width = 9.25, height = 7.5)


```


```{r, fig.width = 7, fig.height = 7}

# plot correlation plot
cor_plot <- plot_correlation_plot(test_predictions, current_subject)


cns_cor_plot <- cor_plot +
  ylim(-.25, 1.5) + xlim(-.25, 1.5) +
  ggtitle("Correlation between true and \npredicted choice to avoid", subtitle = "pearson correlation: 0.19\n") 
  


ggsave(path(here(), "figures", "survival", "correlation_theta_prediction_plot.png"), cns_cor_plot, width = 7, height = 7.5)


```


```{r, fig.width = 7, fig.height = 4}

png(path(here(), "figures", "survival", "roc_theta_behave_plot.png"), width = 7, height = 7.5, units = 'in', res = 300)



# Customizing margins and adding titles manually
par(mar = c(5, 5.5, 4, 2) + 0.1, family = "Gill Sans")

plot(roc_plot, pch = 30, col = "#278BD2", cex = 1.4,
     ylab = "Sensitivity", xlab = "1 - Specificity",
     font.lab = 1.25, # Change according to the available fonts in your R session
     col.lab = "#2D2327", col.axis = "#2D2327",
     cex.lab = 1.8, cex.axis = 1.4,
     bg = "white")

# Adding a linear model line similar to geom_smooth
# abline(lm(y ~ x), col = "black")


title(main = "ROC Curve ~ AUC = .67",
      col.main = "#2D2327", font.main = 2, cex.main = 1.8)


dev.off()

```


```{r, fig.width = 7, fig.height = 4, format= 'asis'}

## take this and put it in overleaf for a pretty table
jm_theta_fit_table <- summary(jm_theta_fit)$Survival
rownames(jm_theta_fit_table) <- c("Theta")

kable(jm_theta_fit_table)
```

```{r, fig.width = 3, fig.height = 4}

behave_fig <- game_data_distance %>%
  filter(trial_numeric == 42 & subject == "BJH016") %>%
  select(distance_to_ghost, points_remaining, trial_time) %>%
  mutate(threat = scale(distance_to_ghost)) %>%
  mutate(reward = scale(points_remaining)) %>%
  select(-distance_to_ghost, -points_remaining) %>%
  pivot_longer(cols = c("threat", "reward"), names_to = "variable", values_to = "value") %>%
  ggplot(., aes(x = trial_time, y = value, color = variable)) +
  geom_line(size = 2) +
  theme(panel.background = element_rect(fill = "white"),
        legend.position = "top",
        axis.text = element_text(family = "Gill Sans", color = '#2D2327', size = 14),
        plot.title = element_text(family = "Gill Sans", color = '#2D2327', size = 18),
        axis.title = element_text(family = "Gill Sans", color = '#2D2327', size = 18)) +
  scale_color_manual(values = c("#86C8B7", "#FB6087")) +
  labs(y = "", x = "Time", color = "") +
  ggtitle("Behavior")

ggsave(path(here(), "figures", "survival", "behave_fig.png"), behave_fig, width = 3, height = 4)

```



