---
title: "Onset Across Region Analysis"
output: html_document
date: "2023-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(ggeffects)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lmerTest)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))
source(path(here(), "R", 'separate_mfg_sfg.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)


## set colors ##
roi_colors <-  c("Amygdala" = "#DE4A4D", "Hippocampus" = "#FFA602", "OFC" =  "#88D1A3", "Ant. Cingulate"=  "#3D99BA", "MFG" =  "#876194")


```


```{r read-behave-data}

# behavioral data #
all_subs_g_dist <- read_csv(path(here(), "munge", "all_subs_complete_distance_df.csv"))
all_subs_ng_dist <- read_csv(path(here(), "munge", "all_subs_noghost_complete_distance_df.csv"))


all_move_df <- bind_rows(all_subs_g_dist, all_subs_ng_dist) %>% 
  mutate(trial_time = round(trial_time, 2)) %>%
  group_by(subject, trial_numeric) %>%
  mutate(first_move_tmp = c(0, diff(move_step))) %>%
  mutate(first_move_time = trial_time[min(which(first_move_tmp != 0))]) %>%
  select(subject, trial_numeric, first_move_time) %>%
  distinct()


```


# Delta
 
```{r load-delta-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "delta_ieeg_hc_all_subs_logged_iti_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "delta_ieeg_amyg_all_subs_logged_iti_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "delta_ieeg_ofc_all_subs_logged_iti_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "delta_ieeg_cing_all_subs_logged_iti_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "delta_ieeg_dlpfc_all_subs_logged_iti_onset.csv"))

# crop time 
hc_onset_df <- hc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
ofc_onset_df <- ofc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
cing_onset_df <- cing_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
amyg_onset_df <- amyg_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)

# separate dlpfc into sfg and mfg
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(electrode = gsub("_.*", "", electrode))
dlpfc_onset_df <- separate_mfg_sfg(dlpfc_onset_df)
sfg_onset_df <- dlpfc_onset_df %>% filter(sfg == 1) %>% select(-sfg, -mfg)
mfg_onset_df <- dlpfc_onset_df %>% filter(mfg == 1) %>% select(-sfg, -mfg)


## Bind together ##
delta_onset_df <- rbind(hc_onset_df %>% mutate(region = "Hippocampus"),
                  amyg_onset_df %>% mutate(region = "Amygdala"),
                  ofc_onset_df %>% mutate(region = "OFC"),
                  cing_onset_df %>% mutate(region = "Ant. Cingulate"),
                  mfg_onset_df %>% mutate(region = "MFG"))

## Bind with behave data ##
delta_onset_df <- delta_onset_df %>%
  left_join(all_move_df , by = c("subject", "trial_numeric"))

```


```{r plot-scaled, warning = F}

delta_onset_plot_df <- delta_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )

delta_move_only_onset_plot_df <- delta_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  filter(trial_time >= first_move_time) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )

delta_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("Delta") +
  ylim(-0.5, .5)
  

delta_move_only_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("Delta") +
  ylim(-0.5, .5)
  

```
# Theta 

```{r load-theta-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "theta_ieeg_hc_all_subs_logged_iti_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "theta_ieeg_amyg_all_subs_logged_iti_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "theta_ieeg_ofc_all_subs_logged_iti_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "theta_ieeg_cing_all_subs_logged_iti_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "theta_ieeg_dlpfc_all_subs_logged_iti_onset.csv"))

# crop time 
hc_onset_df <- hc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
ofc_onset_df <- ofc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
cing_onset_df <- cing_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
amyg_onset_df <- amyg_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)

# separate dlpfc into sfg and mfg
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(electrode = gsub("_.*", "", electrode))
dlpfc_onset_df <- separate_mfg_sfg(dlpfc_onset_df)
sfg_onset_df <- dlpfc_onset_df %>% filter(sfg == 1) %>% select(-sfg, -mfg)
mfg_onset_df <- dlpfc_onset_df %>% filter(mfg == 1) %>% select(-sfg, -mfg)


## Bind together ##
theta_onset_df <- rbind(hc_onset_df %>% mutate(region = "Hippocampus"),
                  amyg_onset_df %>% mutate(region = "Amygdala"),
                  ofc_onset_df %>% mutate(region = "OFC"),
                  cing_onset_df %>% mutate(region = "Ant. Cingulate"),
                  mfg_onset_df %>% mutate(region = "MFG"))

## Bind with behave data ##
theta_onset_df <- theta_onset_df %>%
  left_join(all_move_df , by = c("subject", "trial_numeric"))


```


```{r plot-scaled}

theta_onset_plot_df <- theta_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )


theta_move_only_onset_plot_df <- theta_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  filter(trial_time >= first_move_time) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )


theta_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("theta") +
  ylim(-0.5, .5)
  

theta_move_only_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("theta") +
  ylim(-0.5, .5)

```

# Alpha

```{r load-alpha-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "alpha_ieeg_hc_all_subs_logged_iti_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "alpha_ieeg_amyg_all_subs_logged_iti_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "alpha_ieeg_ofc_all_subs_logged_iti_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "alpha_ieeg_cing_all_subs_logged_iti_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "alpha_ieeg_dlpfc_all_subs_logged_iti_onset.csv"))

# crop time 
hc_onset_df <- hc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
ofc_onset_df <- ofc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
cing_onset_df <- cing_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
amyg_onset_df <- amyg_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)

# separate dlpfc into sfg and mfg
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(electrode = gsub("_.*", "", electrode))
dlpfc_onset_df <- separate_mfg_sfg(dlpfc_onset_df)
sfg_onset_df <- dlpfc_onset_df %>% filter(sfg == 1) %>% select(-sfg, -mfg)
mfg_onset_df <- dlpfc_onset_df %>% filter(mfg == 1) %>% select(-sfg, -mfg)


## Bind together ##
alpha_onset_df <- rbind(hc_onset_df %>% mutate(region = "Hippocampus"),
                  amyg_onset_df %>% mutate(region = "Amygdala"),
                  ofc_onset_df %>% mutate(region = "OFC"),
                  cing_onset_df %>% mutate(region = "Ant. Cingulate"),
                  mfg_onset_df %>% mutate(region = "MFG"))

## Bind with behave data ##
alpha_onset_df <- alpha_onset_df %>%
  left_join(all_move_df , by = c("subject", "trial_numeric"))


```


```{r plot-scaled}

alpha_onset_plot_df <- alpha_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )


alpha_move_only_onset_plot_df <- alpha_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  filter(trial_time >= first_move_time) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )


alpha_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("Alpha") +
  ylim(-0.5, .5)
  

alpha_move_only_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("Alpha") +
  ylim(-0.5, .5)

```

# Beta

```{r load-beta-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "beta_ieeg_hc_all_subs_logged_iti_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "beta_ieeg_amyg_all_subs_logged_iti_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "beta_ieeg_ofc_all_subs_logged_iti_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "beta_ieeg_cing_all_subs_logged_iti_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "beta_ieeg_dlpfc_all_subs_logged_iti_onset.csv"))

# crop time 
hc_onset_df <- hc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
ofc_onset_df <- ofc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
cing_onset_df <- cing_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
amyg_onset_df <- amyg_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)

# separate dlpfc into sfg and mfg
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(electrode = gsub("_.*", "", electrode))
dlpfc_onset_df <- separate_mfg_sfg(dlpfc_onset_df)
sfg_onset_df <- dlpfc_onset_df %>% filter(sfg == 1) %>% select(-sfg, -mfg)
mfg_onset_df <- dlpfc_onset_df %>% filter(mfg == 1) %>% select(-sfg, -mfg)


## Bind together ##
beta_onset_df <- rbind(hc_onset_df %>% mutate(region = "Hippocampus"),
                  amyg_onset_df %>% mutate(region = "Amygdala"),
                  ofc_onset_df %>% mutate(region = "OFC"),
                  cing_onset_df %>% mutate(region = "Ant. Cingulate"),
                  mfg_onset_df %>% mutate(region = "MFG"))

## Bind with behave data ##
beta_onset_df <- beta_onset_df %>%
  left_join(all_move_df , by = c("subject", "trial_numeric"))


```


```{r plot-scaled}

beta_onset_plot_df <- beta_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )


beta_move_only_onset_plot_df <- beta_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  filter(trial_time >= first_move_time) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )


beta_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("Beta") +
  ylim(-0.5, .5)
  

beta_move_only_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("Beta") +
  ylim(-0.5, .5)

```

# Gamma

```{r load-gamma-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "gamma_ieeg_hc_all_subs_logged_iti_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "gamma_ieeg_amyg_all_subs_logged_iti_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "gamma_ieeg_ofc_all_subs_logged_iti_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "gamma_ieeg_cing_all_subs_logged_iti_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "gamma_ieeg_dlpfc_all_subs_logged_iti_onset.csv"))

# crop time 
hc_onset_df <- hc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
ofc_onset_df <- ofc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
cing_onset_df <- cing_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
amyg_onset_df <- amyg_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)

# separate dlpfc into sfg and mfg
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(electrode = gsub("_.*", "", electrode))
dlpfc_onset_df <- separate_mfg_sfg(dlpfc_onset_df)
sfg_onset_df <- dlpfc_onset_df %>% filter(sfg == 1) %>% select(-sfg, -mfg)
mfg_onset_df <- dlpfc_onset_df %>% filter(mfg == 1) %>% select(-sfg, -mfg)


## Bind together ##
gamma_onset_df <- rbind(hc_onset_df %>% mutate(region = "Hippocampus"),
                  amyg_onset_df %>% mutate(region = "Amygdala"),
                  ofc_onset_df %>% mutate(region = "OFC"),
                  cing_onset_df %>% mutate(region = "Ant. Cingulate"),
                  mfg_onset_df %>% mutate(region = "MFG"))


## Bind with behave data ##
gamma_onset_df <- gamma_onset_df %>%
  left_join(all_move_df , by = c("subject", "trial_numeric"))


```


```{r plot-scaled}

gamma_onset_plot_df <- gamma_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )


gamma_move_only_onset_plot_df <- gamma_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  filter(trial_time >= first_move_time) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )


gamma_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("Gamma") +
  ylim(-0.5, .5)
  

gamma_move_only_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("Gamma") +
  ylim(-0.5, .5)


```

# HFA

```{r load-hfa-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "hfa_ieeg_hc_all_subs_logged_iti_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "hfa_ieeg_amyg_all_subs_logged_iti_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "hfa_ieeg_ofc_all_subs_logged_iti_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "hfa_ieeg_cing_all_subs_logged_iti_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "hfa_ieeg_dlpfc_all_subs_logged_iti_onset.csv"))

# crop time 
hc_onset_df <- hc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
ofc_onset_df <- ofc_onset_df %>% 
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
cing_onset_df <- cing_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
amyg_onset_df <- amyg_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(trial_time = trial_time - 3)  %>%
  filter(trial_time >= -1)

# separate dlpfc into sfg and mfg
dlpfc_onset_df <- dlpfc_onset_df %>%
  mutate(electrode = gsub("_.*", "", electrode))
dlpfc_onset_df <- separate_mfg_sfg(dlpfc_onset_df)
sfg_onset_df <- dlpfc_onset_df %>% filter(sfg == 1) %>% select(-sfg, -mfg)
mfg_onset_df <- dlpfc_onset_df %>% filter(mfg == 1) %>% select(-sfg, -mfg)


## Bind together ##
hfa_onset_df <- rbind(hc_onset_df %>% mutate(region = "Hippocampus"),
                  amyg_onset_df %>% mutate(region = "Amygdala"),
                  ofc_onset_df %>% mutate(region = "OFC"),
                  cing_onset_df %>% mutate(region = "Ant. Cingulate"),
                  mfg_onset_df %>% mutate(region = "MFG"))



## Bind with behave data ##
hfa_onset_df <- hfa_onset_df %>%
  left_join(all_move_df , by = c("subject", "trial_numeric"))


```


```{r plot-scaled}

hfa_onset_plot_df <- hfa_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )


hfa_move_only_onset_plot_df <- hfa_onset_df %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  filter(trial_time >= first_move_time) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  summarise(elec_power = mean(theta), .groups = 'drop') %>%
  group_by(region, trial_time, subject) %>%
  summarise(sub_power = mean(elec_power), .groups = 'drop') %>%
  group_by(region, trial_time) %>%
  summarise(
    all_power = mean(sub_power, na.rm = TRUE),
    n = n(),
    sd_sub_power = sd(sub_power, na.rm = TRUE),
    lower_sem = all_power - sd_sub_power / sqrt(n),
    upper_sem = all_power + sd_sub_power / sqrt(n),
    .groups = 'drop'
  )


hfa_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("HFA") +
  ylim(-0.5, .5)
  

hfa_move_only_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = all_power, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values =roi_colors) +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  ggtitle("HFA") +
  ylim(-0.5, .5)

```



## By region


```{r}

onset_plot_df <- bind_rows(delta_onset_plot_df %>% mutate(freq = "Delta"),
                           theta_onset_plot_df %>% mutate(freq = "Theta"),
                          alpha_onset_plot_df %>% mutate(freq = "Alpha"),
                          beta_onset_plot_df %>% mutate(freq = "Beta"),
                          gamma_onset_plot_df %>% mutate(freq = "Gamma"),
                          hfa_onset_plot_df %>% mutate(freq = "HFA")) %>%
  mutate(freq = factor(freq, levels = c("Delta", "Theta", "Alpha", "Beta", "Gamma", "HFA")))

  onset_no_move_plot_df <- bind_rows(delta_move_only_onset_plot_df %>% mutate(freq = "Delta"),
                           theta_move_only_onset_plot_df %>% mutate(freq = "Theta"),
                          alpha_move_only_onset_plot_df %>% mutate(freq = "Alpha"),
                          beta_move_only_onset_plot_df %>% mutate(freq = "Beta"),
                          gamma_move_only_onset_plot_df %>% mutate(freq = "Gamma"),
                          hfa_move_only_onset_plot_df %>% mutate(freq = "HFA")) %>%
  mutate(freq = factor(freq, levels = c("Delta", "Theta", "Alpha", "Beta", "Gamma", "HFA")))

```


```{r all-plot, fig.height =4, fig.width = 12}


onset_plot_df %>%
  filter(!freq %in% c("Gamma", "HFA")) %>%
  ggplot(., aes(x = trial_time, y = all_power, color = freq, fill = freq)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line(size = 1) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_viridis(discrete = T, option = "D") +
  scale_fill_viridis(discrete = T, option = "D") +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  facet_wrap(~region, nrow = 1)

onset_no_move_plot_df %>%
  filter(!freq %in% c("Gamma", "HFA")) %>%
  ggplot(., aes(x = trial_time, y = all_power, color = freq, fill = freq)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_line(size = 1) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_viridis(discrete = T, option = "D") +
  scale_fill_viridis(discrete = T, option = "D") +
  scale_x_continuous(breaks = c(0, 2, 4), limits = c(-1, 5)) +
  facet_wrap(~region, nrow = 1)


```




