---
title: "turnaround Across Region Analysis"
output: html_document
date: "2023-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(ggeffects)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lmerTest)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)



```

# Delta

Comparing across regions, we see 4/7 subjects have bumps in amygdal delta before turnaround. Maybe in OFC as well, but less clear. Drops in dlpfc very clear on average, more difficult to see person by person.

```{r load-delta-data}

## Load Region specific csvs ##
hc_turnaround_df <- read_csv(path(here(), "munge", "delta_hc_all_subs_turnaround.csv"))
amyg_turnaround_df <- read_csv(path(here(), "munge", "delta_amyg_all_subs_turnaround.csv"))
ofc_turnaround_df <- read_csv(path(here(), "munge", "delta_ofc_all_subs_turnaround.csv"))
cing_turnaround_df <- read_csv(path(here(), "munge", "delta_cing_all_subs_turnaround.csv"))
dlpfc_turnaround_df <- read_csv(path(here(), "munge", "delta_dlpfc_all_subs_turnaround.csv"))
insula_turnaround_df <- read_csv(path(here(), "munge", "delta_insula_all_subs_turnaround.csv"))

## Bind together ##
delta_turnaround_df <- rbind(hc_turnaround_df %>% mutate(region = "hc"),
                  amyg_turnaround_df %>% mutate(region = "amyg"),
                  ofc_turnaround_df %>% mutate(region = "ofc"),
                  cing_turnaround_df %>% mutate(region = "cing"),
                  dlpfc_turnaround_df %>% mutate(region = "dlpfc"),
                  insula_turnaround_df %>% mutate(region = "insula"))

# adjust time, adjust electrode label #
delta_turnaround_df <- delta_turnaround_df %>%
  mutate(trial_time = trial_time - 1) %>%
  filter(trial_time < 2 & trial_time > -2) %>%
  mutate(ghost = if_else(grepl("noghost", electrode), "noghost", "ghost")) %>%
  mutate(electrode = gsub("_.*", "", electrode))

```


```{r plot-delta}

delta_turnaround_plot_df <- delta_turnaround_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta)) 
  

delta_turnaround_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), alpha = .2) +
  geom_point() +
  geom_line(width = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("Delta")
  

delta_turnaround_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line(size = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject, scales = "free_y")

```


# Theta 


```{r load-theta-data}

## Load Region specific csvs ##
hc_turnaround_df <- read_csv(path(here(), "munge", "theta_hc_all_subs_turnaround.csv"))
amyg_turnaround_df <- read_csv(path(here(), "munge", "theta_amyg_all_subs_turnaround.csv"))
ofc_turnaround_df <- read_csv(path(here(), "munge", "theta_ofc_all_subs_turnaround.csv"))
cing_turnaround_df <- read_csv(path(here(), "munge", "theta_cing_all_subs_turnaround.csv"))
dlpfc_turnaround_df <- read_csv(path(here(), "munge", "theta_dlpfc_all_subs_turnaround.csv"))
insula_turnaround_df <- read_csv(path(here(), "munge", "theta_insula_all_subs_turnaround.csv"))

## Bind together ##
theta_turnaround_df <- rbind(hc_turnaround_df %>% mutate(region = "hc"),
                  amyg_turnaround_df %>% mutate(region = "amyg"),
                  ofc_turnaround_df %>% mutate(region = "ofc"),
                  cing_turnaround_df %>% mutate(region = "cing"),
                  dlpfc_turnaround_df %>% mutate(region = "dlpfc"),
                  insula_turnaround_df %>% mutate(region = "insula"))


# adjust time #
theta_turnaround_df <- theta_turnaround_df %>%
  mutate(trial_time = trial_time - 1) %>%
  filter(trial_time < 2 & trial_time > -2) %>%
  mutate(ghost = if_else(grepl("noghost", electrode), "noghost", "ghost")) %>%
  mutate(electrode = gsub("_.*", "", electrode))

```


```{r plot-theta}

theta_turnaround_average_df <- theta_turnaround_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta))
  

theta_turnaround_average_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), alpha = .2) +
  geom_point(size = 2) +
  geom_line(width = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("Theta")
  

theta_turnaround_average_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point(size = 2) +
  geom_line(size = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject, scales = "free_y")

```

# Alpha

```{r load-alpha-data}

## Load Region specific csvs ##
hc_turnaround_df <- read_csv(path(here(), "munge", "alpha_hc_all_subs_turnaround.csv"))
amyg_turnaround_df <- read_csv(path(here(), "munge", "alpha_amyg_all_subs_turnaround.csv"))
ofc_turnaround_df <- read_csv(path(here(), "munge", "alpha_ofc_all_subs_turnaround.csv"))
cing_turnaround_df <- read_csv(path(here(), "munge", "alpha_cing_all_subs_turnaround.csv"))
dlpfc_turnaround_df <- read_csv(path(here(), "munge", "alpha_dlpfc_all_subs_turnaround.csv"))
insula_turnaround_df <- read_csv(path(here(), "munge", "alpha_insula_all_subs_turnaround.csv"))

## Bind together ##
alpha_turnaround_df <- rbind(hc_turnaround_df %>% mutate(region = "hc"),
                  amyg_turnaround_df %>% mutate(region = "amyg"),
                  ofc_turnaround_df %>% mutate(region = "ofc"),
                  cing_turnaround_df %>% mutate(region = "cing"),
                  dlpfc_turnaround_df %>% mutate(region = "dlpfc"),
                  insula_turnaround_df %>% mutate(region = "insula"))

# adjust time #
alpha_turnaround_df <- alpha_turnaround_df %>%
  mutate(trial_time = trial_time - 1) %>%
  filter(trial_time < 2 & trial_time > -2) %>%
  mutate(ghost = if_else(grepl("noghost", electrode), "noghost", "ghost")) %>%
  mutate(electrode = gsub("_.*", "", electrode))

```


```{r plot-alpha}

alpha_turnaround_plot_df <- alpha_turnaround_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta)) 
  
alpha_turnaround_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), alpha = .2) +
  geom_point(size = 2) +
  geom_line(width = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("Alpha")
  

alpha_turnaround_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point(size = 2) +
  geom_line(size = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject, scales = "free_y")

```

# Beta

```{r load-beta-data}


## Load Region specific csvs ##
hc_turnaround_df <- read_csv(path(here(), "munge", "beta_hc_all_subs_turnaround.csv"))
amyg_turnaround_df <- read_csv(path(here(), "munge", "beta_amyg_all_subs_turnaround.csv"))
ofc_turnaround_df <- read_csv(path(here(), "munge", "beta_ofc_all_subs_turnaround.csv"))
cing_turnaround_df <- read_csv(path(here(), "munge", "beta_cing_all_subs_turnaround.csv"))
dlpfc_turnaround_df <- read_csv(path(here(), "munge", "beta_dlpfc_all_subs_turnaround.csv"))
insula_turnaround_df <- read_csv(path(here(), "munge", "beta_insula_all_subs_turnaround.csv"))

## Bind together ##
beta_turnaround_df <- rbind(hc_turnaround_df %>% mutate(region = "hc"),
                  amyg_turnaround_df %>% mutate(region = "amyg"),
                  ofc_turnaround_df %>% mutate(region = "ofc"),
                  cing_turnaround_df %>% mutate(region = "cing"),
                  dlpfc_turnaround_df %>% mutate(region = "dlpfc"),
                  insula_turnaround_df %>% mutate(region = "insula"))

# adjust time #
beta_turnaround_df <- beta_turnaround_df %>%
  mutate(trial_time = trial_time - 1) %>%
  filter(trial_time < 2 & trial_time > -2) %>%
  mutate(ghost = if_else(grepl("noghost", electrode), "noghost", "ghost")) %>%
  mutate(electrode = gsub("_.*", "", electrode))

```


```{r plot-beta}

beta_turnaround_plot_df <- beta_turnaround_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta)) 
  
beta_turnaround_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), alpha = .2) +
  geom_point(size = 2) +
  geom_line(width = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("Beta")
  

beta_turnaround_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point(size = 2) +
  geom_line(size = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject, scales = "free_y")
  

```




# Gamma

```{r load-gamma-data}


## Load Region specific csvs ##
hc_turnaround_df <- read_csv(path(here(), "munge", "gamma_hc_all_subs_turnaround.csv"))
amyg_turnaround_df <- read_csv(path(here(), "munge", "gamma_amyg_all_subs_turnaround.csv"))
ofc_turnaround_df <- read_csv(path(here(), "munge", "gamma_ofc_all_subs_turnaround.csv"))
cing_turnaround_df <- read_csv(path(here(), "munge", "gamma_cing_all_subs_turnaround.csv"))
dlpfc_turnaround_df <- read_csv(path(here(), "munge", "gamma_dlpfc_all_subs_turnaround.csv"))
insula_turnaround_df <- read_csv(path(here(), "munge", "gamma_insula_all_subs_turnaround.csv"))

## Bind together ##
gamma_turnaround_df <- rbind(hc_turnaround_df %>% mutate(region = "hc"),
                  amyg_turnaround_df %>% mutate(region = "amyg"),
                  ofc_turnaround_df %>% mutate(region = "ofc"),
                  cing_turnaround_df %>% mutate(region = "cing"),
                  dlpfc_turnaround_df %>% mutate(region = "dlpfc"),
                  insula_turnaround_df %>% mutate(region = "insula"))

# adjust time #
gamma_turnaround_df <- gamma_turnaround_df %>%
  mutate(trial_time = trial_time - 1) %>%
  filter(trial_time < 2 & trial_time > -2) %>%
  mutate(ghost = if_else(grepl("noghost", electrode), "noghost", "ghost")) %>%
  mutate(electrode = gsub("_.*", "", electrode))

```


```{r plot-gamma}

gamma_turnaround_plot_df <- gamma_turnaround_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta)) 
  
gamma_turnaround_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), alpha = .2) +
  geom_point(size = 2) +
  geom_line(width = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("gamma")
  

gamma_turnaround_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point(size = 2) +
  geom_line(size = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject)
  

```

# HFA

```{r load-hfa-data}


## Load Region specific csvs ##
hc_turnaround_df <- read_csv(path(here(), "munge", "hfa_hc_all_subs_turnaround.csv"))
amyg_turnaround_df <- read_csv(path(here(), "munge", "hfa_amyg_all_subs_turnaround.csv"))
ofc_turnaround_df <- read_csv(path(here(), "munge", "hfa_ofc_all_subs_turnaround.csv"))
cing_turnaround_df <- read_csv(path(here(), "munge", "hfa_cing_all_subs_turnaround.csv"))
dlpfc_turnaround_df <- read_csv(path(here(), "munge", "hfa_dlpfc_all_subs_turnaround.csv"))
insula_turnaround_df <- read_csv(path(here(), "munge", "hfa_insula_all_subs_turnaround.csv"))

## Bind together ##
hfa_turnaround_df <- rbind(hc_turnaround_df %>% mutate(region = "hc"),
                  amyg_turnaround_df %>% mutate(region = "amyg"),
                  ofc_turnaround_df %>% mutate(region = "ofc"),
                  cing_turnaround_df %>% mutate(region = "cing"),
                  dlpfc_turnaround_df %>% mutate(region = "dlpfc"),
                  insula_turnaround_df %>% mutate(region = "insula"))

# adjust time #
hfa_turnaround_df <- hfa_turnaround_df %>%
  mutate(trial_time = trial_time - 1) %>%
  filter(trial_time < 2 & trial_time > -2) %>%
  mutate(ghost = if_else(grepl("noghost", electrode), "noghost", "ghost")) %>%
  mutate(electrode = gsub("_.*", "", electrode))

```


```{r plot-hfa}

hfa_turnaround_plot_df <- hfa_turnaround_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta))
  
hfa_turnaround_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), alpha = .2) +
  geom_point(size = 2) +
  geom_line(width = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("hfa")
  

hfa_turnaround_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point(size = 2) +
  geom_line(size = 2) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject)
  

```



