---
title: "Ghost Attack Rts"
output: html_document
date: "2024-03-29"
---

```{r setup, include=FALSE}
## libraries ##
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(lmtest)
library(scales)
library(ggthemr)
library(RColorBrewer)
library(broom.mixed)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))
source(path(here(), "R", 'compile_ieeg_csv_files.R'))
source(path(here(), "R", 'run_and_plot_lme_models.R'))

## plotting helpers ##
ggthemr("light")
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

```


```{r load-data}

dlpfc_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_dlpfc_all_subs_logged_iti_onset.csv"))
cing_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_cing_all_subs_logged_iti_onset.csv"))
hc_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_hc_all_subs_logged_iti_onset.csv"))
dlpfc_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_dlpfc_all_subs_logged_iti_onset.csv"))

dlpfc_hfa_data <- read_csv( path(here(), "munge", "hfa_ieeg_dlpfc_all_subs_logged_iti_onset.csv"))
dlpfc_gamma_data <- read_csv( path(here(), "munge", "gamma_ieeg_dlpfc_all_subs_logged_iti_onset.csv"))

# behavioral data #
all_subs_g_dist <- read_csv(path(here(), "munge", "all_subs_complete_distance_df.csv"))
all_subs_ng_dist <- read_csv(path(here(), "munge", "all_subs_noghost_complete_distance_df.csv"))

# combine ghost and no ghost #
all_subs_dist <- all_subs_g_dist %>% 
  select(-GhostLocation, -distance_to_ghost, -min_distance, -cdf_distance)
all_subs_dist <- rbind(all_subs_dist, all_subs_ng_dist)


```


```{r merge-ieeg-data-behave-data}

# hfa data #
dlpfc_hfa_data <- dlpfc_hfa_data %>% 
  mutate(freq = "hfa") %>%
  rename(power = theta) %>%
  mutate(electrode = gsub("_.*", "", electrode))

dlpfc_gamma_data <- dlpfc_gamma_data %>% 
  mutate(freq = "gamma") %>%
  rename(power = theta) %>%
  mutate(electrode = gsub("_.*", "", electrode))

# bind gamma, hfa data #
dlpfc_data <- full_join(dlpfc_hfa_data, dlpfc_gamma_data, by = c("subject", "trial_numeric", "trial_time", "electrode", "freq", "power"))

# average gamma + hfa #
dlpfc_data <- dlpfc_data %>% 
  group_by(subject, trial_numeric, trial_time, electrode) %>%
  mutate(avg_power = mean(power)) %>%
  select(-freq, -power) %>%
  distinct() %>%
  rename(power = avg_power) %>%
  mutate(freq = "hfa_gamma") %>%
  mutate(region = "dlpfc")

# prep theta data #
dlpfc_theta_data <- dlpfc_theta_data %>% 
  mutate(freq = "theta") %>%
  mutate(region = "dlpfc") %>%
  rename(power = theta) %>%
  mutate(electrode = gsub("_.*", "", electrode))

cing_data <- cing_theta_data %>% 
  mutate(freq = "theta") %>%
  mutate(region = "cing") %>%
  rename(power = theta) %>%
  mutate(electrode = gsub("_.*", "", electrode))

hc_data <- hc_theta_data %>% 
  mutate(freq = "theta") %>%
  mutate(region = "hc") %>%
  rename(power = theta) %>%
  mutate(electrode = gsub("_.*", "", electrode))


# bind ieeg data #
ieeg_data <- bind_rows(dlpfc_data, dlpfc_theta_data, cing_data, hc_data)


ieeg_behave_data <- right_join(all_subs_g_dist %>% select(-move_step) %>% mutate(trial_time = round(trial_time, 2)), 
                             ieeg_data %>% mutate(trial_time = round(trial_time, 2)), by = join_by(subject, trial_numeric, trial_time))

```


```{r read-in-attack-tables}

## load and compile attack tables ##
for(sub in unique(all_subs_dist$subject)){
  
  tmp <- read_csv(path(here(), "data", "ieeg_behave", paste0(sub, "_attack_events.csv")))
  tmp <- tmp %>%
    mutate(subject = sub)
  
  if(exists("attack_events")){
    attack_events <- bind_rows(attack_events, tmp)
  } else {
    attack_events <- tmp
  }
  
}

## modify to get trials of interest ##
attack_events <- attack_events %>%
  mutate(trial_numeric = neural_trial_numeric + 1) %>%
  mutate(attacks_ids = paste0(subject, "_", trial_numeric))


```


```{r shift-to-turnaround}

# shift to center around turnaround  #
turnaround_df <- ieeg_behave_data %>%
  # round time so that we can loop over time later
  mutate(trial_time = round(trial_time, 2)) %>%
  # filiter out ITI
  filter(reward_groups != 99 & !is.na(electrode)) %>%
  # prep electrode variables
  mutate(elec_id = paste0(subject, "_", gsub("_.*", "", electrode))) %>%
  # shift the time so that time 0 is the start of movement onset
  group_by(elec_id, trial_numeric, subject, freq, region) %>%
  # filter time so that trials end when the person turnaround for the final time
  mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
  mutate(event = replace(event, is.na(event), 0)) %>%
  mutate(turnaround_time = if_else(event == 1, trial_time, 0)) %>%
  mutate(turnaround_time = max(turnaround_time)) %>%
  mutate(time = trial_time - turnaround_time) %>%
  ungroup() 



```

## EDA

```{r, fig.width = 15, fig.height = 15}


turnaround_df %>%
  mutate(time = round(time, 2)) %>%
  filter(time >= -2 & time <= 2) %>%
  mutate(reg_f = paste0(region, "_", freq)) %>%
  group_by(subject, reg_f, time, elec_id) %>%
  mutate(elec_power = mean(power)) %>%
  select(-power, -trial_numeric) %>%
  distinct() %>%
  group_by(subject, reg_f, time) %>%
  mutate(sub_power = mean(elec_power)) %>%
  select(-elec_power, -elec_id) %>%
  distinct() %>%
  ggplot(aes(x = time, y = sub_power, color = reg_f)) +
  geom_point() +
  geom_line() +
  facet_wrap(~subject) +
  theme_minimal() 



```

```{r, fig.width = 12, fig.height = 6}


turnaround_df %>%
  mutate(time = round(time, 2)) %>%
  filter(time >= -2 & time <= 2) %>%
  mutate(reg_f = paste0(region, "_", freq)) %>%
  group_by(subject, reg_f, time, elec_id) %>%
  mutate(elec_power = mean(power)) %>%
  select(-power, -trial_numeric) %>%
  distinct() %>%
  group_by(subject, reg_f, time) %>%
  mutate(sub_power = mean(elec_power)) %>%
  select(-elec_power, -elec_id) %>%
  distinct() %>%
  group_by(reg_f, time) %>%
  mutate(mean_power = mean(sub_power, na.rm = T)) %>%
  ggplot(aes(x = time, y = mean_power, color = reg_f)) +
  geom_point() +
  geom_line() +
  theme_minimal() 


```

```{r, fig.width = 8, fig.height = 10}

roi_colors <-  c("Amygdala" = "#DE4A4D", "Hippocampus - Theta" = "#FFA602", "OFC" =  "#88D1A3", "Ant. Cingulate - Theta"=  "#3D99BA", "Insula" =  "#876194",  "dlPFC - HFA" = "#FB6087" ,  "dlPFC - Theta" = "#FB6087")

turnaround_df %>%
  mutate(time = round(time, 2)) %>%
  filter(time >= -2 & time <= 2) %>%
  mutate(reg_f = paste0(region, "_", freq)) %>%
  filter(reg_f != "dlpfc_theta") %>%
  mutate(reg_f = if_else(reg_f == "cing_theta", "Ant. Cingulate - Theta", 
                         if_else(reg_f == "dlpfc_theta", "dlPFC - Theta",
                         if_else(reg_f == "dlpfc_hfa_gamma", "dlPFC - HFA", "Hippocampus - Theta")))) %>%
  mutate(trial_ids = paste0(subject, "_", trial_numeric)) %>%
  mutate(attack_trial = if_else(trial_ids %in% attack_events$attacks_ids, "attack", "safe")) %>%
  group_by(subject, reg_f, time, attack_trial, elec_id) %>%
  mutate(elec_power = mean(power)) %>%
  select(-power, -trial_numeric) %>%
  distinct() %>%
  group_by(subject, reg_f, time, attack_trial) %>%
  mutate(sub_power = mean(elec_power)) %>%
  select(-elec_power, -elec_id) %>%
  distinct() %>%
  group_by(reg_f, time, attack_trial) %>%
  mutate(mean_power = mean(sub_power, na.rm = T)) %>%
  ggplot(aes(x = time, y = mean_power, color = reg_f, linetype = freq)) +
  geom_vline(xintercept = 0, color = "darkgrey") +
  geom_line(size = 1) +
    theme(panel.background = element_rect(fill = "white"), 
        legend.position = "top",
        axis.text = element_text(family = "Gill Sans", color = "#2D2327", size = 14),
        axis.title = element_text(family = "Gill Sans", color = "#2D2327", size = 16),
        legend.text  = element_text(family = "Gill Sans", color = "#2D2327", size = 16),
        strip.text = element_text(family = "Gill Sans", color = "#2D2327", size = 16),
        plot.title = element_text(family = "Gill Sans", color = "#2D2327", size = 18)) +
  scale_color_manual(values = roi_colors) +
  scale_linetype_manual(values = c("dotted", "solid")) +
  facet_wrap(~attack_trial, ncol = 1) +
  labs(y = "Average Power", x = "Time (s)", title = "Average Power by Region and Attack/Safe Trials", color = "")


```

```{r attack-rts}
# filter to turn times
attack_rt_df <- turnaround_df %>%
  mutate(trial_ids = paste0(subject, "_", trial_numeric)) %>%
  filter(trial_ids %in% attack_events$attacks_ids) %>%
  select(subject, trial_numeric, sample, trial_time, turnaround_time) %>%
  distinct()

# merge with attack events 
attack_rt_df <- left_join(attack_rt_df, attack_events %>% select(subject, trial_numeric, sample, event), by = c("subject", "trial_numeric", "sample"))

# calculate rt 
attack_rt_clean_df <- attack_rt_df %>%
  mutate(event = if_else(is.na(event), 9999, 1)) %>%
  mutate(attack_time = if_else(event == 1, trial_time, 9999)) %>%
  group_by(subject, trial_numeric) %>%
  mutate(attack_time = min(attack_time, na.rm = T)) %>%
  ungroup() %>%
  filter(attack_time != 9999) %>%
  filter(turnaround_time != 0) %>%
  rowwise() %>%
  mutate(attack_rt = turnaround_time - attack_time) %>%
  select(subject, trial_numeric, attack_time, turnaround_time, attack_rt) %>%
  distinct() %>%
  filter(attack_rt > 0) %>% # sometimes they turned before the ghost attacked
  group_by(subject) %>%
  mutate(mean_sub_rt = mean(attack_rt))


attack_rt_clean_df %>%
  ggplot(., aes(x = attack_rt)) +
  geom_density() +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~subject)


mean(attack_rt_clean_df$attack_rt)

```

```{r by-subject, fig.width = 15, fig.height = 10}

roi_colors <-  c("Amygdala" = "#DE4A4D", "Hippocampus" = "#FFA602", "OFC" =  "#88D1A3", "Ant. Cingulate"=  "#3D99BA", "Insula" =  "#876194",  "dlPFC" = "#FB6087")


turnaround_rt_rep_df <- turnaround_df %>%
  mutate(time = round(time, 2)) %>%
  filter(time >= -2 & time <= 2) %>%
  mutate(reg_f = paste0(region, "_", freq)) %>%
  mutate(reg_f = if_else(reg_f == "cing_theta", "Ant. Cingulate", 
                         if_else(reg_f == "dlpfc_hfa_gamma", "dlPFC", "Hippocampus"))) %>%
  mutate(trial_ids = paste0(subject, "_", trial_numeric)) %>%
  mutate(attack_trial = if_else(trial_ids %in% attack_events$attacks_ids, "attack", "safe")) %>%
  filter(attack_trial == "attack")



turn_rt_df <- left_join(turnaround_rt_rep_df, attack_rt_clean_df, by = c("subject", "trial_numeric", "turnaround_time"))

turn_rt_df %>%
  filter(!is.na(attack_rt)) %>%
  group_by(subject, reg_f, time, attack_trial, elec_id) %>%
  mutate(elec_power = mean(power)) %>%
  select(-power, -trial_numeric) %>%
  distinct() %>%
  group_by(subject, reg_f, time, attack_trial) %>%
  mutate(sub_power = mean(elec_power)) %>%
  select(-elec_power, -elec_id) %>%
  distinct() %>%
  ggplot(aes(x = time, y = sub_power, color = reg_f)) +
  geom_vline(aes(xintercept = -1*mean_sub_rt), color = "#DE0D16", linetype = "dashed") +
  geom_vline(xintercept = 0, color = "darkgrey") +
  geom_line(size = 1) +
  theme_minimal() +
  scale_color_manual(values = roi_colors) +
  facet_wrap(~subject, ncol = 4, scales = "free")


```






