---
title: "Prediction Error"
output: html_document
date: "2024-02-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,  # don't print the code chunk
  warning = FALSE,  # don't print warnings
  message = FALSE,  # don't print messages
  fig.width = 8,  # set default width of figures
  fig.height = 5,  # set default height of figures
  fig.align = "center",  # always align figure in center
  fig.pos = "H",  # always plot figure at the exact location of the code chunk
  cache = FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(effectsize)
library(scales)
library(JMbayes2)
library(caret)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", "clean_behavioral_data.R"))
source(path(here(), "R", "create_distance_df.R"))
source(path(here(), "R", "joint_modeling_functions.R"))

## plotting helpers ##
ggthemr("solarized")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)

```


```{r load-data}

ofc_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_ofc_all_subs_logged_iti_onset.csv"))

# behavioral data #
all_subs_g_dist <- read_csv(path(here(), "munge", "all_subs_complete_distance_df.csv"))
all_subs_ng_dist <- read_csv(path(here(), "munge", "all_subs_noghost_complete_distance_df.csv"))

# combine ghost and no ghost #
all_subs_dist <- all_subs_g_dist %>% 
  select(-GhostLocation, -distance_to_ghost, -min_distance, -cdf_distance)
all_subs_dist <- rbind(all_subs_dist, all_subs_ng_dist)

# add ITI to behavioral df
behavior_iti_df <- all_subs_dist %>% 
  select(subject, trial_numeric, trial_time) %>%
  filter(trial_time < 1) %>%
  mutate(trial_time = round(trial_time - 1, 2))

all_subs_dist <- full_join(all_subs_dist, behavior_iti_df)



```


```{r add-ghost-direction}

all_subs_g_dist <- all_subs_g_dist %>%
  group_by(subject, trial_numeric) %>%
  mutate(ghost_objective_direction_tmp = c(FALSE, diff(GhostLocation))) %>%
  mutate(ghost_objective_direction = if_else(ghost_objective_direction_tmp >= 2, "Right", 
                                             if_else(ghost_objective_direction_tmp <= -2, "Left", "still"))) %>%
  # select(-ghost_objective_direction_tmp) %>%
  mutate(ghost_direction = if_else((base_start_location < 100 & ghost_objective_direction == "Left") |
                                     (base_start_location > 100 & ghost_objective_direction == "Right") , "Towards",
                                   if_else(ghost_objective_direction == "still", "still", "Away"))) %>%
  mutate(new_ghost_direction = ifelse(ghost_direction == "still", NA, ghost_direction)) %>%
  fill(new_ghost_direction, .direction = "downup") %>%
  mutate(ghost_direction = ifelse(is.na(new_ghost_direction), ghost_direction, new_ghost_direction)) %>%
  select(-new_ghost_direction) %>%
  mutate(ghost_start_dir = first(ghost_direction))

```


```{r dots-eaten, fig.width=15, fig.height=10}

all_subs_g_dist <- all_subs_g_dist %>%
  mutate(points_remaining_scaled = scale(points_remaining))

dots_dir_df <- all_subs_g_dist %>%
  group_by(subject, trial_numeric) %>%
  mutate(trial_points = max(points_aquired)) %>%
  select(subject, trial_numeric, dots_eaten, trial_points, ghost_start_dir) %>%
  distinct() %>%
  ungroup() %>%
  filter(ghost_start_dir != "still") %>%
  mutate(trial_points = scale(trial_points)) 


dots_dir_df %>%
  ggplot(., aes(x = factor(ghost_start_dir), y = ..count.., fill = ghost_start_dir)) +
  geom_bar(position = "dodge", stat = "count") +
  theme_minimal() +
  facet_wrap(~subject) 

dots_dir_df %>%
  ggplot(., aes(x = factor(dots_eaten), y = ..count.., fill = ghost_start_dir)) +
  geom_bar(position = "dodge", stat = "count") +
  theme_minimal() +
  facet_wrap(~subject) 


```


```{r lms-dots_eatn}

summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df))


summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH016")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH021")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH025")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH027")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH029")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH039")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH041")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL10")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL12")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL14")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL17")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "SLCH002")))

# weird ones
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH026")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL13")))
summary(lm(dots_eaten ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL19")))



```

```{r lms-dots_eatn}



summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df))


summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH016")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH021")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH025")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH027")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH029")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH039")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH041")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL10")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL12")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL14")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL17")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "SLCH002")))

# weird ones
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "BJH026")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL13")))
summary(lm(trial_points ~ ghost_start_dir, data = dots_dir_df %>% filter(subject == "LL19")))



```


