---
title: "BJH025 Turnaround Exploration"
output: html_document
date: "2024-03-14"
---

```{r setup, include=FALSE}
## libraries ##
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(lmtest)
library(scales)
library(ggthemr)
library(RColorBrewer)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))
source(path(here(), "R", 'compile_ieeg_csv_files.R'))
source(path(here(), "R", 'run_and_plot_lme_models.R'))

## plotting helpers ##
ggthemr("light")
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

```

```{r load-data}

# ofc_theta_data <- read_csv( path(here(), "data_mount", "remote", "pacman_behavior",  "munge", "theta_ieeg_ofc_all_subs_logged_iti_onset.csv"))
ofc_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_ofc_all_subs_logged_iti_onset.csv"))

# behavioral data #
all_subs_g_dist <- read_csv(path(here(), "munge", "all_subs_complete_distance_df.csv"))
all_subs_ng_dist <- read_csv(path(here(), "munge", "all_subs_noghost_complete_distance_df.csv"))

# combine ghost and no ghost #
all_subs_dist <- all_subs_g_dist %>% 
  select(-GhostLocation, -distance_to_ghost, -min_distance, -cdf_distance)
all_subs_dist <- rbind(all_subs_dist, all_subs_ng_dist)

all_subs_g_dist <- all_subs_g_dist %>%
  group_by(subject, trial_numeric) %>%
  mutate(ghost_objective_direction_tmp = c(FALSE, diff(GhostLocation))) %>%
  mutate(ghost_objective_direction = if_else(ghost_objective_direction_tmp >= 2, "Right", 
                                             if_else(ghost_objective_direction_tmp <= -2, "Left", "still"))) %>%
  # select(-ghost_objective_direction_tmp) %>%
  mutate(ghost_direction = if_else((base_start_location < 100 & ghost_objective_direction == "Left") |
                                     (base_start_location > 100 & ghost_objective_direction == "Right") , "Towards",
                                   if_else(ghost_objective_direction == "still", "still", "Away"))) %>%
  mutate(new_ghost_direction = ifelse(ghost_direction == "still", NA, ghost_direction)) %>%
  fill(new_ghost_direction, .direction = "downup") %>%
  mutate(ghost_direction = ifelse(is.na(new_ghost_direction), ghost_direction, new_ghost_direction)) %>%
  select(-new_ghost_direction) %>%
  filter(ghost_direction != "still") %>%
  filter(attack_chase_bob == "Bob") 

# add ITI to behavioral df
behavior_iti_df <- all_subs_dist %>% 
  select(subject, trial_numeric, trial_time) %>%
  filter(trial_time < 1) %>%
  mutate(trial_time = round(trial_time - 1, 2))

all_subs_dist <- full_join(all_subs_dist, behavior_iti_df)

```
```{r}

# merge behavior data with ieeg data
brain_behave_df <- left_join(all_subs_g_dist %>% select(-move_step) %>% mutate(trial_time = round(trial_time, 2)), 
                             ofc_theta_data %>% mutate(trial_time = round(trial_time, 2)))


# prep for linear mixed effects models #
brain_behave_lme_df <- brain_behave_df %>%
  filter(attack_chase_bob == "Bob") %>%
  # round time so that we can loop over time later
  mutate(trial_time = round(trial_time, 2)) %>%
  # exclude time before they started moving, may be good to look at not doing this as well
  filter(Direction != "Still") %>%
  # filiter out ITI
  filter(reward_groups != 99 & !is.na(electrode)) %>%
  # prep electrode variables
  mutate(elec_id = paste0(subject, "_", gsub("_.*", "", electrode))) %>%
  mutate(electrode = gsub("_.*", "", electrode)) %>%
  # shift the time so that time 0 is the start of movement onset
  group_by(elec_id, trial_numeric, subject) %>%
  # shift trial time so that 0 is turnaround
  mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
  mutate(event = replace(event, is.na(event), 0)) %>%
  mutate(turnaround_time = if_else(event == 1, trial_time, 0)) %>%
  mutate(turn_time = round(trial_time - max(turnaround_time), 2)) %>%
  ungroup() %>%
  filter(turn_time > -2 & turn_time < 2) %>%
  # select and scale the necessary variables for the model
  # rowwise() %>%
  # mutate(combined_value = points_remaining * distance_to_ghost) %>%
  # mutate(discounted_value = points_remaining * 1/distance_to_ghost) %>%
  # mutate(discounted_4reward = if_else(Eaten == 5, 0, points_remaining * 1/abs(UserLocation - Biscuit5))) %>%
  # mutate(points_remaining_goal = if_else(dots_eaten == 5, points_remaining,
  #                                        if_else(dots_eaten == 4 & reward_groups %in% c(3, 4), points_remaining - 20, # ate 4 dots, big dot remaining
  #                                                if_else(dots_eaten == 4 & reward_groups %in% c(1, 2), points_remaining - 10,  # ate 4 dots, small dot remaining
  #                                                        if_else(dots_eaten == 3 & reward_groups %in% c(1, 2), points_remaining - 20 - 10,  # ate 3 dots, 1 big dot, 1 small dot remaining
  #                                                                if_else(dots_eaten == 3 & reward_groups == 4, points_remaining - 20 - 20,  # ate 3 dots, 2 big dots remaining
  #                                                                        if_else(dots_eaten == 3 & reward_groups == 3, points_remaining - 10 - 10, # ate 3 dots, 2 small dots remaining
  #                                                                                if_else(dots_eaten == 2 & reward_groups %in% c(1, 3), points_remaining - 10 - 10 -20, # ate 2 dots, 2 small dots remaining, 1 big
  #                                                                                        if_else(dots_eaten == 2 & reward_groups %in% c(2, 4), points_remaining - 20 - 20 - 10,  # ate 2 dots, 2 small big remaining, 1 small
  #                                                                                                if_else(dots_eaten == 1, points_remaining - 20 - 20 - 10 -10, # always same amount of reward after eating 1 dot
  #                                                                                                        0)))))))))) %>%
  # mutate(discounted_goal = if_else(dots_eaten == 5, points_remaining_goal * 1/(abs(UserLocation - Biscuit5)),
  #                                  if_else(dots_eaten == 4, points_remaining_goal * 1/(abs(UserLocation - Biscuit4)),
  #                                          if_else(dots_eaten == 3, points_remaining_goal * 1/(abs(UserLocation - Biscuit3)),
  #                                                  if_else(dots_eaten == 2, points_remaining_goal * 1/(abs(UserLocation - Biscuit2)),
  #                                                          if_else(dots_eaten == 1, points_remaining_goal * 1/(abs(UserLocation - Biscuit1)),
  #                                                                  0)))))) %>%
  # mutate(discounted_value_goal = points_remaining_goal * 1/distance_to_ghost) %>%                                      
  # ungroup() %>%
  select(subject, elec_id, theta, trial_numeric, turn_time, distance_to_ghost, points_remaining, Eaten,
         GhostLocation, UserLocation, discounted_reward)  %>%
  # mutate(combined_value = scale(combined_value)) %>%
  mutate(Eaten = scale(Eaten)) %>%
  # mutate(discounted_value = scale(discounted_value)) %>%
  mutate(UserLocation = scale(UserLocation)) %>%
  mutate(GhostLocation = scale(GhostLocation))  %>%
  # mutate(discounted_reward = scale(discounted_reward)) %>%
  # mutate(discounted_4reward = scale(discounted_4reward)) %>%
  # mutate(discounted_goal = scale(discounted_goal)) %>%
  mutate(distance_to_ghost = scale(distance_to_ghost)) %>%
  mutate(points_remaining = scale(points_remaining)) %>%
  # mutate(points_remaining_goal = scale(points_remaining_goal)) %>%
  mutate(reward_threat_diff = scale(points_remaining - distance_to_ghost)) %>%
  mutate(eaten_threat_diff = scale(Eaten - distance_to_ghost)) %>%
  mutate(nreward_threat_add = scale(distance_to_ghost + (-1*points_remaining))) %>%
  mutate(reward_threat_sum = scale(points_remaining + distance_to_ghost))



```

```{r, fig.width = 15, fig.height = 10}

brain_behave_lme_df %>%
  filter(subject == "BJH025" & elec_id == "BJH025_A1-A2") %>%
  filter(turn_time >= -1.2 & turn_time <= 1.2) %>%
  ggplot(., aes(x = distance_to_ghost, y = theta)) +
  geom_point() +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~turn_time, ncol = 15)


brain_behave_lme_df %>%
  filter(subject == "BJH025" & elec_id == "BJH025_A1-A2") %>%
  filter(turn_time >= -1.2 & turn_time <= 1.2) %>%
  group_by(turn_time) %>%
  mutate(scaled_dist = scale(distance_to_ghost)) %>%
  ungroup() %>%
  ggplot(., aes(x = scaled_dist, y = theta)) +
  geom_point() +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~turn_time, ncol = 15)


brain_behave_lme_df %>%
  filter(subject == "BJH025" & elec_id == "BJH025_A1-A2") %>%
  filter(turn_time >= -1.2 & turn_time <= 1.2) %>%
  group_by(turn_time) %>%
  mutate(scaled_dist = scale(distance_to_ghost)) %>%
  ungroup() %>%
  ggplot(., aes(x = scaled_dist, y = theta)) +
  geom_point() +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~turn_time, ncol = 15)



```

```{r, fig.width = 15, fig.height = 10}

brain_behave_lme_df %>%
  filter(subject == "BJH025" & elec_id == "BJH025_A1-A2") %>%
  filter(turn_time >= -1.2 & turn_time <= 1.2) %>%
  group_by(turn_time) %>%
  mutate(scaled_dist = scale(distance_to_ghost)) %>%
  ungroup() %>%
  ggplot(., aes(x = scaled_dist, y = theta)) +
  geom_point() +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~turn_time, ncol = 15)



brain_behave_lme_df %>%
  filter(subject == "BJH025" & elec_id == "BJH025_A1-A2") %>%
  filter(turn_time == 0) %>%
  group_by(turn_time) %>%
  mutate(scaled_dist = scale(distance_to_ghost)) %>%
  ungroup() %>%
  filter(scaled_dist < 4) %>%
  ggplot(., aes(x = scaled_dist, y = theta)) +
  geom_point() +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) 


tmp <- brain_behave_lme_df %>%
  filter(subject == "BJH025" & elec_id == "BJH025_A1-A2") %>%
  filter(turn_time == 0) %>%
  group_by(turn_time) %>%
  mutate(scaled_dist = scale(distance_to_ghost)) %>%
  ungroup() 

summary(lm(theta ~scaled_dist, data = tmp))
```


```{r}

# merge behavior data with ieeg data
brain_behave_df <- left_join(all_subs_g_dist %>% select(-move_step) %>% mutate(trial_time = round(trial_time, 2)), 
                             ofc_theta_data %>% mutate(trial_time = round(trial_time, 2)))


turn_times_df <- brain_behave_df %>%
    filter(subject == "BJH016") %>%
    # round time so that we  can loop over time later
    mutate(trial_time = round(trial_time, 2)) %>%
    # exclude time before they started moving, may be good to look at not doing this as well
    filter(Direction != "Still") %>%
    # filiter out ITI
    filter(reward_groups != 99 & !is.na(electrode)) %>%
    # prep electrode variables
    mutate(elec_id = paste0(subject, "_", gsub("_.*", "", electrode))) %>%
    mutate(electrode = gsub("_.*", "", electrode)) %>%
    # shift the time so that time 0 is the start of movement onset
    group_by(elec_id, trial_numeric, subject) %>%
    # shift trial time so that 0 is turnaround
    mutate(move_time = round(trial_time - first(trial_time), 2)) %>%
    mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
    mutate(event = replace(event, is.na(event), 0)) %>%
    mutate(turnaround_time = if_else(event == 1, move_time, 0)) %>%
    mutate(turnaround_time =max(turnaround_time)) %>%
    ungroup() %>%
    select(subject, trial_numeric, turnaround_time) %>%
    distinct()

brain_turnaround_lme_df <- brain_behave_df %>%
    filter(subject == "BJH016") %>%
    # round time so that we  can loop over time later
    mutate(trial_time = round(trial_time, 2)) %>%
    # exclude time before they started moving, may be good to look at not doing this as well
    filter(Direction != "Still") %>%
    # filiter out ITI
    filter(reward_groups != 99 & !is.na(electrode)) %>%
    # prep electrode variables
    mutate(elec_id = paste0(subject, "_", gsub("_.*", "", electrode))) %>%
    mutate(electrode = gsub("_.*", "", electrode)) %>%
    # shift the time so that time 0 is the start of movement onset
    group_by(elec_id, trial_numeric, subject) %>%
    # shift trial time so that 0 is turnaround
    mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
    mutate(event = replace(event, is.na(event), 0)) %>%
    mutate(turnaround_time = if_else(event == 1, trial_time, 0)) %>%
    mutate(turn_time = round(trial_time - max(turnaround_time), 2)) %>%
    ungroup() %>%
    group_by(turn_time) %>%
    # mutate(combined_value = scale(combined_value)) %>%
    mutate(Eaten = scale(Eaten)) %>%
    # mutate(discounted_value = scale(discounted_value)) %>%
    mutate(UserLocation = scale(UserLocation)) %>%
    mutate(GhostLocation = scale(GhostLocation))  %>%
    # mutate(discounted_reward = scale(discounted_reward)) %>%
    # mutate(discounted_4reward = scale(discounted_4reward)) %>%
    # mutate(discounted_goal = scale(discounted_goal)) %>%
    mutate(distance_to_ghost = scale(distance_to_ghost)) %>%
    mutate(points_remaining = scale(points_remaining)) %>%
    # mutate(points_remaining_goal = scale(points_remaining_goal)) %>%
    mutate(reward_threat_diff = scale(points_remaining - distance_to_ghost)) %>%
    mutate(eaten_threat_diff = scale(Eaten - distance_to_ghost)) %>%
    mutate(nreward_threat_add = scale(distance_to_ghost + (-1*points_remaining))) %>%
    mutate(reward_threat_sum = scale(points_remaining + distance_to_ghost)) %>%
    ungroup() %>%
    filter(turn_time > -1 & turn_time < 1) %>%
    select(subject, elec_id, theta, trial_numeric, turn_time, distance_to_ghost, points_remaining, Eaten, ghost_direction, GhostLocation, UserLocation, discounted_reward) 

    



brain_onset_lme_df <- brain_behave_df %>%
    filter(subject == "BJH016") %>%
    # round time so that we can loop over time later
    mutate(trial_time = round(trial_time, 2)) %>%
    # exclude time before they started moving, may be good to look at not doing this as well
    filter(Direction != "Still") %>%
    # filiter out ITI
    filter(reward_groups != 99 & !is.na(electrode)) %>%
    # prep electrode variables
    mutate(elec_id = paste0(subject, "_", gsub("_.*", "", electrode))) %>%
    mutate(electrode = gsub("_.*", "", electrode)) %>%
    # shift the time so that time 0 is the start of movement onset
    group_by(elec_id, trial_numeric, subject) %>%
    mutate(move_time = round(trial_time - first(trial_time), 2)) %>%
    # filter time so that trials end when the person turnaround for the final time
    mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
    mutate(event = replace(event, is.na(event), 0)) %>%
    mutate(turnaround_time = if_else(event == 1, move_time, 0)) %>%
    filter(move_time < max(turnaround_time)) %>%
    ungroup() %>%
    group_by(move_time) %>%
    mutate(Eaten = scale(Eaten)) %>%
    mutate(UserLocation = scale(UserLocation)) %>%
    mutate(GhostLocation = scale(GhostLocation))  %>%
    mutate(distance_to_ghost = scale(distance_to_ghost)) %>%
    mutate(points_remaining = scale(points_remaining)) %>%
    mutate(reward_threat_diff = scale(points_remaining - distance_to_ghost)) %>%
    mutate(eaten_threat_diff = scale(Eaten - distance_to_ghost)) %>%
    mutate(nreward_threat_add = scale(distance_to_ghost + (-1*points_remaining))) %>%
    mutate(reward_threat_sum = scale(points_remaining + distance_to_ghost)) %>%
    ungroup() %>%
    # filter to max time 3 since after 3s we start losing a lot of trials
    filter(move_time < 2) %>%
    select(subject, elec_id, theta, trial_numeric, move_time, distance_to_ghost, points_remaining, Eaten, ghost_direction,
          GhostLocation, UserLocation, discounted_reward) 


```





```{r fig.height = 5, fig.width = 10}

turnaround_moment_df <- brain_turnaround_lme_df %>%
  filter(subject == "BJH016" & turn_time == -.4 ) 

turnaround_moment_df %>%
  ggplot(., aes(x = UserLocation, y = theta)) +
  geom_point() +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~elec_id)

summary(lm(theta ~ UserLocation, data = turnaround_moment_df))


```

```{r fig.height = 5, fig.width = 10}

onset_moment_df <- brain_onset_lme_df %>%
  filter(subject == "BJH016" & move_time == 1.3 ) 

onset_moment_df %>%
  # filter(UserLocation  >= -1 & UserLocation <= 1) %>%
  ggplot(., aes(x = UserLocation, y = theta)) +
  geom_point() +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~elec_id)

summary(lm(theta ~ UserLocation, data = onset_moment_df))


```
```{r}

onset_overlap_times <- left_join(onset_moment_df, turn_times_df)

onset_overlap_times <- onset_overlap_times %>%
  mutate(diff_time = turnaround_time - move_time)

onset_overlap_times %>%
  ggplot(., aes(x = diff_time)) +
  geom_histogram() +
  theme_bw()

```




### PCA

````{r}

theta_pca_df <- brain_onset_lme_df %>%
  # select(subject, elec_id, trial_numeric, move_time, theta) %>%
  distinct() %>%
  pivot_wider(names_from = elec_id, values_from = theta)


pca_result <- prcomp(theta_pca_df[, 11:25], center = FALSE, scale. = FALSE)


summary(pca_result)
plot(pca_result, type = "l")

biplot(pca_result)

pc_result_df <- pca_result$x

pc_result_df <- cbind(theta_pca_df, pc_result_df)




```


```{r fig.height = 5, fig.width = 10}

onset_moment_df <- pc_result_df %>%
  filter(subject == "BJH016" & move_time == 1.3 ) 

onset_moment_df %>%
  ggplot(., aes(x = UserLocation, y = PC1)) +
  geom_point() +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) 

summary(lm(PC1 ~ UserLocation, data = onset_moment_df))
summary(lm(PC2 ~ UserLocation, data = onset_moment_df))
summary(lm(PC3 ~ UserLocation, data = onset_moment_df))

pc_result_df %>%
  ggplot(., aes(x = UserLocation, y = PC1)) +
  geom_point() +
  geom_smooth(method = "lm", formula = "y~x", color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~move_time)

```


