---
title: "Approach/Avoid Behavior Prep"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(ggeffects)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lmerTest)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)



```


# Prep for theta ~ behavioral analyses

Takes the behavoioral data and theta power data and combines them by trial type (ghost vs no ghost), as well as combined. 

Run by knitting

## Load Data

```{r SLCH002-data-load}

sl02_data <- read_csv(path(here(), './data/ieeg_behave/SLCH002_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

sl18_data <- read_csv(path(here(), './data/ieeg_behave/SLCH018_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


bjh16_data <- read_csv(path(here(), './data/ieeg_behave/BJH016_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh17_data <- read_csv(path(here(), './data/ieeg_behave/BJH017_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh21_data <- read_csv(path(here(), './data/ieeg_behave/BJH021_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh25_data <- read_csv(path(here(), './data/ieeg_behave/BJH025_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh26_data <- read_csv(path(here(), './data/ieeg_behave/BJH026_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh27_data <- read_csv(path(here(), './data/ieeg_behave/BJH027_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh29_data <- read_csv(path(here(), './data/ieeg_behave/BJH029_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh39_data <- read_csv(path(here(), './data/ieeg_behave/BJH039_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh41_data <- read_csv(path(here(), './data/ieeg_behave/BJH041_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh46_data <- read_csv(path(here(), './data/ieeg_behave/BJH046_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh50_data <- read_csv(path(here(), './data/ieeg_behave/BJH050_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh51_data <- read_csv(path(here(), './data/ieeg_behave/BJH051_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


ll10_data <- read_csv(path(here(), './data/ieeg_behave/ll10_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll12_data <- read_csv(path(here(), './data/ieeg_behave/ll12_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll13_data <- read_csv(path(here(), './data/ieeg_behave/ll13_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll14_data <- read_csv(path(here(), './data/ieeg_behave/ll14_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll17_data <- read_csv(path(here(), './data/ieeg_behave/ll17_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll19_data <- read_csv(path(here(), './data/ieeg_behave/ll19_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))





```

## Prep Behavioral Data

```{r SLCH002-data-prep}


# clean df #
sl02_data_clean <- clean_bci_data(sl02_data, 2000)

# create distance df # 
sl02_data_distance <- create_distance_df_bci(sl02_data_clean)
sl02_data_distance_no_ghost <- create_distance_df_bci(sl02_data_clean, ghost = F)

```

```{r SLCH018-data-prep}


# clean df #
sl18_data_clean <- clean_bci_data(sl18_data, 2000)

# create distance df # 
sl18_data_distance <- create_distance_df_bci(sl18_data_clean)
sl18_data_distance_no_ghost <- create_distance_df_bci(sl18_data_clean, ghost = F)

```

```{r BJH016-data-prep}


# clean df #
bjh16_data_clean <- clean_bci_data(bjh16_data, 2000)

# create distance df # 
bjh16_data_distance <- create_distance_df_bci(bjh16_data_clean)
bjh16_data_distance_no_ghost <- create_distance_df_bci(bjh16_data_clean, ghost = F)

```

```{r BJH017-data-prep}

# change from early version of bci conversion script
bjh17_data <- bjh17_data %>%
  mutate(Time = Sample) %>% # old conversion script had different variables
  select(-Sample) # remove old variable

# clean Biscuits #
bjh17_data_clean <- clean_bci_data(bjh17_data, 2000)

# create distance df # 
bjh17_data_distance <- create_distance_df_bci(bjh17_data_clean)
bjh17_data_distance_no_ghost <- create_distance_df_bci(bjh17_data_clean, ghost = F)

```

```{r BJH021-data-prep}


# clean df #
bjh21_data_clean <- clean_bci_data(bjh21_data, 2000)

# create distance df # 
bjh21_data_distance <- create_distance_df_bci(bjh21_data_clean)
bjh21_data_distance_no_ghost <- create_distance_df_bci(bjh21_data_clean, ghost = F)

# summary df
bjh21_data_summary <- get_across_task_variables_bci(bjh21_data_clean)

```

```{r BJH025-data-prep}

## Prep #
# Subject paused to get out of dying and that resulted in an incorrect trial count
bjh25_data <- bjh25_data %>%
  mutate(Trial = as.numeric(Trial)) %>%
  filter(Trial != 7) %>%
  mutate(Trial = if_else(Trial < 7, Trial, Trial -1)) %>%
  mutate(Trial = as.character(Trial))

# clean df #
bjh25_data_clean <- clean_bci_data(bjh25_data, 2000)

# create distance df # 
bjh25_data_distance <- create_distance_df_bci(bjh25_data_clean)
bjh25_data_distance_no_ghost <- create_distance_df_bci(bjh25_data_clean, ghost = F)


```

```{r BJH026-data-prep}


# clean df #
bjh26_data_clean <- clean_bci_data(bjh26_data, 2000)

# create distance df # 
bjh26_data_distance <- create_distance_df_bci(bjh26_data_clean)
bjh26_data_distance_no_ghost <- create_distance_df_bci(bjh26_data_clean, ghost = F)

```

```{r BJH027-data-prep}


# clean df #
bjh27_data_clean <- clean_bci_data(bjh27_data, 2000)

# create distance df # 
bjh27_data_distance <- create_distance_df_bci(bjh27_data_clean)
bjh27_data_distance_no_ghost <- create_distance_df_bci(bjh27_data_clean, ghost = F)

```

```{r BJH029-data-prep}


# clean df #
bjh29_data_clean <- clean_bci_data(bjh29_data, 2000)

# create distance df # 
bjh29_data_distance <- create_distance_df_bci(bjh29_data_clean)
bjh29_data_distance_no_ghost <- create_distance_df_bci(bjh29_data_clean, ghost = F)

```

```{r BJH039-data-prep}


# clean df #
bjh39_data_clean <- clean_bci_data(bjh39_data, 2000)

# create distance df # 
bjh39_data_distance <- create_distance_df_bci(bjh39_data_clean)
bjh39_data_distance_no_ghost <- create_distance_df_bci(bjh39_data_clean, ghost = F)

```

```{r BJH041-data-prep}


# clean df #
bjh41_data_clean <- clean_bci_data(bjh41_data, 2000)

# create distance df # 
bjh41_data_distance <- create_distance_df_bci(bjh41_data_clean)
bjh41_data_distance_no_ghost <- create_distance_df_bci(bjh41_data_clean, ghost = F)

```

```{r BJH046-data-prep}


# clean df #
bjh46_data_clean <- clean_bci_data(bjh46_data, 2000)

# create distance df # 
bjh46_data_distance <- create_distance_df_bci(bjh46_data_clean)
bjh46_data_distance_no_ghost <- create_distance_df_bci(bjh46_data_clean, ghost = F)

```

```{r BJH050-data-prep}


# clean df #
bjh50_data_clean <- clean_bci_data(bjh50_data, 2000)

# create distance df # 
bjh50_data_distance <- create_distance_df_bci(bjh50_data_clean)
bjh50_data_distance_no_ghost <- create_distance_df_bci(bjh50_data_clean, ghost = F)

```

```{r BJH051-data-prep}


# clean df #
bjh51_data_clean <- clean_bci_data(bjh51_data, 2000)

# create distance df # 
bjh51_data_distance <- create_distance_df_bci(bjh51_data_clean)
bjh51_data_distance_no_ghost <- create_distance_df_bci(bjh51_data_clean, ghost = F)

```

```{r ll10-data-prep}


# clean df #
ll10_data_clean <- clean_bci_data(ll10_data, 512)

# create distance df # 
ll10_data_distance <- create_distance_df_bci(ll10_data_clean)
ll10_data_distance_no_ghost <- create_distance_df_bci(ll10_data_clean, ghost = F)

```

```{r ll12-data-prep}


# clean df #
ll12_data_clean <- clean_bci_data(ll12_data, 512)

# create distance df # 
ll12_data_distance <- create_distance_df_bci(ll12_data_clean)
ll12_data_distance_no_ghost <- create_distance_df_bci(ll12_data_clean, ghost = F)

```

```{r ll13-data-prep}


# clean df #
ll13_data_clean <- clean_bci_data(ll13_data, 512)

# create distance df # 
ll13_data_distance <- create_distance_df_bci(ll13_data_clean)
ll13_data_distance_no_ghost <- create_distance_df_bci(ll13_data_clean, ghost = F)

```

```{r ll14-data-prep}


# clean df #
# incorrect new trial
ll14_data <- ll14_data %>%
  mutate(Trial = as.numeric(Trial)) %>%
  mutate(Trial = if_else(Trial < 82, Trial, Trial -1)) %>%
  filter(Trial != 121) %>%
  mutate(Trial = if_else(Trial < 121, Trial, Trial -1)) %>%
  mutate(Trial = if_else(Trial < 338, Trial, Trial + 3)) %>% # player pressed n to start whole new game/ refreshed or something but new block begins
  mutate(Trial = if_else(Trial < 731, Trial, Trial + 9)) %>% # player pressed n to start whole new game/ refreshed or something but new block begins
  mutate(Trial = as.character(Trial))

# if we start a new block at trial 338 does it fix it?


# clean Biscuits #
ll14_data_clean <- clean_bci_data(ll14_data, 512)

# create distance df # 
ll14_data_distance <- create_distance_df_bci(ll14_data_clean)
ll14_data_distance_no_ghost <- create_distance_df_bci(ll14_data_clean, ghost = F)

```

```{r ll17-data-prep}


# clean df #
# incorrect new trial
ll17_data <- ll17_data %>%
  mutate(Trial = as.numeric(Trial)) %>%
  filter(Trial != 82) %>%
  mutate(Trial = if_else(Trial < 82, Trial, Trial -1)) %>%
  mutate(Trial = as.character(Trial))

# if we start a new block at trial 338 does it fix it?


# clean Biscuits #
ll17_data_clean <- clean_bci_data(ll17_data, 512)

# create distance df # 
ll17_data_distance <- create_distance_df_bci(ll17_data_clean)
ll17_data_distance_no_ghost <- create_distance_df_bci(ll17_data_clean, ghost = F)

```

```{r ll19-data-prep}


# clean df #
ll19_data_clean <- clean_bci_data(ll19_data, 512)

# create distance df # 
ll19_data_distance <- create_distance_df_bci(ll19_data_clean)
ll19_data_distance_no_ghost <- create_distance_df_bci(ll19_data_clean, ghost = F)

```

## All subjects behavior data

```{r all_subs_behavior}

all_subs_data_clean <- rbind(sl02_data_clean, sl18_data_clean, bjh16_data_clean, bjh17_data_clean,
                             bjh21_data_clean, bjh25_data_clean, bjh26_data_clean, bjh27_data_clean, bjh29_data_clean,
                             bjh39_data_clean,  bjh41_data_clean, bjh46_data_clean, bjh50_data_clean, bjh51_data_clean,
                             ll10_data_clean, ll12_data_clean, ll13_data_clean, 
                             ll14_data_clean, ll17_data_clean, ll19_data_clean)

all_subs_dist_data_clean <- rbind(sl02_data_distance, sl18_data_distance, bjh16_data_distance, bjh17_data_distance, 
                                  bjh21_data_distance, bjh26_data_distance, bjh27_data_distance, bjh29_data_distance,
                                  bjh39_data_distance,  bjh41_data_distance, bjh46_data_distance, bjh50_data_distance, bjh51_data_distance,
                                  bjh25_data_distance, ll10_data_distance, ll12_data_distance, ll13_data_distance,
                                  ll14_data_distance, ll17_data_distance, ll19_data_distance)

all_subs_dist_ng_data_clean <- rbind(sl02_data_distance_no_ghost, sl18_data_distance_no_ghost, bjh16_data_distance_no_ghost, bjh17_data_distance_no_ghost, 
                                  bjh21_data_distance_no_ghost, bjh26_data_distance_no_ghost, bjh27_data_distance_no_ghost, bjh29_data_distance_no_ghost,
                                  bjh39_data_distance_no_ghost,  bjh41_data_distance_no_ghost, bjh46_data_distance_no_ghost, bjh50_data_distance_no_ghost, bjh51_data_distance_no_ghost,
                                  bjh25_data_distance_no_ghost, ll10_data_distance_no_ghost, ll12_data_distance_no_ghost, ll13_data_distance_no_ghost,
                                ll14_data_distance_no_ghost, ll17_data_distance_no_ghost, ll19_data_distance_no_ghost)

write_csv(all_subs_data_clean, path(here(), "munge", "all_subs_complete_behavior_df.csv"))
write_csv(all_subs_dist_data_clean, path(here(), "munge", "all_subs_complete_distance_df.csv"))
write_csv(all_subs_dist_ng_data_clean, path(here(), "munge", "all_subs_noghost_complete_distance_df.csv"))

```
