---
title: "Death Issues"
output: html_document
date: "2024-04-23"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(ggeffects)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lmerTest)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)



```


# Identify best way to classify death trials

## Load Raw Data

```{r SLCH002-data-load}

sl02_data <- read_csv(path(here(), './data/ieeg_behave/SLCH002_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


bjh16_data <- read_csv(path(here(), './data/ieeg_behave/BJH016_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh21_data <- read_csv(path(here(), './data/ieeg_behave/BJH021_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh25_data <- read_csv(path(here(), './data/ieeg_behave/BJH025_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh26_data <- read_csv(path(here(), './data/ieeg_behave/BJH026_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh27_data <- read_csv(path(here(), './data/ieeg_behave/BJH027_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh29_data <- read_csv(path(here(), './data/ieeg_behave/BJH029_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh39_data <- read_csv(path(here(), './data/ieeg_behave/BJH039_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh41_data <- read_csv(path(here(), './data/ieeg_behave/BJH041_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


ll10_data <- read_csv(path(here(), './data/ieeg_behave/ll10_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll12_data <- read_csv(path(here(), './data/ieeg_behave/ll12_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll13_data <- read_csv(path(here(), './data/ieeg_behave/ll13_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll14_data <- read_csv(path(here(), './data/ieeg_behave/ll14_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll17_data <- read_csv(path(here(), './data/ieeg_behave/ll17_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll19_data <- read_csv(path(here(), './data/ieeg_behave/ll19_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))





```

```{r}

sample_rate <- 2000

# bjh25_data <- bjh25_data %>%
#   mutate(Trial = as.numeric(Trial)) %>%
#   filter(Trial != 7) %>%
#   mutate(Trial = if_else(Trial < 7, Trial, Trial -1)) %>%
#   mutate(Trial = as.character(Trial))

# ll14_data <- ll14_data %>%
#   mutate(Trial = as.numeric(Trial)) %>%
#   mutate(Trial = if_else(Trial < 82, Trial, Trial -1)) %>%
#   filter(Trial != 121) %>%
#   mutate(Trial = if_else(Trial < 121, Trial, Trial -1)) %>%
#   mutate(Trial = if_else(Trial < 338, Trial, Trial + 3)) %>% # player pressed n to start whole new game/ refreshed or something but new block begins
#   mutate(Trial = if_else(Trial < 731, Trial, Trial + 9)) %>% # player pressed n to start whole new game/ refreshed or something but new block begins
#   mutate(Trial = as.character(Trial))

# ll17_data <- ll17_data %>%
#   mutate(Trial = as.numeric(Trial)) %>%
#   filter(Trial != 82) %>%
#   mutate(Trial = if_else(Trial < 82, Trial, Trial -1)) %>%
#   mutate(Trial = as.character(Trial))


clean_data <- sl02_data %>%
    select(-any_of(c("...1", "X1"))) %>%
    rename(subject = Subject) %>%
    # ungrouped timing variables
    rename(sample = Time) %>%
    mutate(Time = sample /sample_rate) %>%
    mutate(time_step = c(FALSE, diff(Time))) %>%
    mutate(trial_numeric = as.numeric(gsub("Trial_", "", Trial))) %>%
    # record sampling rate #
    mutate(sfreq = sample_rate) %>%
    ## grouped by trial variables
    group_by(subject, Trial) %>%
    mutate(jittered_start_location = first(UserLocation)) %>%
    # get correct trial type info (sometimes trial type switches early/ lags)
    mutate(TrialType = as.numeric(names(sort(table(TrialType),decreasing=TRUE))[1])) %>%
    # # same deal with lives
    mutate(Lives = as.numeric(names(sort(table(Lives),decreasing=TRUE))[1])) %>%
    mutate(base_start_location = if_else(TrialType %in% c(16, 8), 30,
                                         if_else(TrialType %in% c(19, 15, 14, 7, 6), 50,
                                                 if_else(TrialType %in% c(20, 13, 5), 70,
                                                         if_else(TrialType %in% c(17, 12, 4), 110,
                                                                 if_else(TrialType %in% c(18, 11, 10, 3, 2), 130,
                                                                         if_else(TrialType %in% c(9, 1), 150, 999))))))) %>%
    # biscuit location
    mutate(Biscuit1 = if_else(Biscuit1 == FALSE & base_start_location <= 80,  base_start_location + 12, 
                              if_else(Biscuit1 == FALSE & base_start_location > 80, base_start_location -12, 1111)))  %>%
    mutate(Biscuit2 = if_else(Biscuit2 == FALSE & base_start_location <= 80,  base_start_location + 22, 
                              if_else(Biscuit2 == FALSE & base_start_location > 80, base_start_location -22, 1111)))  %>%
    mutate(Biscuit3 = if_else(Biscuit3 == FALSE & base_start_location <= 80,  base_start_location + 32, 
                              if_else(Biscuit3 == FALSE & base_start_location > 80, base_start_location -32, 1111)))  %>%
    mutate(Biscuit4 = if_else(Biscuit4 == FALSE & base_start_location <= 80,  base_start_location + 42, 
                              if_else(Biscuit4 == FALSE & base_start_location > 80, base_start_location -42, 1111)))  %>%
    mutate(Biscuit5 = if_else(Biscuit5 == FALSE & base_start_location <= 80,  base_start_location + 52, 
                              if_else(Biscuit5 == FALSE & base_start_location > 80, base_start_location -52, 1111)))  %>%
    mutate(dots_eaten = max(Eaten)) %>%
    # Fix Direction
    mutate(move_step = c(0, diff(UserLocation))) %>%
    mutate(move_direction = if_else(move_step %in% c(-2, -4), "Left",
                                        if_else(move_step %in% c(2, 4), "Right", 
                                                if_else(move_step == 0, "Still", "Unsure")))) %>%
    mutate(Direction = if_else(Direction == 2, "Left", 
                                if_else(Direction == 11, "Right", 
                                        if_else(Direction == 4, "Still", "Unsure")))) %>%
    # get starting side
    mutate(starting_side = if_else(base_start_location < 95, "Left", "Right")) %>%
    # trial timing information
    mutate(Trial = if_else(Trial_on_off == 0, "ITI", Trial)) %>%
    mutate_cond(Trial == "ITI", 
                GhostLocation = NA, UserLocation = NA, Lives = NA, starting_side = NA, Direction = NA,
                Biscuit1 = NA, Biscuit2 = NA, Biscuit3 = NA, Biscuit4 = NA, Biscuit5 = NA, 
                Attack = NA, Chase = NA, Eaten = NA, TrialType = NA) %>%
    mutate(trial_time = if_else(Trial == "ITI", 999, Time - first(Time))) %>%
    mutate(trial_flip = 1:n()) %>%
    mutate(time_lag = c(FALSE, diff(trial_time))) %>%
    mutate(trial_end = as.numeric(c(diff(trial_numeric) > 0, FALSE))) %>%
    mutate(trial_length = max(trial_time)) %>%
    # trial grouping variables
    mutate(reward_groups = if_else(TrialType %in% c(1, 5, 9, 13, 20), 2, 
                                   if_else(TrialType %in% c(2, 6, 10, 14, 19), 3, 
                                           if_else(TrialType %in% c(3, 7, 11, 15, 18), 1, 
                                                   if_else(TrialType %in% c(4, 8, 12, 16, 17), 4, 99))))) %>%
    mutate(ghost_start_dir = if_else(TrialType > 16, "no_ghost", 
                                     if_else(TrialType <= 4 | TrialType >= 13, "away", "towards"))) %>%
    mutate(rewards_direction_groups = paste0(reward_groups, "_", ghost_start_dir)) %>%
    mutate(attack_chase_bob = if_else(Attack == T, "Attack", if_else(Chase == T, "Chase", "Bob"))) %>%
    ungroup() 
  


```


```{r}


# bad_df <- read_csv(path(here(), './data/ieeg_behave/SLCH002_bad_trials.csv'))
# 
# clean_data <- clean_data %>%
#   mutate(neural_trial_numeric = trial_numeric - 1) %>%
#   filter(!neural_trial_numeric %in% bad_df$neural_trial_numeric)

clean_flip_data <- clean_data %>%
  filter(Trial != "ITI") %>%
  group_by(subject, trial_numeric) %>%
  mutate(ghost_objective_direction_tmp = c(FALSE, diff(GhostLocation))) %>%
  mutate(
      ghost_objective_direction_tmp = ifelse(trial_flip == 1, 0, ghost_objective_direction_tmp),
      move_step = ifelse(trial_flip == 1, 0, move_step),
      jump = ifelse(ghost_objective_direction_tmp > 10 | ghost_objective_direction_tmp < -10 | move_step > 10 | move_step < -10, 1, 0),
      jump_trial = max(jump),
      jump_flip = ifelse(jump == 1, trial_flip, 9999),
      jump_flip = min(jump_flip),
      jump_flip = ifelse(jump_flip == 9999, NA, jump_flip),
      total_flips = max(trial_flip),
      disc = (total_flips - jump_flip),
      jump_location = ifelse(jump_flip < 5, "low",
               ifelse(jump_flip > 5 & jump_flip < 9999, "high", NA)),
      remove = jump,
      remove = ifelse(jump_location == "low", rev(cummax(rev(remove))), cummax(remove)),
      remove = ifelse(jump_location == "low" & trial_flip == jump_flip, 0, remove) # don’t want to remove first jump flip for low location
      ) %>%
      filter(remove == 0 | is.na(remove)) %>%
  mutate(
      first_flip = min(trial_flip),
      trial_flip = (trial_flip - first_flip + 1),
      max_flip = max(trial_flip),
      ghost_objective_direction_tmp = ifelse(trial_flip == 1, 0, ghost_objective_direction_tmp),
      move_step = ifelse(trial_flip == 1, 0, move_step))


```



```{r}

death_df <- clean_flip_data %>%
  mutate(died_new = 2) %>%
  filter(Trial != "ITI" & Trial != "0") %>%
  group_by(subject) %>%
  arrange(trial_numeric) %>%
  mutate(
  life_lost = as.numeric(c(diff(Lives) < 0, FALSE)), #does not catch trials where lives = 1 and dies, then lives back to 3
  score_lost_all = as.numeric(c(diff(Score) < 0, FALSE))
  ) %>%
  ungroup() %>%
  group_by(trial_numeric) %>%
  mutate(
    # calculate if they lost a life across trials. If so, they always died
    life_lost_trial = max(life_lost, na.rm = T),
    # prep score change. if the score did not change from the beginning to the end of the trial BUT they collected points, they always died (this avoids the block updating issue)
    first_score = first(Score),
    last_score = last(Score),
    got_dots = if_else(dots_eaten > 0, 1, 0),
    points_added = last_score - first_score,
    score_died = if_else(got_dots == 1 & points_added == 0, 1, 0),
    score_died_trial = max(score_died, na.rm = T),
    # look at the ITI - if it was under 3.15 then they did not die, because it was not long enough for the death animation
    first_time = first(Time),
    last_time = last(Time)
  ) %>%
  ungroup() %>%
  mutate(next_first_time = lead(first_time, order_by = trial_numeric)) %>%
  mutate(iti_time_tmp = next_first_time - last_time, na.rm = T) %>%
  group_by(trial_numeric) %>%
  mutate(
    iti_time = max(iti_time_tmp, na.rm = T),
    # were they very close to the ghost at the end of the trial?
    ghost_catch = if_else(is.na(GhostLocation), 0,
                         if_else(abs(last(GhostLocation) - last(UserLocation)) <= 10, 1, 0)), # change to last moment of trial rather than any moment
    ghost_catch_trial = max(ghost_catch),
    # did they exit the corridor?
    corridor_exit = ifelse(UserLocation <= 11 | UserLocation >= 169, 1, 0),
    corridor_exit_expanded = ifelse(UserLocation < 13 | UserLocation > 165, 1, 0),
    exit_trial = max(corridor_exit, na.rm = T),
    exit_trial_expanded = max(corridor_exit_expanded, na.rm = T),
    # create types by whether or not they exited the corridor and/or were close the ghost
    escaped_trialtypes = case_when(
      ghost_catch_trial == 0 & exit_trial == 1 ~ 4, # true escape
      ghost_catch_trial == 0 & exit_trial == 0 ~ 3, # not caught but not left?
      ghost_catch_trial == 1 & exit_trial == 1 ~ 2, # close escape (caught and left)
      ghost_catch_trial == 1 & exit_trial == 0 ~ 1  # true death
      ),
    # defining death - clear cases
    died_new = if_else(life_lost_trial == 1, 1, died_new), # using 0, 1, 2 to check later, 2 = death
    died_new = if_else(escaped_trialtypes == 1, 1, died_new),
    died_new = if_else(escaped_trialtypes == 4, 0, died_new),
    # defining death - complicated
    died_new = if_else(escaped_trialtypes == 2 & score_died_trial == 1, 1, died_new),
    died_new = if_else(escaped_trialtypes == 2 & iti_time < 3, 0, died_new),
    died_new = if_else(escaped_trialtypes == 3 & iti_time < 3, 0, died_new),
    # still unsure?
    died_new = if_else(died_new == 2 & last(Attack) == T, 1, died_new),
    died_new = if_else(died_new == 2 & (last(UserLocation) >= 25 & last(UserLocation) <= 155), 1, died_new),
    died_new = if_else(died_new == 2 & last(Chase) == T, 0, died_new),
    # last
    died_new = if_else(TrialType >16, 0, died_new)
  ) %>%
  ungroup() %>%
  # rename(died_old = died) %>%
  arrange(subject, trial_numeric)
  

table(death_df$escaped_trialtypes, death_df$died_new)



```


```{r}

# should NOT include positions at the ends of the corridor
true_death_df <- death_df %>% 
  filter(escaped_trialtypes == 1) %>% ## true death
  group_by(trial_numeric) %>%
  mutate(last_position = last(UserLocation)) 
kable(table(true_death_df$last_position, true_death_df$died_new), caption = "died_new")

# should ONLY include positions at the ends of the corridor
true_escape_df <- death_df %>% 
  filter(escaped_trialtypes == 4) %>% ## true escape
  group_by(trial_numeric) %>%
  mutate(last_position = if_else(starting_side == "Left", min(UserLocation), max(UserLocation))) 
kable(table(true_escape_df$last_position, true_escape_df$died_new), caption = "died_new")

# Check a couple of things -position, score, iti
close_escape_df <- death_df %>% 
  filter(escaped_trialtypes == 2 & TrialType <= 16) %>% ## true death
  group_by(trial_numeric) %>%
  mutate(last_position = if_else(starting_side == "Left", min(UserLocation), max(UserLocation))) 
kable(table(close_escape_df$last_position, close_escape_df$died_new), caption = "died_new")
kable(table(close_escape_df$score_died_trial, close_escape_df$died_new), caption = "died_new")
kable(table(close_escape_df$iti_time, close_escape_df$died_new), caption = "died_new")

# Check a couple of things -position, score, iti
neither_df <- death_df %>% 
  filter(escaped_trialtypes == 3 & TrialType <= 16) %>% ## true death
  group_by(trial_numeric) %>%
  mutate(last_position = if_else(starting_side == "Left", min(UserLocation), max(UserLocation))) 
kable(table(neither_df$last_position, neither_df$died_new), caption = "died_new")
kable(table(neither_df$score_died_trial, neither_df$died_new), caption = "died_new")
kable(table(neither_df$iti_time, neither_df$died_new), caption = "died_new")


```


## New Score

```{r}
cumsum_na_ignore <- function(x) {
  # Replace NA with 0 temporarily for cumsum calculation
  cumsum_values <- cumsum(replace(x, is.na(x), 0))
  
  # Put NA back where they originally were
  cumsum_values[is.na(x)] <- NA
  
  return(cumsum_values)
}


 clean_flip_death_data <- left_join(clean_flip_data, death_df %>% rename(died = died_new))

score_check <- clean_flip_death_data %>%
    mutate(points_remaining = case_when(
                                      # Reward Group 1
                                      reward_groups == 1 & Biscuit5 == 1111 ~ 70 - 10 - 20 -20 -10 - 10, #  small	large	large	small	small, total 70
                                      reward_groups == 1 & Biscuit4 == 1111 ~ 70 - 10 - 20 -20 - 10,
                                      reward_groups == 1 & Biscuit3 == 1111 ~ 70 - 10 - 20 - 20,
                                      reward_groups == 1 & Biscuit2 == 1111 ~ 70 - 10 - 20, 
                                      reward_groups == 1 & Biscuit1 == 1111 ~ 70 - 10, 
                                      reward_groups == 1 ~ 70,
                                      # Reward Group 2
                                      reward_groups == 2 & Biscuit5 == 1111 ~ 70 - 10 -20 -10 -20 -10, #  small	large	small	large	small, total 70
                                      reward_groups == 2 & Biscuit4 == 1111 ~ 70 - 10 -20 -10 -20,
                                      reward_groups == 2 & Biscuit3 == 1111 ~ 70 - 10 -20 -10, 
                                      reward_groups == 2 & Biscuit2 == 1111 ~ 70 - 10 -20,
                                      reward_groups == 2 & Biscuit1 == 1111 ~ 70 - 10, 
                                      reward_groups == 2 ~ 70, 
                                      # Reward Group 3
                                      reward_groups == 3 & Biscuit5 == 1111 ~ 80 - 20 - 10 - 20 - 10 - 20, #  large	small	large	small	large, total 80
                                      reward_groups == 3 & Biscuit4 == 1111 ~ 80 - 20 - 10 - 20 - 10, 
                                      reward_groups == 3 & Biscuit3 == 1111 ~ 80 - 20 - 10 - 20, 
                                      reward_groups == 3 & Biscuit2 == 1111 ~ 80 - 20 - 10,
                                      reward_groups == 3 & Biscuit1 == 1111 ~ 80 - 20,
                                      reward_groups == 3 ~ 80,
                                      # Reward Group 4
                                      reward_groups == 4 & Biscuit5 == 1111 ~ 70 - 10 - 10 - 10 - 20 - 20, #  small	small	small	large	large, total 70
                                      reward_groups == 4 & Biscuit4 == 1111 ~ 70 - 10 - 10 - 10 - 20,
                                      reward_groups == 4 & Biscuit3 == 1111 ~ 70 - 10 - 10 - 10,
                                      reward_groups == 4 & Biscuit2 == 1111 ~ 70 - 10 - 10,
                                      reward_groups == 4 & Biscuit1 == 1111 ~ 70 - 10,
                                      reward_groups == 4 ~ 70,
                                      )) %>%
    mutate(points_aquired = if_else(reward_groups == 3, 80 - points_remaining, 70 - points_remaining)) %>%
    group_by(Trial) %>%
    mutate(total_trial_points = last(points_aquired)) %>%
    select(Trial, trial_numeric, starts_with("Biscuit"), Eaten, Score, points_aquired, points_remaining, total_trial_points, died) %>%
    ungroup()

score_tmp <- score_check %>%
  filter(Trial != "ITI") %>%
  select(trial_numeric, total_trial_points, died) %>%
  distinct() %>%
  mutate(block = ceiling(trial_numeric/20) ) %>%
  group_by(block) %>%
  mutate(
    game_number = floor(cumsum(died)/3),
    game_number = c(0, game_number[1:n()-1]),
    lives_at_end_of_trial_tmp = 3 - (cumsum(died) %% 3),
    lives_at_end_of_trial = if_else(lives_at_end_of_trial_tmp == 3 & died == 1, 0, lives_at_end_of_trial_tmp),
    lives_new = if_else(died == 0, lives_at_end_of_trial, lives_at_end_of_trial + 1)
  ) %>%
  group_by(block, game_number) %>%
  mutate(
    total_trial_points = if_else(died == 1, 0,  total_trial_points),
    points_from_last_trial = lag(total_trial_points, default = 0),
    points_up_to_last_trial = cumsum(points_from_last_trial),
    # points_up_to_last_trial = if_else(lives_at_end_of_trial == 0, 0, points_up_to_last_trial),
    score_at_trial_end = points_up_to_last_trial + total_trial_points
    ) %>%
  select(trial_numeric, points_up_to_last_trial, score_at_trial_end, lives_new, game_number)
  

score_check <- left_join(score_check , score_tmp)

score_check <- score_check %>%
  mutate(new_score = points_aquired + points_up_to_last_trial)

```


```{r fig.width = 12, fig.height = 6}



tmp <- sl02_data_clean %>%
  mutate(tmp1 = Score-old_score) 


score_table_check <- as.data.frame(table(tmp$trial_numeric, tmp$tmp1))

score_table_check <- score_table_check %>%
  rename(trial_numeric = Var1, difference = Var2) %>%
  filter(difference != 0) %>%
  group_by(trial_numeric) %>%
  mutate(total_differences = sum(Freq)) %>%
  select(trial_numeric, total_differences) %>%
  distinct()
           

table(sl02_data_clean$died)

```

