---
title: "Bayesian Assessment of HFA Correlations And Time to Turnaround"
output: html_document
date: "2024-10-14"
---

```{r setup, include=FALSE}
## libraries ##
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(lmtest)
library(scales)
library(ggthemr)
library(brms)
library(bayesplot)
library(RColorBrewer)
library(broom.mixed)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))
source(path(here(), "R", 'compile_ieeg_csv_files.R'))
source(path(here(), "R", 'run_and_plot_lme_models.R'))
source(path(here(), "R", "bayesian_helpers.R"))

## plotting helpers ##
ggthemr("light")
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

```




```{r load-data}


# load correlations #
correlation_df <- read_csv(path(here(), "results", "hfa_correlations_newsubs.csv"))

```


```{r split-mfg-sfg}

regions_df <- read_csv(path(here(), "munge", "mni_coordinates_all_subs_with_detailed_regions.csv"))

mfg_df <- regions_df %>%
  filter(region == "mfg") %>%
  mutate(elec_id = paste0(subject, "_", Electrode))

sfg_df <- regions_df %>%
  filter(region == "sfg") %>%
  mutate(elec_id = paste0(subject, "_", Electrode))

correlation_detailed_df <- correlation_df %>%
  rowwise() %>%
  mutate(
    first_pair = gsub(paste0(subject, "_"), "", elec1),
    second_pair = gsub(paste0(subject, "_"), "", elec2),
    first_pair_1 = gsub("-.*", "", first_pair),
    first_pair_2 = gsub(".*-", "", first_pair),
    second_pair_1 = gsub("-.*", "", second_pair),
    second_pair_2 = gsub(".*-", "", second_pair),
  ) %>%
  ungroup() %>%
  mutate(
    detailed_first_region = if_else(
        first_region == "dlpfc" &
        paste0(subject, "_", first_pair_1) %in% mfg_df$elec_id |
        paste0(subject, "_", first_pair_2) %in%  mfg_df$elec_id,
      "mfg",
      if_else(
          first_region == "dlpfc" &
          paste0(subject, "_", first_pair_1) %in% sfg_df$elec_id |
          paste0(subject, "_", first_pair_2) %in%  sfg_df$elec_id,
      "sfg",
      first_region
      )),
    detailed_second_region = if_else(
          second_region == "dlpfc" &
          paste0(subject, "_", second_pair_1) %in% mfg_df$elec_id |
          paste0(subject, "_", second_pair_2) %in%  mfg_df$elec_id,
      "mfg",
      if_else(
          second_region == "dlpfc" &
          paste0(subject, "_", second_pair_1) %in% sfg_df$elec_id |
          paste0(subject, "_", second_pair_2) %in%  sfg_df$elec_id,
      "sfg",
      second_region
      )
     )
    )


## Check that everything worked correctly
table(correlation_detailed_df$detailed_first_region)
table(correlation_detailed_df$detailed_second_region)

# final rename
correlation_detailed_df <- correlation_detailed_df %>%
  mutate(first_region = detailed_first_region, 
         second_region = detailed_second_region) %>%
  select(-detailed_first_region, -detailed_second_region)

# fix pair id to fit with sig pairs
correlation_df <- correlation_detailed_df %>%
  rowwise() %>%
  mutate(roi_pair1 = paste0(subject, gsub(subject, "", elec1), "_to", gsub(subject, "", elec2)),
         roi_pair2 = paste0(subject, gsub(subject, "", elec2), "_to", gsub(subject, "", elec1))) %>%
  ungroup()


```

### Original Sig Theta Pairs Version

```{r only-sig-elecs}

# load sig pairs by coherence analysis #
sig_pairs <- read_csv(path(here(), "results", "sig_theta_pairs.csv"))

sig_pairs <- sig_pairs %>%
  mutate(pair_id = paste0(subject, "_", pairs)) %>%
  filter(metric == "Imaginary Coherence")

# filter ofc_turnDf to sig pairs
correlation_sig_df <- correlation_df %>%
  filter(first_region != "sfg" & second_region != "sfg") %>%
  filter(first_region != second_region) %>%
  filter( (roi_pair1 %in% sig_pairs$pair_id) | (roi_pair2 %in% sig_pairs$pair_id) ) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  mutate(scale_correlation = scale(correlation)[,1]) %>%
  mutate(scale_logged_times = scale(logged_times)[,1]) %>%
  ungroup() %>%
  mutate(regions = paste(first_region, second_region, sep = "_")) %>%
  filter(!grepl("insula", regions)) %>%
  mutate(
    region_pair = case_when(
      grepl("ofc", regions) & grepl("hc", regions) ~ "ofc_hc",
      grepl("ofc", regions) & grepl("amyg", regions) ~ "ofc_amyg",
      grepl("ofc", regions) & grepl("mfg", regions) ~ "ofc_mfg",
      grepl("ofc", regions) & grepl("cing", regions) ~ "ofc_cing",
      grepl("hc", regions) & grepl("amyg", regions) ~ "hc_amyg",
      grepl("hc", regions) & grepl("mfg", regions) ~ "hc_mfg",
      grepl("hc", regions) & grepl("cing", regions) ~ "hc_cing",
      grepl("amyg", regions) & grepl("mfg", regions) ~ "amyg_mfg",
      grepl("amyg", regions) & grepl("cing", regions) ~ "amyg_cing",
      grepl("mfg", regions) & grepl("cing", regions) ~ "mfg_cing"
    ))


```


```{r distribution-shapes}

correlation_sig_df %>%
  ggplot(., aes(x = scale_logged_times)) +
  geom_histogram() +
  theme(panel.background = element_rect(fill = "white"))


correlation_sig_df %>%
  ggplot(., aes(x = scale_correlation)) +
  geom_histogram() +
  theme(panel.background = element_rect(fill = "white"))


table(correlation_sig_df$region_pair)



```
Maybe increase hfa iter on the next run!

```{r}


# Set the number of cores for parallel processing
options(mc.cores = parallel::detectCores())

# set the priors #
priors <- c(
  prior(normal(0, 5), class = "Intercept"),            # Prior for the intercept
  prior(normal(0, 2), class = "b"),                    # Prior for fixed effects
  prior(exponential(1), class = "sd"),                 # Prior for random effects standard deviations
  prior(lkj(2), class = "cor")                         # Prior for random effects correlations
)


# Fit the model
model <- brm(
  formula = scale_correlation ~ scale_logged_times * region_pair + (1 + scale_logged_times | subject/roi_pair1),
  data = correlation_sig_df,
  prior = priors,
  family = gaussian(),
  iter = 5000, 
  warmup = 2000,
  chains = 4,
  control = list(adapt_delta = 0.99),
  seed = 1234
)

# save full model #
save(model, file = path(here(), "results", "full_hfa_all_roi_model_brms_newsubs.RData"))

# load full model #
load(path(here(), "results", "full_hfa_all_roi_model_brms_newsubs.RData"))

```


```{r model-summary}

# summary #
summary(model)

 

```


```{r trace-plot, fig.height = 50, fig.width = 8}

# plot #
mcmc_trace(model, regex_pars = c("b_"), facet_args = list(ncol = 1))


```


```{r}

# Combine posteriors into CIs for each region 
slopes_summary_df <- get_region_effects_for_turnaround_models(model,unique(correlation_sig_df$region_pair))


# save output
write_csv(slopes_summary_df, path(here(), "results", "turn_time_prediction", "hfa_all_roi_orig_elecs_slopes_summary.csv"))



```


### All Electrode Pairs Version

```{r only-sig-elecs}

# filter ofc_turnDf to sig pairs
correlation_clean_df <- correlation_df %>%
  filter(first_region != second_region) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  mutate(scale_correlation = scale(correlation)[,1]) %>%
  mutate(scale_logged_times = scale(logged_times)[,1]) %>%
  ungroup() %>%
  mutate(regions = paste(first_region, second_region, sep = "_")) %>%
  filter(!grepl("insula", regions)) %>%
  filter(!grepl("sfg", regions)) %>%
  mutate(
    region_pair = case_when(
      grepl("ofc", regions) & grepl("hc", regions) ~ "ofc_hc",
      grepl("ofc", regions) & grepl("amyg", regions) ~ "ofc_amyg",
      grepl("ofc", regions) & grepl("mfg", regions) ~ "ofc_mfg",
      grepl("ofc", regions) & grepl("cing", regions) ~ "ofc_cing",
      grepl("hc", regions) & grepl("amyg", regions) ~ "hc_amyg",
      grepl("hc", regions) & grepl("mfg", regions) ~ "hc_mfg",
      grepl("hc", regions) & grepl("cing", regions) ~ "hc_cing",
      grepl("amyg", regions) & grepl("mfg", regions) ~ "amyg_mfg",
      grepl("amyg", regions) & grepl("cing", regions) ~ "amyg_cing",
      grepl("mfg", regions) & grepl("cing", regions) ~ "mfg_cing"
    ))


```


```{r}


# Set the number of cores for parallel processing
options(mc.cores = parallel::detectCores())

# set the priors #
priors <- c(
  prior(normal(0, 5), class = "Intercept"),            # Prior for the intercept
  prior(normal(0, 2), class = "b"),                    # Prior for fixed effects
  prior(exponential(1), class = "sd"),                 # Prior for random effects standard deviations
  prior(lkj(2), class = "cor")                         # Prior for random effects correlations
)


# Fit the model
hfa_all_elec_model <- brm(
  formula = scale_correlation ~ scale_logged_times * region_pair + (1 + scale_logged_times | subject/roi_pair1),
  data = correlation_clean_df,
  prior = priors,
  family = gaussian(),
  iter = 5000, 
  warmup = 2000,
  chains = 4,
  control = list(adapt_delta = 0.99),
  seed = 1234
)

# save full model #
save(hfa_all_elec_model, file = path(here(), "results", "full_hfa_all_roi_all_elecs_model_brms.RData"))

# load full model #
load(path(here(), "results", "full_hfa_all_roi_all_elecs_model_brms.RData"))

```


```{r model-summary}

# summary #
summary(hfa_all_elec_model)

```


```{r trace-plot, fig.height = 50, fig.width = 8}

# plot #
mcmc_trace(hfa_all_elec_model, regex_pars = c("b_"), facet_args = list(ncol = 1))


```


```{r}

# Combine posteriors into CIs for each region 
slopes_summary_df <- get_region_effects_for_turnaround_models(hfa_all_elec_model,unique(correlation_clean_df$region_pair))


# save output
write_csv(slopes_summary_df, path(here(), "results", "turn_time_prediction", "hfa_all_roi_all_elecs_slopes_summary.csv"))



```


### Smaller Subset of Electrodes Option

```{r only-sig-elecs}

## load threshold csv ##
sig_thresh_df <- read_csv(path(here(), "results", "sig_theta_threshold_pairs.csv"))

# separate subject lists
sub_elec_lists <- sig_thresh_df %>%
  # get rid of unused regions
  filter(!grepl("sfg", roi_pair)) %>%
  filter(!grepl("insula", roi_pair)) %>%
  filter(roi_pair != "mfg_mfg") %>%
  mutate(pair_id = paste0(subject, "_", pairs)) %>%
  mutate(sig = "True") %>%
  select(pair_id, roi_pair, threshold, sig) 

sig_50_list <- sub_elec_lists %>% filter(threshold == 50) %>% distinct()

# filter ofc_turnDf to sig pairs
correlation_clean_df <- correlation_df %>%
  filter(first_region != second_region) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  filter( (roi_pair1 %in% sig_50_list$pair_id) | (roi_pair2 %in% sig_50_list$pair_id) ) %>%
  mutate(scale_correlation = scale(correlation)[,1]) %>%
  mutate(scale_logged_times = scale(logged_times)[,1]) %>%
  ungroup() %>%
  mutate(regions = paste(first_region, second_region, sep = "_")) %>%
  filter(!grepl("insula", regions)) %>%
  filter(!grepl("sfg", regions)) %>%
  mutate(
    region_pair = case_when(
      grepl("ofc", regions) & grepl("hc", regions) ~ "ofc_hc",
      grepl("ofc", regions) & grepl("amyg", regions) ~ "ofc_amyg",
      grepl("ofc", regions) & grepl("mfg", regions) ~ "ofc_mfg",
      grepl("ofc", regions) & grepl("cing", regions) ~ "ofc_cing",
      grepl("hc", regions) & grepl("amyg", regions) ~ "hc_amyg",
      grepl("hc", regions) & grepl("mfg", regions) ~ "hc_mfg",
      grepl("hc", regions) & grepl("cing", regions) ~ "hc_cing",
      grepl("amyg", regions) & grepl("mfg", regions) ~ "amyg_mfg",
      grepl("amyg", regions) & grepl("cing", regions) ~ "amyg_cing",
      grepl("mfg", regions) & grepl("cing", regions) ~ "mfg_cing"
    ))


```


```{r}


# Set the number of cores for parallel processing
options(mc.cores = parallel::detectCores())

# set the priors #
priors <- c(
  prior(normal(0, 5), class = "Intercept"),            # Prior for the intercept
  prior(normal(0, 2), class = "b"),                    # Prior for fixed effects
  prior(exponential(1), class = "sd"),                 # Prior for random effects standard deviations
  prior(lkj(2), class = "cor")                         # Prior for random effects correlations
)


# Fit the model
hfa_100_elec_model <- brm(
  formula = scale_correlation ~ scale_logged_times * region_pair + (1 + scale_logged_times | subject/roi_pair1),
  data = correlation_clean_df,
  prior = priors,
  family = gaussian(),
  iter = 5000, 
  warmup = 2000,
  chains = 4,
  control = list(adapt_delta = 0.99),
  seed = 1234
)

# save full model #
save(hfa_100_elec_model, file = path(here(), "results", "full_hfa_all_roi_100_elecs_model_brms.RData"))

# load full model #
load(path(here(), "results", "full_hfa_all_roi_100_elecs_model_brms.RData"))

```


```{r model-summary}

# summary #
summary(hfa_100_elec_model)

```


```{r trace-plot, fig.height = 50, fig.width = 8}

# plot #
mcmc_trace(hfa_100_elec_model, regex_pars = c("b_"), facet_args = list(ncol = 1))


```


```{r}

# Combine posteriors into CIs for each region 
slopes_summary_df <- get_region_effects_for_turnaround_models(hfa_100_elec_model,unique(correlation_clean_df$region_pair))

# save output
write_csv(slopes_summary_df, path(here(), "results", "turn_time_prediction", "hfa_all_roi_100_elecs_slopes_summary.csv"))

```

```

