---
title: "OFC ~ Amygdala Power Predictions"
output: html_document
date: "2024-03-28"
---

```{r setup, include=FALSE}
## libraries ##
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(lmtest)
library(scales)
library(ggthemr)
library(RColorBrewer)
library(broom.mixed)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))
source(path(here(), "R", 'compile_ieeg_csv_files.R'))
source(path(here(), "R", 'run_and_plot_lme_models.R'))

## plotting helpers ##
ggthemr("light")
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

```

```{r load-data}

ofc_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_ofc_all_subs_logged_iti_onset.csv"))
amyg_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_amyg_all_subs_logged_iti_onset.csv"))

# behavioral data #
all_subs_g_dist <- read_csv(path(here(), "munge", "all_subs_complete_distance_df.csv"))
all_subs_ng_dist <- read_csv(path(here(), "munge", "all_subs_noghost_complete_distance_df.csv"))

# combine ghost and no ghost #
all_subs_dist <- all_subs_g_dist %>% 
  select(-GhostLocation, -distance_to_ghost, -min_distance, -cdf_distance)
all_subs_dist <- rbind(all_subs_dist, all_subs_ng_dist)

all_subs_g_dist <- all_subs_g_dist %>%
  filter(attack_chase_bob == "Bob") 



```

## SLCH002


```{r prep-data-SLCH002}

# merge behavior data with ieeg data
ofc_behave_df <- left_join(all_subs_g_dist %>% select(-move_step) %>% mutate(trial_time = round(trial_time, 2)), 
                             ofc_theta_data %>% rename(ofc_theta = theta) %>% mutate(trial_time = round(trial_time, 2)), by = join_by(subject, trial_numeric, trial_time))

amyg_behave_df <- left_join(all_subs_g_dist %>%  select(-move_step) %>% mutate(trial_time = round(trial_time, 2)), 
                             amyg_theta_data %>% rename(amyg_theta = theta) %>% mutate(trial_time = round(trial_time, 2)), by = join_by(subject, trial_numeric, trial_time))


ofc_onset_lme_df <- ofc_behave_df %>%
    # round time so that we can loop over time later
    mutate(trial_time = round(trial_time, 2)) %>%
    # exclude time before they started moving, may be good to look at not doing this as well
    filter(Direction != "Still") %>%
    # filiter out ITI
    filter(reward_groups != 99 & !is.na(electrode)) %>%
    # prep electrode variables
    mutate(elec_id = paste0(subject, "_", gsub("_.*", "", electrode))) %>%
    mutate(electrode = gsub("_.*", "", electrode)) %>%
    # shift the time so that time 0 is the start of movement onset
    group_by(elec_id, trial_numeric, subject) %>%
    mutate(move_time = round(trial_time - first(trial_time), 2)) %>%
    # filter time so that trials end when the person turnaround for the final time
    mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
    mutate(event = replace(event, is.na(event), 0)) %>%
    mutate(turnaround_time = if_else(event == 1, move_time, 0)) %>%
    filter(move_time < max(turnaround_time)) %>%
    ungroup() %>%
    group_by(move_time) %>%
    ungroup() %>%
    select(subject, elec_id, ofc_theta, trial_numeric, move_time) %>%
    distinct()


amyg_onset_lme_df <- amyg_behave_df %>%
    # round time so that we can loop over time later
    mutate(trial_time = round(trial_time, 2)) %>%
    # exclude time before they started moving, may be good to look at not doing this as well
    filter(Direction != "Still") %>%
    # filiter out ITI
    filter(reward_groups != 99 & !is.na(electrode)) %>%
    # prep electrode variables
    mutate(elec_id = paste0(subject, "_", gsub("_.*", "", electrode))) %>%
    mutate(electrode = gsub("_.*", "", electrode)) %>%
    # shift the time so that time 0 is the start of movement onset
    group_by(elec_id, trial_numeric, subject) %>%
    mutate(move_time = round(trial_time - first(trial_time), 2)) %>%
    # filter time so that trials end when the person turnaround for the final time
    mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
    mutate(event = replace(event, is.na(event), 0)) %>%
    mutate(turnaround_time = if_else(event == 1, move_time, 0)) %>%
    filter(move_time < max(turnaround_time)) %>%
    ungroup() %>%
    select(subject, elec_id, amyg_theta, trial_numeric, move_time) %>%
    distinct()



turn_time_df <- ofc_onset_lme_df %>%
  select(subject, trial_numeric, move_time) %>%
  distinct() %>%
  group_by(subject, trial_numeric) %>%
  mutate(turn_time = last(move_time)) %>%
  select(trial_numeric, turn_time) %>%
  distinct() %>%
  rename(trial = trial_numeric)

```



```{r ofc-turn-time, fig.width = 10, fig.height= 5}

ofc_summary_lme_df <- ofc_onset_lme_df %>%
  group_by(subject, elec_id, trial_numeric) %>%
  mutate(mean_theta = mean(ofc_theta)) %>%
  select(-ofc_theta, -move_time) %>%
  distinct()

ofc_summary_lme_df %>%
  ggplot(., aes(x = subject, y = mean_theta)) +
  geom_boxplot(notch = T) +
  theme(panel.background = element_rect(fill = "white"))
```

```{r BJH027, fig.width = 10, fig.height = 8}

# filter to single subject #
ofc_subject_lme_df <- ofc_summary_lme_df %>%
  filter(subject == "BJH027") %>%
  rename(trial = trial_numeric) 

# merge with turn data #
ofc_sub_turn_df <- left_join(ofc_subject_lme_df, turn_time_df, by = c("subject", "trial"))

# clean #
ofc_sub_turn_df <- ofc_sub_turn_df %>%
  mutate(log_times = log(turn_time)) %>%
  filter(!is.infinite(log_times)) 

sub_model <- lmer(mean_theta ~ log_times + (1|elec_id), data = ofc_sub_turn_df)

summary(sub_model)


ofc_sub_turn_df %>%
  ggplot(., aes(x = mean_theta, y = log_times)) +
  geom_point() +
  geom_smooth(method = "lm", formula = 'y~x', color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~elec_id)


for(elec in unique(ofc_sub_turn_df$elec_id)) {
  
  elec_df <- ofc_sub_turn_df %>%
    filter(elec_id == elec)
  
  elec_model <- lm(log_times ~ mean_theta, data = elec_df)
  
  print(summary(elec_model))
  
}

```

```{r ofc-turn-time, fig.width = 10, fig.height= 5}

amyg_summary_lme_df <- amyg_onset_lme_df %>%
  group_by(subject, elec_id, trial_numeric) %>%
  mutate(mean_theta = mean(amyg_theta)) %>%
  select(-amyg_theta, -move_time) %>%
  distinct()

amyg_summary_lme_df %>%
  ggplot(., aes(x = subject, y = mean_theta)) +
  geom_boxplot(notch = T) +
  theme(panel.background = element_rect(fill = "white"))


```

```{r BJH027-amyg, fig.width = 10, fig.height = 8}

# filter to single subject #
amyg_subject_lme_df <- amyg_summary_lme_df %>%
  filter(subject == "BJH027") %>%
  rename(trial = trial_numeric) 

# merge with turn data #
amyg_sub_turn_df <- left_join(amyg_subject_lme_df, turn_time_df, by = c("subject", "trial"))

# clean #
amyg_sub_turn_df <- amyg_sub_turn_df %>%
  mutate(log_times = log(turn_time)) %>%
  filter(!is.infinite(log_times)) 

sub_model <- lmer(mean_theta ~ log_times + (1|elec_id), data = amyg_sub_turn_df)

summary(sub_model)


amyg_sub_turn_df %>%
  ggplot(., aes(x = mean_theta, y = log_times)) +
  geom_point() +
  geom_smooth(method = "lm", formula = 'y~x', color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~elec_id)


for(elec in unique(amyg_sub_turn_df$elec_id)) {
  
  elec_df <- amyg_sub_turn_df %>%
    filter(elec_id == elec)
  
  elec_model <- lm(log_times ~ mean_theta, data = elec_df)
  
  print(summary(elec_model))
  
}

```

```{r permutation-test}

estimates_perm <- NULL
permutations <- 1:1000
for(perm in permutations){
  
  amyg_perm_turn_df <- amyg_sub_turn_df %>%
    group_by(elec_id) %>%
    mutate(permuted_times = sample(log_times)) %>%
    ungroup()
  
  perm_model <- tidy(lme4::lmer(mean_theta ~ permuted_times + (1|elec_id), data = amyg_perm_turn_df))
  
  estimates_tmp <- perm_model %>%
    filter(term == "permuted_times") %>%
    pull(estimate)
  
  estimates_perm <- c(estimates_perm, estimates_tmp)
  
  
}

true_model <- tidy(lme4::lmer(mean_theta ~ log_times + (1|elec_id), data = amyg_sub_turn_df))

estimates_true <- true_model %>%
  filter(term == "log_times") %>%
  pull(estimate)

print(true_model)


print(table(estimates_perm >= estimates_true))

```

```{r}

# load correlation data #
ofc_amyg_results <- read_csv(path(here(), "results", "turn_time_prediction", "amyg_ofc_theta_turn_time_correlations.csv"))

# filter to sub #
ofc_amyg_sub_results <- ofc_amyg_results %>% filter(subject == "BJH027")


table(ofc_amyg_sub_results$pair_id)

```

```{r}

reg_df <- ofc_amyg_sub_results %>%
  mutate(logged_times = log(turn_time)) %>%  
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times))


corr_model <- lmer(correlation ~ logged_times + (1|pair_id), data = reg_df)
summary(corr_model)



```


```{r, fig.width = 20, fig.height = 40}

correl_power_df <- left_join(reg_df, amyg_sub_turn_df %>% select(subject, trial, mean_theta, elec_id) %>% rename(amyg_elec = elec_id, amyg_theta = mean_theta), by = join_by(trial, subject, amyg_elec))
correl_power_df <- left_join(correl_power_df, ofc_sub_turn_df %>% select(subject, trial, mean_theta, elec_id) %>% rename(ofc_elec = elec_id, ofc_theta = mean_theta), by = join_by(trial, subject, ofc_elec))

corr_power_model <- lmer(correlation ~ logged_times + amyg_theta + (1|pair_id), data = correl_power_df)
summary(corr_power_model)



reg_df %>%
  ggplot(., aes(x = correlation, y = logged_times))  +
  geom_point() +
  geom_smooth(method = "lm", formula = 'y~x', color = "black", fill = "lightgrey") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~pair_id)


```


