---
title: "Theta Turn Correlation Plots"
output: html_document
date: "2024-10-14"
---

```{r setup, include=FALSE}
## libraries ##
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(lmtest)
library(scales)
library(ggthemr)
library(brms)
library(RColorBrewer)
library(broom.mixed)
library(gt)
library(bayestestR)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))
source(path(here(), "R", 'compile_ieeg_csv_files.R'))
source(path(here(), "R", 'run_and_plot_lme_models.R'))

## plotting helpers ##
ggthemr("light")
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

```




```{r load-data}

# load correlations #
correlation_df <- read_csv(path(here(), "results", "theta_correlations_newsubs.csv"))


```


```{r split-mfg-sfg}

regions_df <- read_csv(path(here(), "munge", "mni_coordinates_all_subs_with_detailed_regions.csv"))

mfg_df <- regions_df %>%
  filter(region == "mfg") %>%
  mutate(elec_id = paste0(subject, "_", Electrode))

sfg_df <- regions_df %>%
  filter(region == "sfg") %>%
  mutate(elec_id = paste0(subject, "_", Electrode))

correlation_detailed_df <- correlation_df %>%
  rowwise() %>%
  mutate(
    first_pair = gsub(paste0(subject, "_"), "", elec1),
    second_pair = gsub(paste0(subject, "_"), "", elec2),
    first_pair_1 = gsub("-.*", "", first_pair),
    first_pair_2 = gsub(".*-", "", first_pair),
    second_pair_1 = gsub("-.*", "", second_pair),
    second_pair_2 = gsub(".*-", "", second_pair),
  ) %>%
  ungroup() %>%
  mutate(
    detailed_first_region = if_else(
        first_region == "dlpfc" &
        paste0(subject, "_", first_pair_1) %in% mfg_df$elec_id |
        paste0(subject, "_", first_pair_2) %in%  mfg_df$elec_id,
      "mfg",
      if_else(
          first_region == "dlpfc" &
          paste0(subject, "_", first_pair_1) %in% sfg_df$elec_id |
          paste0(subject, "_", first_pair_2) %in%  sfg_df$elec_id,
      "sfg",
      first_region
      )),
    detailed_second_region = if_else(
          second_region == "dlpfc" &
          paste0(subject, "_", second_pair_1) %in% mfg_df$elec_id |
          paste0(subject, "_", second_pair_2) %in%  mfg_df$elec_id,
      "mfg",
      if_else(
          second_region == "dlpfc" &
          paste0(subject, "_", second_pair_1) %in% sfg_df$elec_id |
          paste0(subject, "_", second_pair_2) %in%  sfg_df$elec_id,
      "sfg",
      second_region
      )
     )
    )


## Check that everything worked correctly
table(correlation_detailed_df$detailed_first_region)
table(correlation_detailed_df$detailed_second_region)

# final rename
correlation_detailed_df <- correlation_detailed_df %>%
  mutate(first_region = detailed_first_region, 
         second_region = detailed_second_region) %>%
  select(-detailed_first_region, -detailed_second_region)

# fix pair id to fit with sig pairs
correlation_df <- correlation_detailed_df %>%
  rowwise() %>%
  mutate(roi_pair1 = paste0(subject, gsub(subject, "", elec1), "_to", gsub(subject, "", elec2)),
         roi_pair2 = paste0(subject, gsub(subject, "", elec2), "_to", gsub(subject, "", elec1))) %>%
  ungroup()


```


```{r only-sig-elecs}

# load sig pairs by coherence analysis #
sig_pairs <- read_csv(path(here(), "results", "sig_theta_pairs.csv"))

sig_pairs <- sig_pairs %>%
  mutate(pair_id = paste0(subject, "_", pairs)) %>%
  filter(metric == "Imaginary Coherence")

# filter to sig pairs
correlation_sig_df <- correlation_df %>%
  filter(first_region != "sfg" & second_region != "sfg") %>%
  filter(first_region != second_region) %>%
  filter( (roi_pair1 %in% sig_pairs$pair_id) | (roi_pair2 %in% sig_pairs$pair_id) ) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  mutate(scale_correlation = scale(correlation)[,1]) %>%
  mutate(scale_logged_times = scale(logged_times)[,1]) %>%
  ungroup() %>%
  mutate(regions = paste(first_region, second_region, sep = "_")) %>%
  filter(!grepl("insula", regions)) %>%
  mutate(
    region_pair = case_when(
      grepl("ofc", regions) & grepl("hc", regions) ~ "ofc_hc",
      grepl("ofc", regions) & grepl("amyg", regions) ~ "ofc_amyg",
      grepl("ofc", regions) & grepl("mfg", regions) ~ "ofc_mfg",
      # grepl("ofc", regions) & grepl("insula", regions) ~ "ofc_insula",
      grepl("ofc", regions) & grepl("cing", regions) ~ "ofc_cing",
      grepl("hc", regions) & grepl("amyg", regions) ~ "hc_amyg",
      grepl("hc", regions) & grepl("mfg", regions) ~ "hc_mfg",
      # grepl("hc", regions) & grepl("insula", regions) ~ "hc_insula",
      grepl("hc", regions) & grepl("cing", regions) ~ "hc_cing",
      grepl("amyg", regions) & grepl("mfg", regions) ~ "amyg_mfg",
      # grepl("amyg", regions) & grepl("insula", regions) ~ "amyg_insula",
      grepl("amyg", regions) & grepl("cing", regions) ~ "amyg_cing",
      # grepl("mfg", regions) & grepl("insula", regions) ~ "mfg_insula",
      grepl("mfg", regions) & grepl("cing", regions) ~ "mfg_cing"
      # grepl("insula", regions) & grepl("cing", regions) ~ "insula_cing"
    ))


```

```{r load-model-results}

# load full model #
load(path(here(), "results", "full_all_roi_model_brms_newsubs_noinsula.RData"))


summary(model)
```


```{r}

# For each region pair
region_pairs <- unique(model$data$region_pair)

# values to find CI intervals in the density function
closest_value <- function(x, v) {
  # Calculate the absolute differences between each element in v and x
  differences <- abs(v - x)
  
  # Find the index of the minimum difference
  index_of_min <- which.min(differences)
  
  # Return the value in v at the index of the minimum difference
  closest <- v[index_of_min]
  return(closest)
}

# Function to summarize posterior samples
summarize_posterior <- function(samples) {
  mean_val <- mean(samples)
  sd_val <- sd(samples)
  ci_lower <- quantile(samples, 0.025)
  ci_upper <- quantile(samples, 0.975)
  max_density = max(density(samples)$y)
  ci_lower_dens = density(samples)$y[density(samples)$x == closest_value(ci_lower, density(samples)$x)]
  ci_upper_dens = density(samples)$y[density(samples)$x == closest_value(ci_upper, density(samples)$x)]
  prob_positive <- mean(samples > 0)
  tibble(
    Mean = mean_val,
    SD = sd_val,
    CI_Lower = ci_lower,
    CI_Upper = ci_upper,
    Max_Density = max_density,
    CI_Lower_Density = ci_lower_dens,
    CI_Upper_Density = ci_upper_dens,
    Prob_Positive = prob_positive
  )
}

# Function to extract sample for each region pair
get_samples_for_region <- function(region) {
  if (region == "amyg_cing") {
    slope <- as_draws_df(model)$b_scale_logged_times
  } else {
    interaction_term <- paste0("b_scale_logged_times:region_pair", region)
    slope <- as_draws_df(model)$b_scale_logged_times + as_draws_df(model)[[interaction_term]]
  }
}

# Function to extract slopes for each region pair
get_slope_for_region <- function(region) {
  if (region == "amyg_cing") {
    slope <- as_draws_df(model)$b_scale_logged_times
  } else {
    interaction_term <- paste0("b_scale_logged_times:region_pair", region)
    slope <- as_draws_df(model)$b_scale_logged_times + as_draws_df(model)[[interaction_term]]
  }
  summarize_posterior(slope)
}


# get all samples #
full_sample <-  lapply(region_pairs, get_samples_for_region)
names(full_sample) <- region_pairs
full_sample_df <- as_tibble(full_sample)

# Summarize slopes for all region pairs
slopes_summary <- lapply(region_pairs, get_slope_for_region)
names(slopes_summary) <- region_pairs

# Combine summaries into a data frame
slopes_summary_df <- bind_rows(slopes_summary, .id = "Region_Pair")

```

## Scatter Plots 

```{r scatter-plots, fig.width=4.5, fig.height = 8.5}

# set plot colors
example_colors <- c("#FFA602", "#88D1A3", "darkgrey")
example_fills <- c("#FFD485", "#C4E7D4", "lightgrey")

# pull electrode examples & combine
amyg_hc_df <- correlation_sig_df %>%
  filter(region_pair == "hc_amyg") %>%
  filter(roi_pair1 == "BJH041_AL2-AL3_to_CL1-CL2")

ofc_cing_df <- correlation_sig_df %>%
  filter(region_pair == "ofc_cing") %>%
  filter(roi_pair1 == "BJH046_EL1-EL2_to_IR3-IR4")

amyg_mfg_df <- correlation_sig_df %>%
  filter(region_pair == "amyg_mfg") %>%
  filter(roi_pair1 == "LL19_RA3-RA4_to_ROF11-ROF12")

example_correlation_dfs <- bind_rows(amyg_hc_df %>% mutate(case = "HC - Amyg."), 
                                     ofc_cing_df %>% mutate(case = "OFC - ACC"), 
                                     amyg_mfg_df %>% mutate(case = "Amyg. - MFG"))


# create plot
example_correlation_plot <- example_correlation_dfs %>%
  mutate(case = factor(case, levels = c("HC - Amyg.", "OFC - ACC", "Amyg. - MFG"))) %>%
  ggplot(aes(x = turn_time, y = scale_correlation, fill = case, color = case)) +
  geom_point(size = 2, shape = 21) +
  geom_smooth(method = "lm", formula = 'y ~ x', se = FALSE, color = "#2D2327") +
  labs(
    x = "Approach Time (s)",
    y = "Theta power correlation during approach (z-score)",
    title = "Example Pairs - Theta"
  ) +
    theme(panel.background = element_rect(fill = "white"), 
      legend.position = "none",
      axis.text = element_text(family = "Gill Sans", color = "#2D2327", size = 13),
      axis.title = element_text(family = "Gill Sans", color = "#2D2327", size = 13),
      legend.title = element_text(family = "Gill Sans", color = "#2D2327", size = 13),
      legend.text  = element_text(family = "Gill Sans", color = "#2D2327", size = 13),
      strip.text = element_text(family = "Gill Sans", color = "#2D2327", size = 13),
      plot.title = element_text(family = "Gill Sans", color = "#2D2327", size = 14, hjust = .75)) + 
  scale_color_manual(values = example_colors) +
  scale_fill_manual(values = example_fills) +
  facet_wrap(~case, scales = 'free_y', ncol = 1)


ggsave(path(here(), "figures", "correl_turn_predictions", "figure4_turn_time_example_plot.png"), 
       plot = example_correlation_plot, 
       width = 2.5, height = 4.5, units = "in", dpi = 300)


# write csv
write_csv(example_correlation_dfs, path(here(), "results", "turn_time_prediction", "theta_example_correlation_df.csv"))

```


## Posterior Distribution Plots


```{r prep-for-posterior-plot}

full_sample_plot_df <- full_sample_df %>%
  pivot_longer(everything(), names_to = "Region_Pair", values_to = "samples") %>%
  mutate(first_region = case_when(
    grepl("^amyg", Region_Pair) ~ "Amygdala",
    grepl("^hc", Region_Pair) ~ "Hippocampus",
    grepl("^ofc", Region_Pair) ~ "OFC",
    grepl("^cing", Region_Pair) ~ "Ant. Cingulate",
    grepl("^mfg", Region_Pair) ~ "MFG"
  )) %>%
  mutate(Region_Pair = case_when(
    Region_Pair == "amyg_cing" ~ "Amyg. ~ ACC",
    Region_Pair == "hc_amyg" ~ "HC ~ Amyg.",
    Region_Pair == "amyg_mfg" ~ "Amyg. ~ MFG",
    Region_Pair == "ofc_amyg" ~ "OFC ~ Amyg.",
    Region_Pair == "ofc_cing" ~ "OFC ~ ACC",
    Region_Pair == "ofc_hc" ~ "OFC ~ HC",
    Region_Pair == "ofc_mfg" ~ "OFC ~ MFG",
    Region_Pair == "hc_cing" ~ "HC ~ ACC",
    Region_Pair == "hc_mfg" ~ "HC ~ MFG",
    Region_Pair == "mfg_cing" ~ "MFG ~ ACC"
    
  )) %>%
  mutate(Region_Pair = factor(Region_Pair, levels = c("Amyg. ~ ACC",  "Amyg. ~ MFG", "HC ~ Amyg.", "HC ~ ACC",  "HC ~ MFG",
                                          "OFC ~ Amyg.", "OFC ~ HC", "OFC ~ ACC", "OFC ~ MFG", "MFG ~ ACC")))

pair_count <- correlation_sig_df %>%
  select(pair_id, subject, region_pair) %>%
  unique() %>%
  count(region_pair)

sub_count <- correlation_sig_df %>%
  select(pair_id, subject, region_pair) %>%
  unique() %>%
  select(-pair_id) %>%
  unique() %>%
  group_by(region_pair) %>%
  count(subject) %>%
  summarise(n = n())

slopes_summary_df <- left_join(slopes_summary_df, pair_count, by = c("Region_Pair" = "region_pair"))


slopes_summary_plot_df <- slopes_summary_df %>%
  mutate(first_region = case_when(
    grepl("^amyg", Region_Pair) ~ "Amygdala",
    grepl("^hc", Region_Pair) ~ "Hippocampus",
    grepl("^ofc", Region_Pair) ~ "OFC",
    grepl("^cing", Region_Pair) ~ "Ant. Cingulate",
    grepl("^mfg", Region_Pair) ~ "MFG"
  )) %>%
  mutate(Region_Pair = case_when(
    Region_Pair == "amyg_cing" ~ "Amyg. ~ ACC",
    Region_Pair == "hc_amyg" ~ "HC ~ Amyg.",
    Region_Pair == "amyg_mfg" ~ "Amyg. ~ MFG",
    Region_Pair == "ofc_amyg" ~ "OFC ~ Amyg.",
    Region_Pair == "ofc_cing" ~ "OFC ~ ACC",
    Region_Pair == "ofc_hc" ~ "OFC ~ HC",
    Region_Pair == "ofc_mfg" ~ "OFC ~ MFG",
    Region_Pair == "hc_cing" ~ "HC ~ ACC",
    Region_Pair == "hc_mfg" ~ "HC ~ MFG",
    Region_Pair == "mfg_cing" ~ "MFG ~ ACC"
    
  ))  %>%
  mutate(Region_Pair = factor(Region_Pair,
                              levels = c("Amyg. ~ ACC",  "Amyg. ~ MFG", "HC ~ Amyg.", "HC ~ ACC",  "HC ~ MFG",
                                          "OFC ~ Amyg.", "OFC ~ HC", "OFC ~ ACC", "OFC ~ MFG", "MFG ~ ACC"))) %>%
  mutate(sig = if_else(0 > CI_Lower & 0 < CI_Upper, 99, 44))


# merge
full_sample_summary_plot_df <- left_join(slopes_summary_plot_df, full_sample_plot_df) 

# write csv
write_csv(full_sample_summary_plot_df, path(here(), "results", "turn_time_prediction", "theta_model_results_summary_plot_df.csv"))



```


```{r prep-samples-for-plotting, fig.width. = 10, fig.height = 10}

## set colors ##
roi_colors <-  c("Amygdala" = "#DE4A4D", "Hippocampus" = "#FFA602", "OFC" =  "#88D1A3", "Ant. Cingulate"=  "#3D99BA", "Insula" =  "#876194", "MFG" = "#FB6087", "SFG" = "#FB9A99", "CI includes 0" = "darkgrey")

turn_time_plot <- full_sample_summary_plot_df %>%
  mutate(first_region_color = if_else(sig == 99, "CI includes 0", first_region)) %>%
  mutate(first_region_color = factor(first_region_color, levels = c("Amygdala", "Hippocampus", "OFC", "MFG", "CI includes 0"))) %>%
  ggplot(., aes(x = samples, color = first_region_color, fill = first_region_color)) +
  geom_vline(xintercept = 0, color = "black") +
  geom_density(alpha = .15) +
  geom_segment(aes(x = Mean, xend = Mean, y = 0, yend = Max_Density, color = first_region_color), linewidth = 1, linetype = "dotdash") +
  geom_segment(aes(x = CI_Upper, xend = CI_Upper, y = 0, yend = CI_Upper_Density, color = first_region_color),  linewidth = 1) +
  geom_segment(aes(x = CI_Lower, xend = CI_Lower, y = 0, yend = CI_Lower_Density, color = first_region_color),  linewidth = 1) +
  geom_text(aes(x = .08, y = sig), label = "*", size = 20, show.legend = FALSE, check_overlap = T) +
  facet_wrap(~Region_Pair,  nrow = 2) +
  theme(panel.background = element_rect(fill = "white"), 
      legend.position = "top",
      axis.text = element_text(family = "Gill Sans", color = "#2D2327", size = 13),
      axis.title = element_text(family = "Gill Sans", color = "#2D2327", size = 15),
      legend.title = element_text(family = "Gill Sans", color = "#2D2327", size = 16),
      legend.text  = element_text(family = "Gill Sans", color = "#2D2327", size = 15),
      strip.text = element_text(family = "Gill Sans", color = "#2D2327", size = 14),
      plot.title = element_text(family = "Gill Sans", color = "#2D2327", size = 16)) +
  labs(color = " ", fill = " ", y = "Density", x = "\nEstimated Beta Coefficient (a.u., fit using MCMC Sampling)") +
  scale_color_manual(values = roi_colors) +
  scale_fill_manual(values = roi_colors) +
  ylim(0, 60) +
  ggtitle("Posterior distributions of the estimated correlation between approach\ntimes and theta power synchrony")

turn_time_plot

ggsave(path(here(), "figures", "correl_turn_predictions", "figure4_turn_time_posterior_dist_plot.png"),
       plot = turn_time_plot,
       width = 9, height = 5, units = "in", dpi = 300)



```




