---
title: "HFA"
output: html_document
date: "2024-05-02"
---


```{r setup, include=FALSE}
## libraries ##
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(lmtest)
library(scales)
library(ggthemr)
library(RColorBrewer)
library(broom.mixed)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))
source(path(here(), "R", 'compile_ieeg_csv_files.R'))
source(path(here(), "R", 'run_and_plot_lme_models.R'))

## plotting helpers ##
ggthemr("light")
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

```


## Based on Imaginary Coherence

```{r load-data}


# load correlations #
correlation_df <- read_csv(path(here(), "results", "hfa_correlations.csv"))

```

```{r split-mfg-sfg}

regions_df <- read_csv(path(here(), "munge", "mni_coordinates_all_subs_with_detailed_regions.csv"))

mfg_df <- regions_df %>%
  filter(region == "mfg") %>%
  mutate(elec_id = paste0(subject, "_", Electrode))

sfg_df <- regions_df %>%
  filter(region == "sfg") %>%
  mutate(elec_id = paste0(subject, "_", Electrode))

correlation_detailed_df <- correlation_df %>%
  rowwise() %>%
  mutate(
    first_pair = gsub(paste0(subject, "_"), "", elec1),
    second_pair = gsub(paste0(subject, "_"), "", elec2),
    first_pair_1 = gsub("-.*", "", first_pair),
    first_pair_2 = gsub(".*-", "", first_pair),
    second_pair_1 = gsub("-.*", "", second_pair),
    second_pair_2 = gsub(".*-", "", second_pair),
  ) %>%
  ungroup() %>%
  mutate(
    detailed_first_region = if_else(
        first_region == "mfg" &
        paste0(subject, "_", first_pair_1) %in% mfg_df$elec_id |
        paste0(subject, "_", first_pair_2) %in%  mfg_df$elec_id,
      "mfg",
      if_else(
          first_region == "mfg" &
          paste0(subject, "_", first_pair_1) %in% sfg_df$elec_id |
          paste0(subject, "_", first_pair_2) %in%  sfg_df$elec_id,
      "sfg",
      first_region
      )),
    detailed_second_region = if_else(
          second_region == "mfg" &
          paste0(subject, "_", second_pair_1) %in% mfg_df$elec_id |
          paste0(subject, "_", second_pair_2) %in%  mfg_df$elec_id,
      "mfg",
      if_else(
          second_region == "mfg" &
          paste0(subject, "_", second_pair_1) %in% sfg_df$elec_id |
          paste0(subject, "_", second_pair_2) %in%  sfg_df$elec_id,
      "sfg",
      second_region
      )
     )
    )


## Check that everything worked correctly
table(correlation_detailed_df$detailed_first_region)
table(correlation_detailed_df$detailed_second_region)

# final rename
correlation_detailed_df <- correlation_detailed_df %>%
  mutate(first_region = detailed_first_region, 
         second_region = detailed_second_region) %>%
  select(-detailed_first_region, -detailed_second_region)

# fix pair id to fit with sig pairs
correlation_df <- correlation_detailed_df %>%
  rowwise() %>%
  mutate(roi_pair1 = paste0(subject, gsub(subject, "", elec1), "_to", gsub(subject, "", elec2)),
         roi_pair2 = paste0(subject, gsub(subject, "", elec2), "_to", gsub(subject, "", elec1))) %>%
  ungroup()


```

```{r only-sig-pairs}

# load sig pairs by coherence analysis #
sig_pairs <- read_csv(path(here(), "results", "sig_theta_pairs.csv"))

sig_pairs <- sig_pairs %>%
  mutate(pair_id = paste0(subject, "_", pairs)) %>%
  filter(metric == "Imaginary Coherence")

# filter ofc_turnDf to sig pairs
correlation_sig_df <- correlation_df %>%
  filter( (roi_pair1 %in% sig_pairs$pair_id) | (roi_pair2 %in% sig_pairs$pair_id) ) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  mutate(scale_correlation = scale(correlation)) %>%
  ungroup() 


correlation_nsig_df <- correlation_df %>%
  filter( (!roi_pair1 %in% sig_pairs$pair_id) & (!roi_pair2 %in% sig_pairs$pair_id) ) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  mutate(scale_correlation = scale(correlation)) %>%
  ungroup() 



```




```{r distribution-shapes}

correlation_sig_df %>%
  ggplot(., aes(x = logged_times)) +
  geom_histogram() +
  theme(panel.background = element_rect(fill = "white"))

correlation_sig_df %>%
  ggplot(., aes(x = correlation)) +
  geom_histogram() +
  theme(panel.background = element_rect(fill = "white"))


correlation_sig_df %>%
  ggplot(., aes(x = scale_correlation)) +
  geom_histogram() +
  theme(panel.background = element_rect(fill = "white"))

```



## OFC 

```{r, fig.width = 12, fig.height = 8}

control <- lme4::lmerControl(optCtrl = list(maxfun = 1e5, tolPwrss = 1e-4))
start_values <- list(theta = c(0.1, .1))

# OFC ~ HC, sig #
ofc_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "hc"),  control = control, start = start_values)
summary(ofc_hc_model)
bayestestR::ci(ofc_hc_model)

# OFC ~ Insula, sig #
ofc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "insula"),  control = control, start = start_values)
summary(ofc_insula_model)
bayestestR::ci(ofc_insula_model)

# OFC ~ dlPFC,  sig #
ofc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "mfg"),  control = control, start = start_values)
summary(ofc_mfg_model)
bayestestR::ci(ofc_mfg_model)

# OFC ~ Ant. Cingulate, not sig #
ofc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "cing"),  control = control, start = start_values)
summary(ofc_cing_model)
bayestestR::ci(ofc_cing_model)

# OFC ~ Amygdala, not sig #
ofc_amyg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "amyg"),  control = control, start = start_values)
summary(ofc_amyg_model)
bayestestR::ci(ofc_amyg_model)

```


## Amygdala 

```{r, fig.width = 12, fig.height = 8}

# Amygdala ~ HC, sig #
amyg_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "hc"),  control = control, start = start_values)
summary(amyg_hc_model)
bayestestR::ci(amyg_hc_model)

# Amygdala ~ Insula, not sig #
amyg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "insula"),  control = control, start = start_values)
summary(amyg_insula_model)
bayestestR::ci(amyg_insula_model)

# Amygdala ~ dlPFC, not sig #
amyg_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "mfg"),  control = control, start = start_values)
summary(amyg_mfg_model)
bayestestR::ci(amyg_mfg_model)

# Amygdala ~ Ant. Cing, not sig #
amyg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "cing"),  control = control, start = start_values)
summary(amyg_cing_model)
bayestestR::ci(amyg_cing_model)

# Amygdala ~ OFC, not sig #
ofc_amyg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "amyg"),  control = control, start = start_values)
summary(ofc_amyg_model)
bayestestR::ci(ofc_amyg_model)


```


## HC 

```{r, fig.width = 12, fig.height = 8}

# OFC ~ HC, sig #
ofc_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "hc"),  control = control, start = start_values)
summary(ofc_hc_model)
bayestestR::ci(ofc_hc_model)

# HC ~ Insula, not sig #
hc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "insula"),  control = control, start = start_values)
summary(hc_insula_model)
bayestestR::ci(hc_insula_model)

# HC ~ dlPFC, not sig #
hc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "mfg"),  control = control, start = start_values)
summary(hc_mfg_model)
bayestestR::ci(hc_mfg_model)

# HC ~ Cing, not sig #
hc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "cing"),  control = control, start = start_values)
summary(hc_cing_model)
bayestestR::ci(hc_cing_model)

# Amygdala ~ HC, sig #
amyg_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "hc"),  control = control, start = start_values)
summary(amyg_hc_model)
bayestestR::ci(amyg_hc_model)


```


## Insula 

```{r, fig.width = 12, fig.height = 8}

# OFC ~ Insula, sig #
ofc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "insula"),  control = control, start = start_values)
summary(ofc_insula_model)
# parameters::p_value(ofc_insula_model)
# parameters::ci(ofc_insula_model, method = "boot")
bayestestR::ci(ofc_insula_model)

# HC ~ Insula, not sig #
hc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "insula"),  control = control, start = start_values)
summary(hc_insula_model)
bayestestR::ci(hc_insula_model)

# dlPFC ~ Insula, sig #
mfg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "mfg" & second_region == "insula"),  control = control, start = start_values)
summary(mfg_insula_model)
bayestestR::ci(mfg_insula_model)

# Ant. Cing ~ Insula,  not sig #
cing_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "insula"),  control = control, start = start_values)
summary(cing_insula_model)
bayestestR::ci(cing_insula_model)

# Amygdala ~ Insula #
amyg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "insula"),  control = control, start = start_values)
summary(amyg_insula_model)
bayestestR::ci(amyg_insula_model)

```


## Cing 

```{r, fig.width = 12, fig.height = 8}


# OFC ~ Cing, not sig #
ofc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "cing"),  control = control, start = start_values)
summary(ofc_cing_model)
bayestestR::ci(ofc_cing_model)

# HC ~ Cing, not sig #
hc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "cing"),  control = control, start = start_values)
summary(hc_cing_model)
bayestestR::ci(hc_cing_model)

# dlPFC ~ Cing, sig #
mfg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "mfg"),  control = control, start = start_values)
summary(mfg_cing_model)
bayestestR::ci(mfg_cing_model)

# Ant. Cing ~ Insula,  not sig #
cing_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "insula"),  control = control, start = start_values)
summary(cing_insula_model)
bayestestR::ci(cing_insula_model)

# Amygdala ~ Cing, not sig #
amyg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "cing"),  control = control, start = start_values)
summary(amyg_cing_model)
bayestestR::ci(amyg_cing_model)

```


## mfg 

```{r, fig.width = 12, fig.height = 8}


# dlPFC ~ Insula, sig #
mfg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "mfg" & second_region == "insula"),  control = control, start = start_values)
summary(mfg_insula_model)
bayestestR::ci(mfg_insula_model)

# HC ~ dlPFC, not sig #
hc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "mfg"),  control = control, start = start_values)
summary(hc_mfg_model)
bayestestR::ci(hc_mfg_model)

# dlPFC ~ Cing, sig #
mfg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "mfg"),  control = control, start = start_values)
summary(mfg_cing_model)
bayestestR::ci(mfg_cing_model)

# OFC ~ dlPFC,  sig #
ofc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "mfg"),  control = control, start = start_values)
summary(ofc_mfg_model)
bayestestR::ci(ofc_mfg_model)

# Amygdala ~ dlPFC, not sig #
amyg_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "mfg"),  control = control, start = start_values)
summary(amyg_mfg_model)
bayestestR::ci(amyg_mfg_model)


```



## Based on Pairwise Phase Consistency

```{r load-data}


# load correlations #
correlation_df <- read_csv(path(here(), "results", "hfa_correlations.csv"))

# fix pair id to fit with sig pairs
correlation_df <- correlation_df %>%
  rowwise() %>%
  mutate(roi_pair1 = paste0(subject, gsub(subject, "", elec1), "_to", gsub(subject, "", elec2)),
         roi_pair2 = paste0(subject, gsub(subject, "", elec2), "_to", gsub(subject, "", elec1))) %>%
  ungroup()


# load sig pairs by coherence analysis #
sig_pairs <- read_csv(path(here(), "results", "sig_theta_pairs.csv"))

sig_pairs <- sig_pairs %>%
  mutate(pair_id = paste0(subject, "_", pairs)) %>%
  filter(metric == "Pairwise Phase Consistency")

# filter ofc_turnDf to sig pairs
correlation_sig_df <- correlation_df %>%
  filter( (roi_pair1 %in% sig_pairs$pair_id) | (roi_pair2 %in% sig_pairs$pair_id) ) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  mutate(scale_correlation = scale(correlation)) %>%
  ungroup() 


correlation_nsig_df <- correlation_df %>%
  filter( (!roi_pair1 %in% sig_pairs$pair_id) & (!roi_pair2 %in% sig_pairs$pair_id) ) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  mutate(scale_correlation = scale(correlation)) %>%
  ungroup() 



```




## OFC 

```{r, fig.width = 12, fig.height = 8}

control <- lme4::lmerControl(optCtrl = list(maxfun = 1e5, tolPwrss = 1e-4))
start_values <- list(theta = c(0.1, .1))

# OFC ~ HC, sig, nsig #
ofc_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "hc"),  control = control, start = start_values)
summary(ofc_hc_model)
bayestestR::ci(ofc_hc_model)

# OFC ~ Insula, sig, sig #
ofc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "insula"),  control = control, start = start_values)
summary(ofc_insula_model)
bayestestR::ci(ofc_insula_model)

# OFC ~ dlPFC,  sig, sig #
ofc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "mfg"),  control = control, start = start_values)
summary(ofc_mfg_model)
bayestestR::ci(ofc_mfg_model)

# OFC ~ Ant. Cingulate, not sig, sig#
ofc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "cing"),  control = control, start = start_values)
summary(ofc_cing_model)
bayestestR::ci(ofc_cing_model)

# OFC ~ Amygdala, not sig, not sig #
ofc_amyg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "amyg"),  control = control, start = start_values)
summary(ofc_amyg_model)
bayestestR::ci(ofc_amyg_model)

```


## Amygdala 

```{r, fig.width = 12, fig.height = 8}

# Amygdala ~ HC, sig, not sig #
amyg_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "hc"),  control = control, start = start_values)
summary(amyg_hc_model)
bayestestR::ci(amyg_hc_model)

# Amygdala ~ Insula, not sig, not sig #
amyg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "insula"),  control = control, start = start_values)
summary(amyg_insula_model)
bayestestR::ci(amyg_insula_model)

# Amygdala ~ dlPFC, not sig, sig,  #
amyg_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "mfg"),  control = control, start = start_values)
summary(amyg_mfg_model)
bayestestR::ci(amyg_mfg_model)

# Amygdala ~ Ant. Cing, not sig, not sig, #
amyg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "cing"),  control = control, start = start_values)
summary(amyg_cing_model)
bayestestR::ci(amyg_cing_model)

# Amygdala ~ OFC, not sig, not sig #
ofc_amyg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "amyg"),  control = control, start = start_values)
summary(ofc_amyg_model)
bayestestR::ci(ofc_amyg_model)


```


## HC 

```{r, fig.width = 12, fig.height = 8}

# OFC ~ HC, sig, not sig #
ofc_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "hc"),  control = control, start = start_values)
summary(ofc_hc_model)
bayestestR::ci(ofc_hc_model)

# HC ~ Insula, not sig, not sig #
hc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "insula"),  control = control, start = start_values)
summary(hc_insula_model)
bayestestR::ci(hc_insula_model)

# HC ~ dlPFC, not sig, not sig #
hc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "mfg"),  control = control, start = start_values)
summary(hc_mfg_model)
bayestestR::ci(hc_mfg_model)

# HC ~ Cing, not sig, not sig #
hc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "cing"),  control = control, start = start_values)
summary(hc_cing_model)
bayestestR::ci(hc_cing_model)

# Amygdala ~ HC, sig, not sig #
amyg_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "hc"),  control = control, start = start_values)
summary(amyg_hc_model)
bayestestR::ci(amyg_hc_model)


```


## Insula 

```{r, fig.width = 12, fig.height = 8}

# OFC ~ Insula, sig, sig #
ofc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "insula"),  control = control, start = start_values)
summary(ofc_insula_model)
# parameters::p_value(ofc_insula_model)
# parameters::ci(ofc_insula_model, method = "boot")
bayestestR::ci(ofc_insula_model)

# HC ~ Insula, not sig, not sig #
hc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "insula"),  control = control, start = start_values)
summary(hc_insula_model)
bayestestR::ci(hc_insula_model)

# dlPFC ~ Insula, sig, sig #
mfg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "mfg" & second_region == "insula"),  control = control, start = start_values)
summary(mfg_insula_model)
bayestestR::ci(mfg_insula_model)

# Ant. Cing ~ Insula,  not sig, not sig #
cing_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "insula"),  control = control, start = start_values)
summary(cing_insula_model)
bayestestR::ci(cing_insula_model)

# Amygdala ~ Insula, not sig, not sig #
amyg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "insula"),  control = control, start = start_values)
summary(amyg_insula_model)
bayestestR::ci(amyg_insula_model)

```


## Cing 

```{r, fig.width = 12, fig.height = 8}


# OFC ~ Cing, not sig, sig #
ofc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "cing"),  control = control, start = start_values)
summary(ofc_cing_model)
bayestestR::ci(ofc_cing_model)

# HC ~ Cing, not sig, not sig #
hc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "cing"),  control = control, start = start_values)
summary(hc_cing_model)
bayestestR::ci(hc_cing_model)

# dlPFC ~ Cing, sig, sig #
mfg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "mfg"),  control = control, start = start_values)
summary(mfg_cing_model)
bayestestR::ci(mfg_cing_model)

# Ant. Cing ~ Insula,  not sig, not sig #
cing_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "insula"),  control = control, start = start_values)
summary(cing_insula_model)
bayestestR::ci(cing_insula_model)

# Amygdala ~ Cing, not sig, not sig #
amyg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "cing"),  control = control, start = start_values)
summary(amyg_cing_model)
bayestestR::ci(amyg_cing_model)

```


## mfg 

```{r, fig.width = 12, fig.height = 8}


# dlPFC ~ Insula, sig, sig #
mfg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "mfg" & second_region == "insula"),  control = control, start = start_values)
summary(mfg_insula_model)
bayestestR::ci(mfg_insula_model)

# HC ~ dlPFC, not sig, not sig #
hc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "mfg"),  control = control, start = start_values)
summary(hc_mfg_model)
bayestestR::ci(hc_mfg_model)

# dlPFC ~ Cing, sig, sig #
mfg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "mfg"),  control = control, start = start_values)
summary(mfg_cing_model)
bayestestR::ci(mfg_cing_model)

# OFC ~ dlPFC,  sig, sig #
ofc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "mfg"),  control = control, start = start_values)
summary(ofc_mfg_model)
bayestestR::ci(ofc_mfg_model)

# Amygdala ~ dlPFC, not sig, didn't converge #
amyg_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "mfg"),  control = control, start = start_values)
summary(amyg_mfg_model)
bayestestR::ci(amyg_mfg_model)


```



## Based on Phase Locking Index

```{r load-data}


# load correlations #
correlation_df <- read_csv(path(here(), "results", "hfa_correlations.csv"))

# fix pair id to fit with sig pairs
correlation_df <- correlation_df %>%
  rowwise() %>%
  mutate(roi_pair1 = paste0(subject, gsub(subject, "", elec1), "_to", gsub(subject, "", elec2)),
         roi_pair2 = paste0(subject, gsub(subject, "", elec2), "_to", gsub(subject, "", elec1))) %>%
  ungroup()


# load sig pairs by coherence analysis #
sig_pairs <- read_csv(path(here(), "results", "sig_theta_pairs.csv"))

sig_pairs <- sig_pairs %>%
  mutate(pair_id = paste0(subject, "_", pairs)) %>%
  filter(metric == "Phase Lag Index")

# filter ofc_turnDf to sig pairs
correlation_sig_df <- correlation_df %>%
  filter( (roi_pair1 %in% sig_pairs$pair_id) | (roi_pair2 %in% sig_pairs$pair_id) ) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  mutate(scale_correlation = scale(correlation)) %>%
  ungroup() 


correlation_nsig_df <- correlation_df %>%
  filter( (!roi_pair1 %in% sig_pairs$pair_id) & (!roi_pair2 %in% sig_pairs$pair_id) ) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  mutate(scale_correlation = scale(correlation)) %>%
  ungroup() 



```




## OFC 

```{r, fig.width = 12, fig.height = 8}

control <- lme4::lmerControl(optCtrl = list(maxfun = 1e5, tolPwrss = 1e-4))
start_values <- list(theta = c(0.1, .1))

# OFC ~ HC, sig, nsig, sig #
ofc_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "hc"),  control = control, start = start_values)
summary(ofc_hc_model)
bayestestR::ci(ofc_hc_model)

# OFC ~ Insula, sig, sig, sig #
ofc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "insula"),  control = control, start = start_values)
summary(ofc_insula_model)
bayestestR::ci(ofc_insula_model)

# OFC ~ dlPFC,  sig, sig, sig #
ofc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "mfg"),  control = control, start = start_values)
summary(ofc_mfg_model)
bayestestR::ci(ofc_mfg_model)

# OFC ~ Ant. Cingulate, not sig, sig, not sig#
ofc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "cing"),  control = control, start = start_values)
summary(ofc_cing_model)
bayestestR::ci(ofc_cing_model)

# OFC ~ Amygdala, not sig, not sig, not sig #
ofc_amyg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "amyg"),  control = control, start = start_values)
summary(ofc_amyg_model)
bayestestR::ci(ofc_amyg_model)

```


## Amygdala 

```{r, fig.width = 12, fig.height = 8}

# Amygdala ~ HC, sig, not sig, sig #
amyg_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "hc"),  control = control, start = start_values)
summary(amyg_hc_model)
bayestestR::ci(amyg_hc_model)

# Amygdala ~ Insula, not sig, not sig, not sig #
amyg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "insula"),  control = control, start = start_values)
summary(amyg_insula_model)
bayestestR::ci(amyg_insula_model)

# Amygdala ~ dlPFC, not sig, sig, not sig#
amyg_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "mfg"),  control = control, start = start_values)
summary(amyg_mfg_model)
bayestestR::ci(amyg_mfg_model)

# Amygdala ~ Ant. Cing, not sig, not sig, not sig #
amyg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "cing"),  control = control, start = start_values)
summary(amyg_cing_model)
bayestestR::ci(amyg_cing_model)

# Amygdala ~ OFC, not sig, not sig, not sig #
ofc_amyg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "amyg"),  control = control, start = start_values)
summary(ofc_amyg_model)
bayestestR::ci(ofc_amyg_model)


```


## HC 

```{r, fig.width = 12, fig.height = 8}

# OFC ~ HC, sig, not sig, sig #
ofc_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "hc"),  control = control, start = start_values)
summary(ofc_hc_model)
bayestestR::ci(ofc_hc_model)

# HC ~ Insula, not sig, not sig, not sig #
hc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "insula"),  control = control, start = start_values)
summary(hc_insula_model)
bayestestR::ci(hc_insula_model)

# HC ~ dlPFC, not sig, not sig, not sig #
hc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "mfg"),  control = control, start = start_values)
summary(hc_mfg_model)
bayestestR::ci(hc_mfg_model)

# HC ~ Cing, not sig, not sig, not sig #
hc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "cing"),  control = control, start = start_values)
summary(hc_cing_model)
bayestestR::ci(hc_cing_model)

# Amygdala ~ HC, sig, not sig, sig #
amyg_hc_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "hc"),  control = control, start = start_values)
summary(amyg_hc_model)
bayestestR::ci(amyg_hc_model)


```


## Insula 

```{r, fig.width = 12, fig.height = 8}

# OFC ~ Insula, sig, sig, sig #
ofc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "insula"),  control = control, start = start_values)
summary(ofc_insula_model)
# parameters::p_value(ofc_insula_model)
# parameters::ci(ofc_insula_model, method = "boot")
bayestestR::ci(ofc_insula_model)

# HC ~ Insula, not sig, not sig, not sig #
hc_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "insula"),  control = control, start = start_values)
summary(hc_insula_model)
bayestestR::ci(hc_insula_model)

# dlPFC ~ Insula, sig, sig, sig #
mfg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "mfg" & second_region == "insula"),  control = control, start = start_values)
summary(mfg_insula_model)
bayestestR::ci(mfg_insula_model)

# Ant. Cing ~ Insula,  not sig, not sig, not sig #
cing_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "insula"),  control = control, start = start_values)
summary(cing_insula_model)
bayestestR::ci(cing_insula_model)

# Amygdala ~ Insula, not sig, not sig, not sig #
amyg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "insula"),  control = control, start = start_values)
summary(amyg_insula_model)
bayestestR::ci(amyg_insula_model)

```


## Cing 

```{r, fig.width = 12, fig.height = 8}


# OFC ~ Cing, not sig, sig, not sig #
ofc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "cing"),  control = control, start = start_values)
summary(ofc_cing_model)
bayestestR::ci(ofc_cing_model)

# HC ~ Cing, not sig, not sig, not sig #
hc_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "cing"),  control = control, start = start_values)
summary(hc_cing_model)
bayestestR::ci(hc_cing_model)

# dlPFC ~ Cing, sig, sig, sig #
mfg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "mfg"),  control = control, start = start_values)
summary(mfg_cing_model)
bayestestR::ci(mfg_cing_model)

# Ant. Cing ~ Insula,  not sig, not sig, not sig #
cing_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "insula"),  control = control, start = start_values)
summary(cing_insula_model)
bayestestR::ci(cing_insula_model)

# Amygdala ~ Cing, not sig, not sig, not sig #
amyg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "cing"),  control = control, start = start_values)
summary(amyg_cing_model)
bayestestR::ci(amyg_cing_model)

```


## mfg 

```{r, fig.width = 12, fig.height = 8}


# dlPFC ~ Insula, sig, sig, sig #
mfg_insula_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "mfg" & second_region == "insula"),  control = control, start = start_values)
summary(mfg_insula_model)
bayestestR::ci(mfg_insula_model)

# HC ~ dlPFC, not sig, not sig, not sig #
hc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "hc" & second_region == "mfg"),  control = control, start = start_values)
summary(hc_mfg_model)
bayestestR::ci(hc_mfg_model)

# dlPFC ~ Cing, sig, sig, sig #
mfg_cing_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "cing" & second_region == "mfg"),  control = control, start = start_values)
summary(mfg_cing_model)
bayestestR::ci(mfg_cing_model)

# OFC ~ dlPFC,  sig, sig, sig #
ofc_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "ofc" & second_region == "mfg"),  control = control, start = start_values)
summary(ofc_mfg_model)
bayestestR::ci(ofc_mfg_model)

# Amygdala ~ dlPFC, not sig, didn't converge, not sig #
amyg_mfg_model <- blmer(scale_correlation ~ logged_times + (1 + logged_times||subject:roi_pair1), data = correlation_sig_df %>% filter(first_region == "amyg" & second_region == "mfg"),  control = control, start = start_values)
summary(amyg_mfg_model)
bayestestR::ci(amyg_mfg_model)


```



