---
title: "PCA on Theta Connectivity"
output: html_document
date: "2024-05-24"
---

```{r setup, include=FALSE}
## libraries ##
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(lmtest)
library(scales)
library(ggthemr)
library(RColorBrewer)
library(broom.mixed)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))
source(path(here(), "R", 'compile_ieeg_csv_files.R'))
source(path(here(), "R", 'run_and_plot_lme_models.R'))

## plotting helpers ##
ggthemr("light")
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

```


```{r load-data}


# load correlations #
ofc_corr_df <- read_csv(path(here(), "results", "ofc_correlations.csv"))
all_other_corr_df <- read_csv(path(here(), "results", "all_other_correlations.csv"))
correlation_df <- bind_rows(ofc_corr_df, all_other_corr_df)

# fix pair id to fit with sig pairs
correlation_df <- correlation_df %>%
  rowwise() %>%
  mutate(roi_pair1 = paste0(subject, gsub(subject, "", elec1), "_to", gsub(subject, "", elec2)),
         roi_pair2 = paste0(subject, gsub(subject, "", elec2), "_to", gsub(subject, "", elec1))) %>%
  ungroup()


# load sig pairs by coherence analysis #
sig_pairs <- read_csv(path(here(), "results", "sig_theta_pairs.csv"))

sig_pairs <- sig_pairs %>%
  mutate(pair_id = paste0(subject, "_", pairs)) %>%
  filter(metric == "Imaginary Coherence")

# filter ofc_turnDf to sig pairs
correlation_sig_df <- correlation_df %>%
  filter( (roi_pair1 %in% sig_pairs$pair_id) | (roi_pair2 %in% sig_pairs$pair_id) ) %>%
  filter(!is.na(correlation)) %>%
  filter(!is.infinite(logged_times)) %>%
  mutate(scale_correlation = scale(correlation)[,]) %>%
  ungroup() 

```


```{r}


pca_df <- correlation_sig_df %>%
  filter(subject == "BJH027") %>%
  select(roi_pair1,  trial, scale_correlation) %>%
  distinct() %>%
  pivot_wider(names_from = roi_pair1, values_from = scale_correlation, values_fn = mean) 

pca_tmp <- prcomp(pca_df %>% select(-trial), center = TRUE, scale = TRUE)


summary(pca_tmp)

pca_loadings <- as_tibble(pca_tmp$rotation)

pca_loadings$roi_pair1 <- colnames(pca_df %>% select(-trial))

pca_loadings <- pca_loadings %>%
  select(roi_pair1, starts_with("P"))

combined_df <- left_join(pca_loadings, correlation_sig_df %>% select(roi_pair1, first_region, second_region) %>% distinct(), by = c("roi_pair1" = "roi_pair1"))


```

```{r, fig.width = 15, fig.height = 5}

combined_df %>%
  mutate(roi = paste0(first_region, "_", second_region)) %>%
  select(roi, PC1) %>%
  ggplot(., aes(x = PC1)) +
  geom_density() +
  geom_vline(xintercept = 0, color = "black") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~roi, nrow = 2)

combined_df %>%
  mutate(roi = paste0(first_region, "_", second_region)) %>%
  select(roi, PC2) %>%
  ggplot(., aes(x = PC2)) +
  geom_density() +
  geom_vline(xintercept = 0, color = "black") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~roi, nrow = 2) +
  ggtitle("dlPFC PC ?")

combined_df %>%
  mutate(roi = paste0(first_region, "_", second_region)) %>%
  select(roi, PC3) %>%
  ggplot(., aes(x = PC3)) +
  geom_density() +
  geom_vline(xintercept = 0, color = "black") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~roi, nrow = 2) +
  ggtitle("HC PC ?")

combined_df %>%
  mutate(roi = paste0(first_region, "_", second_region)) %>%
  select(roi, PC4) %>%
  ggplot(., aes(x = PC4)) +
  geom_density() +
  geom_vline(xintercept = 0, color = "black") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~roi, nrow = 2)

combined_df %>%
  mutate(roi = paste0(first_region, "_", second_region)) %>%
  select(roi, PC5) %>%
  ggplot(., aes(x = PC5)) +
  geom_density() +
  geom_vline(xintercept = 0, color = "black") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~roi, nrow = 2)

```

```{r, fig.width = 15, fig.height = 5}
ggthemr("solarized")

combined_df %>%
  mutate(roi = paste0(first_region, "_", second_region)) %>%
  select(roi, PC1) %>%
  filter(PC1 <= -.05 | PC1 >= .05) %>%
  mutate(dir = if_else(PC1 <0, "neg", "pos")) %>%
  ggplot(., aes(x = roi, fill = dir)) +
  geom_bar() +
  theme(panel.background = element_rect(fill = "white")) 

combined_df %>%
  mutate(roi = paste0(first_region, "_", second_region)) %>%
  select(roi, PC2)  %>%
  filter(PC2 <= -.05 | PC2 >= .05) %>%
  mutate(dir = if_else(PC2 <0, "neg", "pos")) %>%
  ggplot(., aes(x = roi, fill = dir)) +
  geom_bar() +
  theme(panel.background = element_rect(fill = "white")) 

combined_df %>%
  mutate(roi = paste0(first_region, "_", second_region)) %>%
  select(roi, PC3)  %>%
  filter(PC3 <= -.05 | PC3 >= .05) %>%
  mutate(dir = if_else(PC3 <0, "neg", "pos")) %>%
  ggplot(., aes(x = roi, fill = dir)) +
  geom_bar() +
  theme(panel.background = element_rect(fill = "white")) +
  ggtitle("HC PC?")

combined_df %>%
  mutate(roi = paste0(first_region, "_", second_region)) %>%
  select(roi, PC4)  %>%
  filter(PC4 <= -.05 | PC4 >= .05) %>%
  mutate(dir = if_else(PC4 <0, "neg", "pos")) %>%
  ggplot(., aes(x = roi, fill = dir)) +
  geom_bar() +
  theme(panel.background = element_rect(fill = "white")) 

combined_df %>%
  mutate(roi = paste0(first_region, "_", second_region)) %>%
  select(roi, PC5)  %>%
  filter(PC5 <= -.05 | PC5 >= .05) %>%
  mutate(dir = if_else(PC5 <0, "neg", "pos")) %>%
  ggplot(., aes(x = roi, fill = dir)) +
  geom_bar() +
  theme(panel.background = element_rect(fill = "white")) 

```
```{r pls}

library(pls)

pls_df <- correlation_sig_df %>%
  filter(subject == "BJH027") %>%
  select(roi_pair1,  trial, turn_time, scale_correlation) %>%
  distinct() %>%
  pivot_wider(names_from = roi_pair1, values_from = scale_correlation, values_fn = mean) 


predictors <- as.matrix(pls_df %>% select(-turn_time, -trial))
turn_times <- pls_df$turn_time

pls_model <- plsr(turn_times ~ predictors, ncomp = 10, validation = "CV")

summary(pls_model)

plot(RMSEP(pls_model), legendpos = "topright")


```

