---
title: "Pacman: Game Setup and Ghost Movement in IEEG Sample, All Data"
author: "Jules"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=F, echo=F}
knitr::opts_chunk$set(
  root.dir =
  echo <- FALSE,
  fig.width <- 8,  
  fig.height <- 4, 
  fig.align <- "center",  
  fig.pos <- "H",  
  cache <- FALSE) 

library(lmerTest)
library(car)
library(merTools) 
library(dplyr)
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr) # devtools::install_github('Mikata-Project/ggthemr')
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(effectsize)
library(scales)
library(devtools)
library(patchwork)
library(sjPlot)
library(lattice) 
```
```{r plotting helpers, include=F, echo=F}
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "blue1", "steelblue4", "#80B1D3", "skyblue2", "#5BBCD6", "dodgerblue2", "darkturquoise", "#8DD3C7",  "#1C8E7A",
  
  "green1", "green4", "#50A45C", "#78C679",  "palegreen2", "#B3DE69", "#ADDD8E", "#A1D99B", "#C7E9C0","#CCEBC5", "#D9F0A3",
  
  "gold1",  "#FFFFB3", "yellow4", "yellow3", "khaki2",
  
  "#FF7F00", "#FDBF6F", "#FDB462", "#F3A300", "#FB8072",  "#FB9A99",
  
  "#E31A1C", "#FF0000", "#FD5372", "deeppink1", "orchid1", "#FCCDE5", "maroon", 
  
  "#6A3D9A", "#BC80BD", "#9986A5", "#CAB2D6", "#BEBADA", "orchid4",
  
  "darkorange4", "brown", "black", "grey70","#D9D9D9" 
)

my_theme <- theme_classic() +
  theme(panel.grid.major.y = element_line(colour = "grey70", linewidth = 0.1), axis.ticks = element_blank())

tt_order <- c("3","15","1","13","2","14","4","16","7","11","5","9","6","10","8","12", "17", "18", "19", "20")
color_order <- list("3","15","2","14","7","11","6","10", "17", "18", "19", "20") # numbers represent trial type
distance_colors1 <- c("#FCCDE5", "#BC80BD")
distance_colors2 <- c("maroon1", "maroon4")
dot_colors1 <- c("#CCEBC5", "#8DD3C7")
dot_colors2 <- c("skyblue", "skyblue4")
time_colors <- c("khaki2", "#FB9A99")
```
```{r data, include=F, echo=F}
distance_ghost <- read.csv('all_subs_complete_distance_df.csv') 
distance_noghost <- read.csv('all_subs_noghost_complete_distance_df.csv') 
all_data <- read.csv('all_subs_complete_behavior_df.csv')
```

```{r ghost mutated, include=F, echo=F}
# ghost_mutated includes trials with a ghost present
ghost_mutated <- distance_ghost %>%
  filter(Trial != "0") %>%
  group_by(subject, trial_numeric) %>%

  mutate(
  # Recreating ghost movement variable. Necessary in IEEG due to downsampling of data.
  ghost_objective_direction_tmp = c(FALSE, diff(GhostLocation)),
  ghost_objective_direction = if_else(ghost_objective_direction_tmp >= 2, "Right", 
                              if_else(ghost_objective_direction_tmp <= -2, "Left", "still")),
  ghost_direction = if_else((base_start_location < 100 & ghost_objective_direction == "Left") |
                            (base_start_location > 100 & ghost_objective_direction == "Right") , "Towards",
                    if_else(ghost_objective_direction == "still", "still", "Away")),
  new_ghost_direction = ifelse(ghost_direction == "still", NA, ghost_direction)) %>%
  fill(new_ghost_direction, .direction = "downup") %>%
  mutate(ghost_direction = ifelse(is.na(new_ghost_direction), ghost_direction, new_ghost_direction)) %>%
  select(-new_ghost_direction) %>%
  
  mutate(
    # ghost starting direction (ghost movement direction at the beginning of the trial)
    gsd_new = ifelse(trial_flip == 2 & ghost_direction == "Towards", 1, 0), 
    gsd_new = max(gsd_new), 
    gsd_new = ifelse(gsd_new == 1, "towards", "away"),
    former_gsd = ghost_start_dir, 
    
    current_ghost_direction = ghost_objective_direction,
    prev_ghost_direction = lag(ghost_objective_direction),
    ghost_turn = ifelse(is.na(prev_ghost_direction) | prev_ghost_direction == current_ghost_direction, 0, 1),
    ghost_turn_count = cumsum(ghost_turn),
    current_trial_flip = trial_flip,
    
    ghost_start_pos = ifelse(current_trial_flip ==1, GhostLocation, 0),
    ghost_start_pos = max(ghost_start_pos),
    current_ghost_position = GhostLocation, # check

    dot5_position = ifelse(current_trial_flip == 1, Biscuit5, 0),
    dot5_position = max(dot5_position),
    ghost_dot5_dis = ifelse(attack_chase_bob == "Bob", abs(current_ghost_position - dot5_position), 999),
    min_dis_ghost_dot5 = min(ghost_dot5_dis),
    min_dis_ghost_dot5 = ifelse(min_dis_ghost_dot5 == 999, NA, min_dis_ghost_dot5),
    overlap_dot5 = ifelse(GhostLocation == dot5_position, "overlap", "no overlap"),
        
    ) %>% 
  ungroup()

# noghost mutated includes trials without a ghost
noghost_mutated <- distance_noghost 
```
```{r all data mutated, echo=F, include=F}
# combine noghost and ghost datasets
all_data_mutated <- bind_rows(ghost_mutated, noghost_mutated) %>%
  group_by(subject, trial_numeric) %>% 
  mutate(
    first_flip = min(trial_flip),
    trial_flip = (trial_flip - first_flip + 1),
    initial_score = first(Score),
    first_movement_flip = ifelse(move_step != 0, trial_flip, 999), 
    first_movement_flip = min(first_movement_flip),                
    first_movement_time =  ifelse(trial_flip == first_movement_flip, trial_time, 0),
    first_movement_time = max(first_movement_time), 
    move_step = ifelse(trial_flip == 1, 0, move_step), #repeat for former third trials
    
    trialtype_new = case_when(
      gsd_new == "away" & base_start_location > 100 & reward_groups == 2 ~ 1,
      gsd_new == "away" & base_start_location > 100 & reward_groups == 3 ~ 2,
      gsd_new == "away" & base_start_location > 100 & reward_groups == 1 ~ 3,
      gsd_new == "away" & base_start_location > 100 & reward_groups == 4 ~ 4,
      gsd_new == "towards" & base_start_location < 100 & reward_groups == 2 ~ 5,
      gsd_new == "towards" & base_start_location < 100 & reward_groups == 3 ~ 6,
      gsd_new == "towards" & base_start_location < 100 & reward_groups == 1 ~ 7,
      gsd_new == "towards" & base_start_location < 100 & reward_groups == 4 ~ 8,
      gsd_new == "towards" & base_start_location > 100 & reward_groups == 2 ~ 9,
      gsd_new == "towards" & base_start_location > 100 & reward_groups == 3 ~ 10,
      gsd_new == "towards" & base_start_location > 100 & reward_groups == 1 ~ 11,
      gsd_new == "towards" & base_start_location > 100 & reward_groups == 4 ~ 12,
      gsd_new == "away" & base_start_location < 100 & reward_groups == 2 ~ 13,
      gsd_new == "away" & base_start_location < 100 & reward_groups == 3 ~ 14,
      gsd_new == "away" & base_start_location < 100 & reward_groups == 1 ~ 15,
      gsd_new == "away" & base_start_location < 100 & reward_groups == 4 ~ 16, 
      is.na(gsd_new) & base_start_location > 100 & base_start_location < 120 ~ 17,
      is.na(gsd_new) & base_start_location > 120 ~ 18,
      is.na(gsd_new) & base_start_location < 60 ~ 19,
      is.na(gsd_new) & base_start_location > 60 & base_start_location < 80 ~ 20),
    tt_fail = ifelse(trialtype_new == TrialType, "same", "fail"),
    tt_color = if_else(as.factor(trialtype_new) %in% color_order, 'odd', 'even')
  ) %>%
  rename(trialtype_old = TrialType) %>%
  ungroup()

rm(ghost_mutated, noghost_mutated, distance_ghost, distance_noghost)
```
```{r removing bad trials, echo=F}
# mark bad trials for each participant
bad_trials_list <- list(
  participant1 = data.frame(subject = "SLCH002", Trial = c(10,30,51,57,79,92,97,101,126,133,150,167,168,223,224,225)), #incl 126 2 jumps
  participant2 = data.frame(subject = "LL19", Trial = c(5,9,12,13,21,23,27,30,33,44,46,48,53,57,61,64,67,72,73,78,79,91,93, 110,118,120,122,126,127,131,135,157,158,160,174,187,196,206,218,14,52,151)),    
  participant3 = data.frame(subject = "LL17", Trial = c(16,17,81,83,121,128,132,147,162,173,190,191,223,227,228,235,237,243,245)),    
  participant4 = data.frame(subject = "LL14", Trial = c(3,6,25,35,48,95,179,183,193,198,206,237,255,274,289,337,382,391, 394,406,417,473,486,491,494,526,543,570,634,647,653,681,686,699,712,728,785,797,81)),    
  participant5 = data.frame(subject = "LL13", Trial = c(5,6,7,10,19,22,32,49,59,72,102,118,128,161,171,191,195,201,175,181)),    
  participant6 = data.frame(subject = "LL12", Trial = c(18,40,66,69,89,97,157,247)),    
  participant7 = data.frame(subject = "LL10", Trial = c(28,29,54,82,100,102,103,164,168,228,8)),    
  participant8 = data.frame(subject = "BJH041", Trial = c(2,50,59,73,87,89,111)),    
  participant9 = data.frame(subject = "BJH039", Trial = c(1,2,9,28,100,122,130,160,180,218,13)),    
  participant10 = data.frame(subject = "BJH029", Trial = c(5,12,32,57,136,140,164,223,230)),    
  participant11 = data.frame(subject = "BJH016", Trial = c(34,35,36,71,72,432,433,1,4,7,12,14,25,28,39,40,49,59,61,69,76,84,94, 96,103,108,115,116,118,142,169,185,202,238,248,258,310,323,342,360,366,379,382,386,387,391,407,417,451,452,8,16,32,24,66,81,102,112,392)),  
  participant12 = data.frame(subject = "BJH021", Trial = c(1,2,6,79,82,83,98,104,124,191,209,237,18)),    
  participant13 = data.frame(subject = "BJH025", Trial = c(23,49,63,80,97,99,100,106,167,170,211,232,10,13,6)),    
  participant14 = data.frame(subject = "BJH026", Trial = c(4,151,158,162,171,175,182,196,2,31)),    
  participant15 = data.frame(subject = "BJH027", Trial = c(10,28,34,71,77,78,123,124,149,172,179,180,190,209,211,225,234))
)

# convert the list to a data frame
bad_trials_df <- map_df(bad_trials_list, ~ .x %>%  # Convert the list to a data frame
                          mutate(subject = subject)) %>%
                select(subject, Trial)

# filter out bad trials
clean_all_mutated <- all_data_mutated %>% # Filter out bad trials
  anti_join(bad_trials_df, by = c("subject" = "subject", "Trial" = "Trial"))

# clean up
rm(bad_trials_list, bad_trials_df)
```
```{r trial data, echo=F}
# creates data set that only includes the first flip of each trial
trial_data <- clean_all_mutated %>%
  filter(trial_flip == 1) 

rm(all_data_mutated)
```
```{r trial count subject, echo=F, include=F}
# count_data <- trial_data %>%
#   group_by(subject) %>%
#   summarise(trials = n()) %>%
#   arrange(desc(trials))
# kable(count_data, caption = "Trial Counts per Subject")
```
  
## Game Setup in All Data (IEEG Sample)    
Overview of the distribution of different variables before applying any filters to the data. Bad trials have been removed.      
    

```{r user start location, fig.width=12, echo=F, warning=F}
# user location by starting side. this to check whether the starting side manipulation worked 
trial_data %>%
  select(subject, Trial, UserLocation, starting_side, gsd_new) %>%
  distinct() %>%
  count(UserLocation, starting_side) %>%
  ggplot(aes(x = UserLocation, y = n, fill = starting_side)) +
  geom_bar(stat = "identity", position = "dodge") + scale_x_continuous(breaks = seq(0, 160, 10)) + 
  my_theme + scale_fill_manual(values = c("Right" = "#8DD3C7", "Left" = "khaki2")) +
  labs(title = "User Start Location", x = "Location (units)", y = "Count")
```
```{r aggregate RG, starting side, GSD, echo=F, warning=F, message=F}
# checking for an equal distribution of different variables 

# Starting Side
trial_data %>%
  count(starting_side) %>%
  ggplot(aes(x = starting_side, y = n, fill = starting_side)) +
  geom_bar(stat = "identity", position = "dodge") +
  my_theme + scale_y_continuous(breaks = seq(0, 2200, 500)) + 
  scale_fill_manual(values = c("Right" = "#8DD3C7", "Left" = "khaki2")) +
  coord_cartesian(ylim = c(0,2200)) + 
  theme(legend.position = "none") +
  labs(x = "Starting Side", y = "Count", fill = "starting_side", title="Starting Side Distribution")

# RG
trial_data %>%
  filter(trialtype_new < 17) %>%
  count(reward_groups) %>%
  ggplot(aes(x = reward_groups, y = n, fill = reward_groups)) +
  geom_bar(stat = "identity", position = "dodge") +
  my_theme + coord_cartesian(ylim = c(0,1000)) + scale_y_continuous(breaks = seq(0, 1000, 200)) + 
  theme(legend.position = "none") +
  labs(x = "Reward Groups", y = "Count", fill = "reward_groups", title="Reward Groups Distribution")

# GSD
trial_data %>%
  filter(trialtype_new < 17) %>%
  count(gsd_new) %>%
  ggplot(aes(x = gsd_new, y = n, fill = gsd_new)) +
  geom_bar(stat = "identity", position = "dodge") + my_theme + 
  scale_fill_manual(values = c("towards" = "maroon", "away" = "#FCCDE5")) + coord_cartesian(ylim = c(0,2500)) + 
  theme(legend.position = "none") + scale_y_continuous(breaks = seq(0, 2500, 500)) + 
  labs(x = "GSD", y = "Count", fill = "GSD", title="GSD Distribution")

```
```{r individual gsd, echo=F, fig.height=8}
# Distribution of GSD for each participant
trial_data %>%
  select(subject, Trial, gsd_new) %>%
  distinct() %>%
  filter(!(is.na(gsd_new))) %>%
  ggplot(., aes(x = factor(gsd_new), fill = gsd_new)) +
    geom_bar() + facet_wrap(~subject, nrow=5) +
    my_theme + theme(legend.position = "none") +
    scale_fill_manual(values = c("towards" = "maroon", "away" = "#FCCDE5")) +
    labs(title = "Distribution of GSD for each Participant", x = "GSD", y = "Count")
```

```{r aggregate RG & GSD, echo=F}
# Distribution of GSD for each reward group
trial_data %>%
  filter(trialtype_new < 17) %>%
  count(reward_groups, gsd_new) %>%
  ggplot(aes(x = reward_groups, y = n, fill = gsd_new)) +
  geom_bar(stat = "identity", position = "dodge") +
  my_theme + scale_fill_manual(values = c("towards" = "deeppink4", "away" = "pink2")) +
  labs(x = "Reward Group", y = "Count", fill = "GSD", title="GSD by Rewardgroup") + coord_cartesian(ylim = c(0,800)) 
```
```{r individual RG & GSD, echo=F, fig.height=8}
# For each participant: distribution of GSD for each reward group
trial_data %>%
  filter(trialtype_new < 17) %>%
  group_by(subject) %>%
  count(reward_groups, gsd_new) %>%
  ggplot(aes(x = reward_groups, y = n, fill = gsd_new)) +
    geom_bar(stat = "identity", position = "dodge") + facet_wrap(~subject, nrow=5) + 
    my_theme + scale_fill_manual(values = c("towards" = "deeppink4", "away" = "pink2")) +
    labs(x = "Reward Group", y = "Count", fill = "GSD", title="GSD by Reward Group for each Participant")
```

```{r aggregate starting side & GSD, echo=F}
# Distribution of GSD for each starting side
trial_data %>%
  filter(trialtype_new < 17) %>%
  count(starting_side, gsd_new) %>%
  ggplot(aes(x = starting_side, y = n, fill = gsd_new)) +
  geom_bar(stat = "identity", position = "dodge") +
  my_theme + scale_fill_manual(values = c("towards" = "#CAB2D6", "away" = "#BC80BD")) +
  labs(x = "Starting Side", y = "Count", fill = "GSD", title="GSD by Starting Side")
```
```{r individual starting side & GSD, echo=F, fig.height=8}
# For each participant: distribution of GSD for each starting side
trial_data %>%
  filter(trialtype_new < 17) %>%
  group_by(subject) %>%
  count(starting_side, gsd_new) %>%
  ggplot(aes(x = starting_side, y = n, fill = gsd_new)) +
    geom_bar(stat = "identity", position = "dodge") + facet_wrap(~subject, nrow=5) + 
    my_theme + scale_fill_manual(values = c("towards" = "#CAB2D6", "away" = "#BC80BD")) +
    labs(x = "Starting Side", y = "Count", fill = "GSD", title="GSD by Starting Side for each Participant")
```

## Note:  
Order within plots:  
- pairs of similar trial types  
- groups of 4 of rewardgroup type (first 4 = low, next 4 = high)  
- groups of 8 of GSD (first half = away, 2nd half = towards)  

```{r aggregate trial types, echo=F}
# Distribution of trial type
trial_data %>%
  ggplot(., aes(x = factor(trialtype_new, level=tt_order), fill=tt_color)) +
    geom_bar() +
    my_theme + theme(legend.position = "none") +
    scale_fill_manual(values = distance_colors1) +
    labs(title = "Distribution of Trial Types", x = "Trial Type", y = "Count")

```
```{r individual trial types, echo=F, fig.height=8}
# For each participant: distribution of trial type
trial_data %>%
  select(subject, Trial, trialtype_new, tt_color) %>%
  distinct() %>%
  ggplot(., aes(x = factor(trialtype_new, level=tt_order), fill=tt_color)) +
    geom_bar() + facet_wrap(~subject, nrow=5) +
    my_theme + theme(legend.position = "none") +
    scale_fill_manual(values = distance_colors1) +
    labs(title = "Distribution of Trial Types for each Participant", x = "Trial Type", y = "Count")

```



