---
title: "SLCH002 JMBayes2"
output: html_document
date: "2023-09-06"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(effectsize)
library(scales)
library(JMbayes2)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))
source(path(here(), "R", 'create_timelock_event_tables.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)

```




```{r BJH025-data-load}

bjh25_data <- read_csv(path(here(), './data/ieeg_behave/BJH025_raw_behave.csv'), col_types = cols(`...1` = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))
# bjh25_data_raw <- bjh25_data_raw %>%
#     rename(sample = Time) %>%
#     mutate(Time = sample /2000)

```

```{r BJH025-data-prep}
# Subject paused to get out of dying and that resulted in an incorrect trial count
bjh25_data <- bjh25_data %>%
  mutate(Trial = as.numeric(Trial)) %>%
  filter(Trial != 7) %>%
  mutate(Trial = if_else(Trial < 7, Trial, Trial -1)) %>%
  mutate(Trial = as.character(Trial))

# clean Biscuits #
bjh25_data_clean <- clean_bci_data(bjh25_data, 2000)

# create distance df #
bjh25_data_distance <- create_distance_df_bci(bjh25_data_clean)

# task vars df #
bjh25_all_vars_df <- get_across_task_variables_bci(bjh25_data_clean)

```
```{r load-theta}

# brain data #
hc_onset_df <- read_csv(path(here(), "munge", "theta_behavior_hc_all_subs_onset.csv"))

# join data #
hc_behavior_df <- left_join(bjh25_data_distance %>% mutate(trial_time = round(trial_time, 2)), hc_onset_df %>% mutate(trial_time = round(trial_time, 2)))

hc_behavior_df <- hc_behavior_df %>%
  mutate(ghost = if_else(grepl("noghost", electrode), "noghost", "ghost")) %>%
  mutate(electrode = gsub("_.*", "", electrode))

```



```{r}

hc_behavior_df %>%
  mutate(final_reward = if_else(reward_groups >2, "big", "small")) %>%
  select(trial_numeric, dots_eaten, subject, final_reward, reward_groups) %>%
  distinct() %>%
  ggplot(., aes(fill = factor(reward_groups), x = factor(dots_eaten))) +
  geom_bar(position = position_dodge()) + 
  theme(panel.background = element_rect(fill = "white"))

hc_behavior_df %>%
  select(trial_numeric, dots_eaten, subject) %>%
  distinct() %>%
  ggplot(., aes(x =dots_eaten)) +
  geom_histogram(binwidth = 1) +
  theme(panel.background = element_rect(fill = "white"))


bjh25_data_distance %>%
  filter(Direction != "Still") %>%
  ggplot(., aes(x = factor(Lives), y = distance_to_ghost)) +
  geom_boxplot(notch = T) +
  theme(panel.background = element_rect(fill = "white"))


 sub_df <- hc_behavior_df %>%
  filter(electrode == "I4-I5") %>%
  filter(Direction != "Still") %>%
  filter(dots_eaten != 0) %>%
  group_by(trial_numeric) %>%
  mutate(trial_time = trial_time - first(trial_time)) %>%
  mutate(final_reward = if_else(reward_groups >2, "big", "small")) %>%
  mutate(Bisc4_tmp = if_else(Biscuit4 == 1111, UserLocation, Biscuit4)) %>%
  mutate(Bisc4 = if_else(Biscuit4 == 1111, 1, 0)) %>%
  mutate(dist_to_dot_4 = abs(Bisc4_tmp - UserLocation)) %>%
  mutate(Eaten_rev = 5 - Eaten) %>%
  mutate(last_big_reward = if_else(reward_groups %in% c(3, 4), Biscuit5, if_else(reward_groups == 2, Biscuit4, Biscuit3))) %>%
  mutate(dist_last_big_rtmp = if_else(last_big_reward == 1111, UserLocation, last_big_reward)) %>%
  mutate(dist_last_big_r = abs(dist_last_big_rtmp - UserLocation)) %>%
  ungroup() 
 
 
 sub_df %>%
   filter(trial_numeric %in% sample(trial_numeric, 5)) %>%
   ggplot(., aes(x = trial_time, y = theta)) +
   geom_point() +
   geom_line() +
   theme(panel.background = element_rect(fill = "white")) +
   facet_wrap(~trial_numeric)


correlation_mat <- cor(sub_df %>% select(distance_to_ghost, trial_time, Bisc4, Eaten_rev, dist_to_dot_4, points_remaining, Eaten, discounted_reward, distance_to_next_reward, points_aquired, dist_last_big_r))

ggcorrplot(correlation_mat)

sub_cox_df %>%
  ggplot(., aes(x = Time)) +
  geom_histogram()

```

```{r joint-modeling-threat-only}


### Prep Data 

# filter to single subject and reset time to be from when they started moving #
sub_df <- hc_behavior_df %>%
  filter(electrode == "I4-I5") %>%
  filter(Direction != "Still") %>%
  # filter(dots_eaten != 0) %>%
  group_by(trial_numeric) %>%
  mutate(trial_time = trial_time - first(trial_time)) %>%
  mutate(final_reward = if_else(reward_groups >2, "big", "small")) %>%
  mutate(Bisc4_tmp = if_else(Biscuit4 == 1111, UserLocation, Biscuit4)) %>%
  mutate(dist_to_dot_4 = abs(Bisc4_tmp - UserLocation)) %>%
  mutate(Bisc4_tmp = if_else(Biscuit4 == 1111, UserLocation, Biscuit4)) %>%
  mutate(dist_to_dot_4 = abs(Bisc4_tmp - UserLocation)) %>%
  ungroup() %>%
  select(subject, trial_numeric, distance_to_ghost, last_away, theta,
         away_choice, trial_time, TrialType, dist_to_dot_4) %>%
  mutate(EVENT = 1)

# get hold out trials #
set.seed(56)
hold_out_trials <- sample(unique(sub_df_tmp$trial_numeric), 20)

# create the survival dataframe
sub_cox_df <- sub_df %>%
  group_by(trial_numeric) %>%
  filter(away_choice == last_away & away_choice != 0) %>%
  filter(trial_time == last(trial_time)) %>%
  mutate(Time = trial_time) %>%
  ungroup() %>%
  mutate(event = 1) %>%
  select(trial_numeric, Time, event, EVENT) %>%
  filter(Time > 0) %>% # get rid of trials where they chose to leave from the moment they started moving
  filter(!trial_numeric %in% hold_out_trials)

# created longitudinal data frame #
all_trials_long_sub_df <- sub_df %>%
  group_by(trial_numeric) %>%
  mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
  mutate(turnaround_time = if_else(event == 1, trial_time, 0)) %>%
  filter(trial_time <= max(turnaround_time)) %>%
  mutate(Time = last(trial_time)) %>%
  ungroup() 

# exclude hold out subjects #  
trian_sub_long_df<-  all_trials_long_sub_df %>%
  filter(trial_numeric %in% sub_cox_df_tmp$trial_numeric)

test_long_sub_df <-  all_trials_long_sub_df_tmp %>%
  filter(trial_numeric %in% hold_out_trials) %>%
  filter(Time > 0)

### Fit Models ###

# longitudinal model #
control = lmeControl(maxIter = 1000, niterEM = 1000)
MixedModelFit2 <- lme(distance_to_ghost ~ trial_time, data = trian_sub_long_df_tmp, random = ~trial_time | trial_numeric, control = control)
summary(MixedModelFit2)

# survival model #
CoxFit <- coxph(Surv(Time, EVENT) ~ 1, data = sub_cox_df_tmp)

# joint model #
JMFit1_real <- jm(CoxFit, MixedModelFit2, time_var = "trial_time", data_Surv = sub_cox_df_tmp, n_burnin = 1000, n_iter = 30000, n_chains =8)
summary(JMFit1)

# ### traceplot ###
# traceplot(JMFit1)
# 
# ### densplot ###
# densplot(JMFit1)
# 
# ### cumuplot ###
# # cumuplot(JMFit1)
# 
# ### gelman_diag ###
# gelman_diag(JMFit1)

### AUC and ROC ###
tvAUC(JMFit1, test_long_sub_df, Tstart = .5, Thoriz = 2, idVar = 'trial_numeric')

roc <- tvROC(JMFit1, newdata = test_long_sub_df, Tstart = .5, Thoriz = 1.1, idVar = 'trial_numeric')
plot(roc) 

### Calibration Plot ###
calibration_plot(JMFit1_real, newdata = test_long_sub_df, Tstart = .5, Thoriz = 1.1, idVar = 'trial_numeric')
calibration_plot(JMFit1_real, newdata = test_long_sub_df %>% filter(!trial_numeric %in% c(69, 10, 76, 3)), Tstart = .5, Thoriz = 1.1, idVar = 'trial_numeric')
calibration_plot(JMFit1_real, newdata = all_trials_long_sub_df %>% filter(trial_numeric %in% test_long_sub_df_tmp$trial_numeric | trial_numeric %in% test_long_sub_df$trial_numeric), Tstart = .5, Thoriz = 1.1, idVar = 'trial_numeric')

calibration_metrics(JMFit1, newdata = test_long_sub_df_tmp, Tstart = .5, Dt = .7, idVar = 'trial_numeric')
calibration_metrics(JMFit1, newdata = test_long_sub_df, Tstart = .5, Dt = .7, idVar = 'trial_numeric')

### Brier Scores ###
tvBrier(JMFit1, newdata = test_long_sub_df, Tstart = .5, Dt = 1)

tvBrier(JMFit1, newdata = test_long_sub_df, Tstart = .5, Dt = 1, integrated = T)

### Held Out Trials ###

test_trials <- sort(sample(hold_out_trials, 13))

test_three_trials <- test_long_sub_df %>% 
  filter(trial_numeric %in% test_trials) %>%
  filter(trial_time < .5) %>%
  select(-Time, -EVENT)


trial_1 <- test_long_sub_df %>% filter(trial_numeric == test_trials[1]) %>% filter(trial_time < .5)
trial_2 <- test_long_sub_df %>% filter(trial_numeric == test_trials[2]) %>% filter(trial_time < .5)
trial_3 <- test_long_sub_df %>% filter(trial_numeric == test_trials[3]) %>% filter(trial_time < .5)

test_three_preds <- predict(JMFit1, 
          newdata = test_three_trials, process = "event", return_newdata = TRUE, 
          idVar = "trial_numeric", times = seq(.5, 2.5, .05))




ggthemr("solarized")
ggplot() +
  geom_rect(aes(xmin=0, xmax=.5, ymin=0, ymax=1), fill = "lightgrey", alpha = .5) +
  geom_point(data = test_three_preds, aes(x = trial_time, y = pred_CIF, color = factor(trial_numeric))) +
  # geom_ribbon(data = test_three_preds, aes(x = trial_time, ymin = low_CIF, ymax = upp_CIF, fill = factor(trial_numeric)), alpha = .5) +
  geom_vline(xintercept = test_long_sub_df %>% filter(trial_numeric == test_trials[1]) %>% pull(Time) %>% unique()) +
  geom_vline(xintercept = test_long_sub_df %>% filter(trial_numeric == test_trials[2]) %>% pull(Time) %>% unique(),
             color = "#E68D81") +
  geom_vline(xintercept = test_long_sub_df %>% filter(trial_numeric == test_trials[3]) %>% pull(Time) %>% unique()
             , color = "#5EB7AB") +
  theme(panel.background = element_rect(fill = "white")) +
  ylim(0, 1) + xlim(0, 2.5) +
  ggtitle("Prediction on three held out trials") +
  labs(x = "Time", y = "Probability of Turning Around")

```


Predicted probabilities are cut up and then the observed probabilities is the proportion of subjects who exerpienced the event base on the predicted prob binning!

```{r tmp}

test <- predict(JMFit1,  newdata = test_long_sub_df %>% filter(trial_time < .5), process = "event",
                return_newdata = TRUE, idVar = "trial_numeric", times = seq(0, 2.5, .05))
        
ggplot() +
  geom_rect(aes(xmin=0, xmax=.5, ymin=0, ymax=1), fill = "lightgrey", alpha = .5) +
  geom_point(data = test_three_preds, aes(x = trial_time, y = pred_CIF, color = factor(trial_numeric))) +
  scale_color_manual(values = getPalette(9)) +
  theme(panel.background = element_rect(fill = "white"))

```



```{r joint-modeling-threat-only}


### Prep Data 

# filter to single subject and reset time to be from when they started moving #
sub_df <- bjh25_data_distance %>%
  filter(Direction != "Still") %>%
  # filter(dots_eaten != 0) %>%
  group_by(trial_numeric) %>%
  mutate(trial_time = trial_time - first(trial_time)) %>%
  mutate(final_reward = if_else(reward_groups >2, "big", "small")) %>%
  mutate(Bisc4_tmp = if_else(Biscuit4 == 1111, UserLocation, Biscuit4)) %>%
  mutate(dist_to_dot_4 = abs(Bisc4_tmp - UserLocation)) %>%
  mutate(Bisc4_tmp = if_else(Biscuit4 == 1111, UserLocation, Biscuit4)) %>%
  mutate(dist_to_dot_4 = abs(Bisc4_tmp - UserLocation)) %>%
  ungroup() %>%
  select(subject, trial_numeric, distance_to_ghost, last_away, 
         away_choice, trial_time, TrialType, dist_to_dot_4) %>%
  mutate(EVENT = 1)

# get hold out trials #
set.seed(56)
hold_out_trials <- sample(unique(sub_df$trial_numeric), 20)

# create the survival dataframe
sub_cox_df <- sub_df %>%
  group_by(trial_numeric) %>%
  filter(away_choice == last_away & away_choice != 0) %>%
  filter(trial_time == last(trial_time)) %>%
  mutate(Time = trial_time) %>%
  ungroup() %>%
  mutate(event = 1) %>%
  select(trial_numeric, Time, event, EVENT) %>%
  filter(Time > 0) %>% # get rid of trials where they chose to leave from the moment they started moving
  filter(!trial_numeric %in% hold_out_trials) 

# created longitudinal data frame #
all_trials_long_sub_df <- sub_df %>%
  group_by(trial_numeric) %>%
  mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
  mutate(turnaround_time = if_else(event == 1, trial_time, 0)) %>%
  filter(trial_time <= max(turnaround_time)) %>%
  mutate(Time = last(trial_time)) %>%
  ungroup() 

# exclude hold out subjects #  
trian_sub_long_df <-  all_trials_long_sub_df %>%
  filter(trial_numeric %in% sub_cox_df$trial_numeric)

test_long_sub_df <-  all_trials_long_sub_df %>%
  filter(trial_numeric %in% hold_out_trials) %>%
  filter(Time > 0)

### Fit Models ###

# longitudinal model #
control = lmeControl(maxIter = 1000, niterEM = 1000)
MixedModelFit2 <- lme(distance_to_ghost ~ trial_time, data = trian_sub_long_df, random = ~trial_time | trial_numeric, control = control)
summary(MixedModelFit2)

# survival model #
CoxFit <- coxph(Surv(Time, EVENT) ~ 1, data = sub_cox_df)

# joint model #
JMFit1 <- jm(CoxFit, MixedModelFit2, time_var = "trial_time", data_Surv = sub_cox_df, n_burnin = 1000, n_iter = 30000, n_chains =8)
summary(JMFit1)

# ### traceplot ###
# traceplot(JMFit1)
# 
# ### densplot ###
# densplot(JMFit1)
# 
# ### cumuplot ###
# # cumuplot(JMFit1)
# 
# ### gelman_diag ###
# gelman_diag(JMFit1)

### AUC and ROC ###
tvAUC(JMFit1, test_long_sub_df, Tstart = .5, Thoriz = 1.5, idVar = 'trial_numeric')

roc <- tvROC(JMFit1, newdata = test_long_sub_df, Tstart = .5, Thoriz = 1.5, idVar = 'trial_numeric')
plot(roc) 

### Calibration Plot ###
calibration_plot(JMFit1, newdata = test_long_sub_df, Tstart = .5, Thoriz = 1.1, idVar = 'trial_numeric')

calibration_metrics(JMFit1, newdata = test_long_sub_df, Tstart = .5, Thoriz = 1.1, idVar = 'trial_numeric')

### Brier Scores ###
tvBrier(JMFit1, newdata = test_long_sub_df, Tstart = .5, Dt = 1)

tvBrier(JMFit1, newdata = test_long_sub_df, Tstart = .5, Dt = 1, integrated = T)

### Held Out Trials ###

test_trials <- sort(sample(hold_out_trials, 3))

test_three_trials <- test_long_sub_df %>% 
  filter(trial_numeric %in% test_trials) %>%
  filter(trial_time < .5) %>%
  select(-Time, -EVENT)


trial_1 <- test_long_sub_df %>% filter(trial_numeric == test_trials[1]) %>% filter(trial_time < .5)
trial_2 <- test_long_sub_df %>% filter(trial_numeric == test_trials[2]) %>% filter(trial_time < .5)
trial_3 <- test_long_sub_df %>% filter(trial_numeric == test_trials[3]) %>% filter(trial_time < .5)

test_three_preds <- predict(JMFit1, 
          newdata = test_three_trials, process = "event", return_newdata = TRUE, 
          idVar = "trial_numeric", times = seq(0, 2.5, .05))



ggthemr("solarized")
ggplot() +
  geom_rect(aes(xmin=0, xmax=.5, ymin=0, ymax=1), fill = "lightgrey", alpha = .5) +
  geom_point(data = test_three_preds, aes(x = trial_time, y = pred_CIF, color = factor(trial_numeric))) +
  # geom_ribbon(data = test_three_preds, aes(x = trial_time, ymin = low_CIF, ymax = upp_CIF, fill = factor(trial_numeric)), alpha = .5) +
  geom_vline(xintercept = test_long_sub_df %>% filter(trial_numeric == test_trials[1]) %>% pull(Time) %>% unique()) +
  geom_vline(xintercept = test_long_sub_df %>% filter(trial_numeric == test_trials[2]) %>% pull(Time) %>% unique(),
             color = "#E68D81") +
  geom_vline(xintercept = test_long_sub_df %>% filter(trial_numeric == test_trials[3]) %>% pull(Time) %>% unique()
             , color = "#5EB7AB") +
  theme(panel.background = element_rect(fill = "white")) +
  ylim(0, 1) + xlim(0, 2.5) +
  ggtitle("Prediction on three held out trials") +
  labs(x = "Time", y = "Probability of Turning Around")

```
THE DIFFERENCE IN THE TEST SET NOT THE MODEL DRIVES THE DIFFERENCE!
```{r}

# test data
glimpse(test_long_sub_df)
glimpse(test_long_sub_df_tmp) # curved

shared_test <- test_long_sub_df %>%
  filter(trial_numeric %in% test_long_sub_df_tmp$trial_numeric)


#only tmp
tmp_unique_test <- test_long_sub_df_tmp %>%
  filter(!trial_numeric %in% test_long_sub_df$trial_numeric)
  
combined_test <- rbind(test_long_sub_df, test_long_sub_df_tmp %>% select(-theta))

combined_test <- combined_test %>% distinct()


# tmp_unique_test
tmp_unique_test %>%
  ggplot(., aes(x = Time)) +
  geom_histogram() +
  theme(panel.background = element_rect(fill = "white"))

# tmp_unique_test
test_long_sub_df %>%
  ggplot(., aes(x = Time)) +
  geom_histogram() +
  theme(panel.background = element_rect(fill = "white"))


preds_test_unique <- predict(JMFit1_real, 
          newdata = tmp_unique_test %>% filter(trial_time < .5) %>% select(-Time, -EVENT), process = "event", return_newdata = TRUE, 
          idVar = "trial_numeric", times = seq(1, 1.2, .05))



```






