---
title: "Survival Analysis Tutorial"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(lubridate)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))

## plotting helpers ##
ggthemr("solarized")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)

```

## Load Pacman data ##

```{r load-data}
# game data #
pilot_game_data <- read_csv(path(here(), '../behavioral_parsing/prolific_data_clean/cleaned_pacman_200_trial_n69.csv'), col_types = cols(X1 = col_double(),
                                                                                              subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double(),
                                                                                              final_score = col_double()))

# behavioral data#
pilot_behave_data <- read_csv(path(here(), '../behavioral_parsing/prolific_data_clean/cleaned_behave_data_200_trial_n69.csv'), col_types = cols())

# metadata / IDs #
pacman_ids <- read_csv(path(here(), '../behavioral_parsing/prolific_data_clean/cleaned_ids_200_trial_n69.csv'))

# merge with ids to confirm parsing worked #
pilot_behave_data_clean <- merge.data.frame(pilot_behave_data, pacman_ids, by = c("subject", "ID"))

```

## Prep behavioral data

```{r beahvioral-prep}

# clean Biscuits #
pilot_game_data_clean <- pilot_game_data %>%
  # ungrouped timing variables
  mutate(time_step = c(FALSE, diff(Time))) %>%
  mutate(trial_numeric = as.numeric(gsub("Trial_", "", Trial))) %>%
  ## grouped by trial variables
  group_by(subject, Trial) %>%
  mutate(start_location = first(UserLocation))


## IMPORTANT NOTES ##
# subject 84 and trial 48 somehow managed to press before trial began-- manually need to change startlocation to 63 and starting direction
# subject 70 on trial 127 also pressed, true start was 57


# clean Biscuits #
pilot_game_data_clean <- pilot_game_data %>%
  # ungrouped timing variables
  mutate(time_step = c(FALSE, diff(Time))) %>%
  mutate(trial_numeric = as.numeric(gsub("Trial_", "", Trial))) %>%
  ## grouped by trial variables
  group_by(subject, Trial) %>%
  mutate(jittered_start_location = first(UserLocation)) %>%
  mutate(base_start_location = if_else(TrialType %in% c(16, 8), 30,
                                       if_else(TrialType %in% c(19, 15, 14, 7, 6), 50,
                                               if_else(TrialType %in% c(20, 13, 5), 70,
                                                   if_else(TrialType %in% c(17, 12, 4), 110,
                                                       if_else(TrialType %in% c(18, 11, 10, 3, 2), 130,
                                                               if_else(TrialType %in% c(9, 1), 150, 999))))))) %>%
  # biscuit location
  mutate(Biscuit1 = if_else(Biscuit1 == FALSE & base_start_location <= 80,  base_start_location + 12, 
                            if_else(Biscuit1 == FALSE & base_start_location > 80, base_start_location -12, 1111)))  %>%
  mutate(Biscuit2 = if_else(Biscuit2 == FALSE & base_start_location <= 80,  base_start_location + 22, 
                            if_else(Biscuit2 == FALSE & base_start_location > 80, base_start_location -22, 1111)))  %>%
  mutate(Biscuit3 = if_else(Biscuit3 == FALSE & base_start_location <= 80,  base_start_location + 32, 
                            if_else(Biscuit3 == FALSE & base_start_location > 80, base_start_location -32, 1111)))  %>%
  mutate(Biscuit4 = if_else(Biscuit4 == FALSE & base_start_location <= 80,  base_start_location + 42, 
                            if_else(Biscuit4 == FALSE & base_start_location > 80, base_start_location -42, 1111)))  %>%
  mutate(Biscuit5 = if_else(Biscuit5 == FALSE & base_start_location <= 80,  base_start_location + 52, 
                            if_else(Biscuit5 == FALSE & base_start_location > 80, base_start_location -52, 1111)))  %>%
  # trial timing information
  mutate(Trial = if_else(Trial == "Trial_1", Trial, if_else(Time == first(Time), "ITI", Trial))) %>%
  mutate_cond(Trial == "ITI", 
              GhostLocation = NA, UserLocation = NA, 
              Biscuit1 = NA, Biscuit2 = NA, Biscuit3 = NA, Biscuit4 = NA, Biscuit5 = NA, 
              Attack = NA, Chase = NA, Eaten = NA, TrialType = NA) %>%
  mutate(trial_time = if_else(Trial == "ITI", 999, Time - first(Time))) %>%
  mutate(trial_flip = 1:n()) %>%
  mutate(time_lag = c(FALSE, diff(trial_time))) %>%
  mutate(trial_end = as.numeric(c(diff(trial_numeric) > 0, FALSE))) %>%
  mutate(trial_length = max(trial_time)) %>%
  # trial grouping variables
  mutate(reward_groups = if_else(TrialType %in% c(1, 5, 9, 13), 2, 
                                 if_else(TrialType %in% c(2, 6, 10, 14), 3, 
                                         if_else(TrialType %in% c(3, 7, 11, 15), 1, 
                                                 if_else(TrialType %in% c(4, 8, 12, 16), 4, 99))))) %>%
  mutate(ghost_start_dir = if_else(TrialType > 16, "no_ghost", 
                                   if_else(TrialType <= 4 | TrialType >= 13, "away", "towards"))) %>%
  mutate(rewards_direction_groups = paste0(reward_groups, "_", ghost_start_dir)) %>%
  mutate(attack_chase_bob = if_else(Attack == T, "Attack", if_else(Chase == T, "Chase", "Bob"))) %>%
  ungroup() %>%
  group_by(subject) %>%
  arrange(subject, trial_numeric) %>%
  mutate(life_change = as.numeric(c(diff(Score) < 0, FALSE))) %>%
  group_by(subject, Trial) %>%
  mutate(died = sum(life_change)) %>%
  select(-life_change) %>%
  ungroup()

# get rid of paused trials #
paused_trials <- pilot_game_data_clean %>%
  filter(time_step > 1 & trial_flip != 1 & Trial != "ITI") %>%
  ungroup() %>%
  mutate(trial_ids = paste0(subject, "_", trial_numeric)) %>%
  pull(trial_ids) %>%
  unique()

pilot_game_data_clean <- pilot_game_data_clean %>%
  ungroup() %>%
   mutate(trial_ids = paste0(subject, "_", trial_numeric)) %>%
  filter(!trial_ids %in% paused_trials)
 
pilot_game_data_distance <- pilot_game_data_clean %>%
  filter(Trial != "ITI") %>%
  filter(!is.na(GhostLocation)) %>%
  filter(died == 0) %>%
  group_by(subject, Trial) %>%
  # user movement and distance measures
  mutate(distance_to_ghost = abs(GhostLocation - UserLocation)) %>%
  mutate(min_distance = min(distance_to_ghost)) %>%
  mutate(towards_ghost = if_else(Direction == 2 & GhostLocation < UserLocation, "Towards", 
                                 if_else(Direction == 11 & GhostLocation > UserLocation, "Towards",
                                         if_else(Direction == 4, "Still", "Away")))) %>%
  mutate(away_choice_tmp = c(0, diff(factor(towards_ghost)))) %>%
  mutate(away_choice = if_else( (away_choice_tmp == -2 & towards_ghost == "Away") | 
                                  (away_choice_tmp == -1 & towards_ghost == "Away"), distance_to_ghost, 0)) %>%
  select(-away_choice_tmp) %>%
  mutate(number_of_runs = sum(away_choice > 0, na.rm = T)) %>%
  mutate(last_away = if_else(number_of_runs == 0, 0, last(away_choice[away_choice > 0]) )) %>%
  ungroup()

```


```{r general-surv-curve}

survival_df_test <- pilot_game_data_distance %>%
  filter(subject == "Subject_49") %>%
  group_by(trial_numeric) %>%
  filter(trial_time <= trial_time[away_choice == last_away]) %>%
  mutate(trial_time = round(trial_time/.05)*.05) %>%
  mutate(survival_time = max(trial_time)) %>%
  mutate(censor = 1) %>%
  select(subject, trial_time, trial_numeric, survival_time, censor, reward_groups) %>%
  distinct() %>% 
  ungroup()


survival_df_test %>%
  ggplot(., aes(x= trial_time)) +
  geom_histogram(alpha = .5, binwidth = .05, aes(y = 100 *(..count..)/length(unique(survival_df_test$trial_numeric)))) +
  # geom_density(aes(y = ..count../sum(..count..))) +
  # geom_bar(aes(y = ..count../sum(..count..))) +
  ylab("Percent of Trials") +
  theme(panel.background = element_rect(fill = "white")) 


```



## prep for survival analysis

```{r prep-surv}
library(survival)
library(ranger)
library(ggplot2)
library(dplyr)
library(ggfortify)


survival_df_test <- pilot_game_data_distance %>%
  filter(subject == "Subject_49") %>%
  group_by(trial_numeric) %>%
  filter(trial_time <= trial_time[away_choice == last_away]) %>%
  mutate(trial_time = round(trial_time/.1)*.1) %>%
  mutate(survival_time = max(trial_time)) %>%
  mutate(censor = 1) %>%
  select(subject, trial_time, trial_numeric, survival_time, censor, Direction) %>%
  distinct() %>% 
  ungroup()



# create survival object
s1 <- Surv(survival_df_test$survival_time, survival_df_test$censor) 

# fit a basic KM curve
f1 <- survfit(s1 ~ 1, data = survival_df_test)
summary(f1)

```


```{r visualize-km-curve}

# look at survival curve
ggsurvplot(
    fit = f1, 
    xlab = "Seconds", 
    ylab = "Overall survival probability")


# difference in survival by reward group
reward_survival <- survdiff(Surv(survival_df_test$survival_time, survival_df_test$censor) ~ Direction, data = survival_df_test)
ezfun::sdp(reward_survival)

## same thing using coxph
reward_surv_cox <- coxph(Surv(survival_df_test$survival_time, survival_df_test$censor) ~ Direction, data = survival_df_test)
reward_surv_cox %>%
  gtsummary::tbl_regression(exp = TRUE) 

reward_surv_cox_fit <- survfit(reward_surv_cox)

autoplot(reward_surv_cox_fit, type = "fill")

```



```{r coxph-basic-model}

# cox_df_test <- pilot_game_data_distance %>%
#   filter(last_away != 0) %>% # filter out times person ran into the ghost
#   filter(subject == "Subject_49") %>%
#   # group_by(subject, trial_numeric) %>%
#   filter(trial_time <= trial_time[tail(which(away_choice == last_away), n= 1)]) %>% # gross
#   mutate(survival_time = max(trial_time)) %>%
#   mutate(status = if_else(survival_time ==trial_time, 1, 0 )) %>%
#   mutate(time1 = round(trial_time, digits = 2)) %>%
#   mutate(time2 = c(time1[2:n()], time1[n()] + .05)) %>%
#   mutate(time1_r = round(time1/.05)*.05) %>%
#   mutate(time2_r = round(time2/.05)*.05) %>%
#   mutate(dif = time2_r - time1_r) %>%
#   mutate(dif_prob = if_else(dif < .049 | dif > .051, 1, 0)) %>%
#   mutate(dif_prob_sum = sum(dif_prob)) %>%
#   filter(dif_prob_sum == 0) %>%
#   select(subject, trial_numeric, survival_time, min_distance, status, reward_groups, distance_to_ghost, jittered_start_location, Eaten, Score, Lives, Direction, time1, time2, number_of_runs) %>%
#   distinct()

threat_function <- distributions3::Beta(2, 5.5)
cox_df_test <- pilot_game_data_distance %>%
  filter(last_away != 0) %>% # filter out times person ran into the ghost
  filter(subject == "Subject_49") %>%
  group_by(trial_numeric) %>%
  filter(trial_time <= trial_time[away_choice == last_away]) %>%
  mutate(trial_time = round(trial_time/.05)*.05) %>%
  mutate(survival_time = max(trial_time)) %>%
  mutate(time1 = round(trial_time, digits = 2)) %>%
  mutate(time2 = c(time1[2:n()], time1[n()] + .05)) %>%
  # mutate(time1_r = round(time1/.05)*.05) %>%
  # mutate(time2_r = round(time2/.05)*.05) %>%
  mutate(dif = time2 - time1) %>%
  mutate(status = if_else(survival_time ==trial_time, 1, 0 )) %>%
  mutate(censor = 1)  %>%
  mutate(dif_prob = if_else(dif < .049 | dif > .051, 1, 0)) %>%
  mutate(dif_prob_sum = sum(dif_prob)) %>%
  filter(dif_prob_sum == 0) %>%
  select(subject, trial_numeric, survival_time, min_distance, status, reward_groups,
         distance_to_ghost, jittered_start_location, Eaten, Score, Lives, Direction, time1, time2, dif, number_of_runs) %>%
  distinct() %>%
  mutate(cdf_distance = distributions3::cdf(threat_function, distance_to_ghost/100))



c1 <- coxph(Surv(time1, time2, status) ~  1, data=cox_df_test)

c1_fit <- survfit(c1)

autoplot(c1_fit) +
  theme(panel.background = element_rect(fill = "white"))


```

```{r cox-predict-model}

c2 <- coxph(Surv(time1, time2, status) ~  cdf_distance + Eaten + 
              reward_groups + Score + Lives +
              jittered_start_location + Direction,
            data=cox_df_test)

c2_fit <- survfit(c2)

autoplot(c2_fit) +
  theme(panel.background = element_rect(fill = "white"))

linelistsurv_ph_test <- cox.zph(c2)
linelistsurv_ph_test
ggcoxzph(linelistsurv_ph_test)

survival:::plot.cox.zph(linelistsurv_ph_test)


```


```{r}


f2_fit <- survfit(Surv(time1, time2, status) ~  
              cdf_distance, 
              data=cox_df_test, type = "fleming-harrington")

tmp <- ggsurvplot(f2_fit)



f2_fit <- aareg(Surv( time1, time2, status) ~  
              cdf_distance + Eaten + reward_groups + Score + Lives +
              jittered_start_location + Direction,
              data=cox_df_test)

f2_fit %>%
  broom::tidy() %>%
  mutate(p_sig = p.value < .05) %>%
  kable() %>%
  kable_styling()


autoplot(f2_fit) +
  theme(panel.background = element_rect(fill = "white"))


f2_autoplot <- autoplot(f2_fit)

f2_autoplot$data %>%
  ggplot(., aes(x = time, y = coef, color = variable, fill = variable)) +
  geom_line() +
  theme(panel.background = element_rect(fill = "white"))


```




