---
title: "Starting Side and Ghost Starting Direction"
output: html_document
date: "2024-02-29"
---

```{r setup, include=FALSE}
### batch files for joint modeling ###

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(effectsize)
library(scales)
library(JMbayes2)
library(caret)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", "clean_behavioral_data.R"))
source(path(here(), "R", "create_distance_df.R"))
source(path(here(), "R", "joint_modeling_functions.R"))
## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(9, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

```

### Stratified Splits


```{r}

## Load Data ##
hc_theta_data <- read_csv( path(here(), "munge", "theta_ieeg_hc_all_subs_logged_iti_onset.csv"))
game_data_distance <-  read_csv(path(here(), "munge", "all_subs_complete_distance_df.csv"))
game_data_behavior <-  read_csv(path(here(), "munge", "all_subs_complete_behavior_df.csv"))

```
```{r, fig.width=12, fig.height=8}


trial_setup_df <- game_data_behavior %>%
  filter(trial_flip == 10)


trial_setup_df %>%
  ggplot(., aes(x = starting_side, fill = starting_side)) +
  geom_bar() +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~subject, scales = "free") +
  scale_fill_manual(values = c("skyblue2", "darkturquoise"))

```



```{r, fig.width=12, fig.height=8}


ghost_start_df <- game_data_behavior %>%
  filter(TrialType <= 16) %>%
  group_by(subject, trial_numeric) %>%
  mutate(ghost_objective_direction_tmp = c(FALSE, diff(GhostLocation))) %>%
  mutate(ghost_objective_direction = if_else(ghost_objective_direction_tmp >= 2, "Right", 
                                             if_else(ghost_objective_direction_tmp <= -2, "Left", "still"))) %>%
  # select(-ghost_objective_direction_tmp) %>%
  mutate(ghost_direction = if_else((base_start_location < 100 & ghost_objective_direction == "Left") |
                                     (base_start_location > 100 & ghost_objective_direction == "Right") , "Towards",
                                   if_else(ghost_objective_direction == "still", "still", "Away"))) %>%
  mutate(new_ghost_direction = ifelse(ghost_direction == "still", NA, ghost_direction)) %>%
  fill(new_ghost_direction, .direction = "downup") %>%
  mutate(ghost_direction = ifelse(is.na(new_ghost_direction), ghost_direction, new_ghost_direction)) %>%
  select(-new_ghost_direction)

trial_setup_ghost_df <- ghost_start_df %>%
  filter(trial_flip == 10)
  
trial_setup_ghost_df %>%
  ggplot(., aes(x = starting_side, fill = ghost_direction)) +
  geom_bar(position = "dodge") +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~subject, scales = "free") +
  scale_fill_manual(values = c("lightblue", "darkturquoise"))

```


