---
title: "iEEG Normative Behavior"
output: html_document
date: "2023-09-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(effectsize)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", "clean_behavioral_data.R"))
source(path(here(), "R", "create_distance_df.R"))
## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)

```

```{r load-data}

# behavior data #
all_subs_dist <- read_csv(path(here(), "munge", "all_subs_distance_df.csv"))

# get last time #
all_subs_dist_clean <- all_subs_dist %>%
  mutate(trial_time = round(trial_time, 2)) %>%
  group_by(subject, trial_numeric) %>%
  mutate(event = if_else(last_away == away_choice & away_choice != 0, 1, 0)) %>%
  mutate(turnaround_time = if_else(event == 1, trial_time, 0)) %>%
  mutate(last_turn_time = max(turnaround_time)) %>%
  rowwise() %>%
  mutate(time_to_exit = trial_length - last_turn_time) %>% 
  ungroup() %>%
  filter(Eaten > 0)

```


```{r}

all_subs_dist_clean %>%
  # filter(subject != "BJH016") %>%
  select(subject, trial_numeric, last_turn_time) %>%
  distinct() %>%
  ggplot(., aes(x = last_turn_time, fill = subject)) +
  geom_histogram(binwidth = .1) +
  geom_vline(xintercept = 1, color = "black") +
  theme(panel.background = element_rect(fill = "white")) + 
  facet_wrap(~subject) +
  ggtitle("Turnaround Time") +
  xlim(0.001, 6)

all_subs_dist_clean %>%
  # filter(subject != "BJH016") %>%
  select(subject, trial_numeric, time_to_exit) %>%
  distinct() %>%
  ggplot(., aes(x = time_to_exit, fill = subject)) +
  geom_histogram(binwidth = .1) +
  geom_vline(xintercept = 1, color = "black") +
  theme(panel.background = element_rect(fill = "white")) + 
  facet_wrap(~subject) +
  ggtitle("Time to Exit")

all_subs_dist_clean %>%
  # filter(subject != "BJH016") %>%
  select(subject, trial_numeric, trial_length) %>%
  distinct() %>%
  ggplot(., aes(x = trial_length, fill = subject)) +
  geom_histogram(binwidth = .1) +
  geom_vline(xintercept = 2, color = "black") +
  theme(panel.background = element_rect(fill = "white")) + 
  facet_wrap(~subject) +
  ggtitle("Trial Length")


```
```{r}

all_subs_dist_clean %>%
  filter(subject == "BJH016") %>%
  filter(trial_numeric == 14) %>%
  ggplot(., aes(x = Time, y = trial_numeric)) +
  geom_point() + 
  geom_line() +
  theme(panel.background = element_rect(fill= "white"))


```


