---
title: "Fig 3 Example Coherence Plot"
output: html_document
date: "2024-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,  # don't print the code chunk
  warning = FALSE,  # don't print warnings
  message = FALSE,  # don't print messages
  fig.width = 8,  # set default width of figures
  fig.height = 5,  # set default height of figures
  fig.align = "center",  # always align figure in center
  fig.pos = "H",  # always plot figure at the exact location of the code chunk
  cache = FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(effectsize)
library(scales)
library(JMbayes2)
library(caret)
library(rmarkdown)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", "clean_behavioral_data.R"))
source(path(here(), "R", "create_distance_df.R"))
source(path(here(), "R", "joint_modeling_functions.R"))
source(path(here(), "R", "jm_visualization_functions.R"))
source(path(here(), "R", "connectivity_prep_functions.R"))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# # ## parallelization ##
# nCores <- 8
# registerDoParallel(nCores)


```



```{r load-data}

# load conn data
# conn_df <- read_csv(path(here(), "data_mount", "remote", "pacman/connectivity/ieeg/imcoh_ppc_pli/",  "combined_connectivity_newsubs.csv"))

```

```{r}

# find sig pair
# hc_amyg_scl2 <- conn_df %>%
#   filter(subject == "SLCH002") %>%
#   filter(first_region == "hc" & second_region == "amyg" & metric == "Imaginary Coherence") %>%
#   filter(time >= -1.5 & time <= 1.5) %>%
#   group_by(pairs) %>%
#   mutate(p_frd = p.adjust(percent_sig, method = "fdr")) %>%
#   mutate(sig = p_frd < 0.05) %>% 
#   mutate(sig_time_bins = sum(sig)) 

# pull perumtation csv (created on rivendell
example_df <- read_csv(path(here(), 'data_mount', 'remote', 'pacman/connectivity/ieeg/imcoh_ppc_pli/SLCH002_example_imcoh_fig3.csv'))

```

```{r}

example_plot_df <- example_df %>%
  filter(time >= -1.5 & time <= 1.5) %>%
  pivot_longer(cols = -time, names_to = "perm_true", values_to = "imcoh") %>%
  mutate(perm_case = if_else(grepl("perm", perm_true), "perm", "true"))
  

```


```{r plot, fig.width = 3.5, fig.height = 3, warning = F}


example_plot <- example_plot_df %>%
  mutate(abs_imcoh = abs(imcoh)) %>%
  mutate(log_abs_imcoh = log(abs_imcoh)) %>%
  ggplot(., aes(x = time, y = abs_imcoh, color = perm_case, alpha = perm_case, group = perm_true)) +
  geom_line() +
  geom_vline(xintercept = 0,  color = "#2D2327") +
  geom_hline(yintercept = 0,  color = "#2D2327") +
  scale_alpha_manual(values = c(.25, 1), guide = F) +
  scale_color_manual(values = c("darkgrey", "#FFA602")) +
  guides(color = guide_legend(nrow = 1, title = NULL)) +
  theme(panel.background = element_rect(fill = "white", color = "#2D2327"), 
        panel.grid = element_blank(),
        plot.margin = unit(c(.5, .5, 0, .5), "lines"),
        legend.position = c(.75,.94),
        legend.key=element_blank(),
        legend.margin = margin(),
        legend.box = element_blank(),
        legend.box.margin = margin(),
        # legend.title = element_blank(),
        axis.text = element_text(family = "Gill Sans", color = "#2D2327", size = 7),
        axis.title = element_text(family = "Gill Sans", color = "#2D2327", size = 7.5),
        legend.title = element_text(family = "Gill Sans", color = "#2D2327", size = 7),
        legend.text  = element_text(family = "Gill Sans", color = "#2D2327", size = 7),
        strip.text = element_text(family = "Gill Sans", color = "#2D2327", size = 7),
        plot.title = element_text(family = "Gill Sans", color = "#2D2327", size = 8, hjust = 0.5, margin = margin(b = 5)),
        plot.subtitle = element_text(family = "Gill Sans", color = "#2D2327", size = 7, margin = margin(b = 0)))  +
  labs(title = "Example Electrode Pair", subtitle = "Electrodes were placed in Hippocmpaus & Amygdala", x = "Time (s)", y = "Absolute Value of Imaginary Coherence") 
example_plot

ggsave(path(here(), "figures", "connectivity", "figure3_example_elec_pair.png"), 
       plot = example_plot, 
       width = 3.5, height = 2.5, units = "in", dpi = 600)

```




