---
title: "Finding Lag"
output: html_document
date: '2022-10-12'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lmerTest)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(effectsize)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)



```




## SLCH002

```{r SLCH002-data-load}

sl02_data <- read_csv(path(here(), './data/ieeg_behave/SLCH002_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


bjh16_data <- read_csv(path(here(), './data/ieeg_behave/BJH016_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


ll10_data <- read_csv(path(here(), './data/ieeg_behave/LL10_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))





```

```{r SLCH002-data-prep}


# clean df #
sl02_data_clean <- clean_bci_data(sl02_data, 2000)

# create distance df # 
sl02_data_distance <- create_distance_df_bci(sl02_data_clean)

# round trial time to match theta analyses #
sl02_data_distance <- sl02_data_distance %>%
    mutate(trial_time = as.character(round(trial_time, 3)))
  

```

```{r BJH016-data-prep}


# clean df #
bjh16_data_clean <- clean_bci_data(bjh16_data, 2000)

# create distance df # 
bjh16_data_distance <- create_distance_df_bci(bjh16_data_clean)

# round trial time to match theta analyses #
bjh16_data_distance <- bjh16_data_distance %>%
    mutate(trial_time = as.character(round(trial_time, 3)))
  

```

```{r LL10-data-prep}


# clean df #
ll10_data_clean <- clean_bci_data(ll10_data, 512)

# create distance df # 
ll10_data_distance <- create_distance_df_bci(ll10_data_clean)

# round trial time to match theta analyses #
ll10_data_distance <- ll10_data_distance %>%
    mutate(trial_time = as.character(round(trial_time, 2)))
  

```



## Hippocampus

```{r hc-slch02}

shift <- 0
hc_elecs <- list.files(path(here(), "data", "theta_csvs", "hc", "SLCH002"))

best_lags <- c()
for(file in hc_elecs){

  print(file)
  
  elec_theta_data <- read_csv(path(here(), "data", "theta_csvs", "hc", "SLCH002", file))
  
  # fix col names
  elec_theta_data <- elec_theta_data %>%
    select(-X1)
  colnames(elec_theta_data) <- c(paste0("bin_", colnames(elec_theta_data)[1:181]), 'trial_numeric')
  
  
  # pivot
  elec_theta_data <- elec_theta_data %>%
    pivot_longer(names_to = 'bin', values_to = 'theta', cols = starts_with("bin")) %>%
    mutate(bin = as.numeric(gsub("bin_", "", bin))) %>%
    mutate(bin = paste0("bin_", if_else(bin - shift > -1, bin - shift, 999))) %>%
    filter(bin != "bin_999") %>%
    mutate(trial_numeric = trial_numeric + 1) %>%
    mutate(trial_time = .05 * as.numeric(gsub("bin_", "", bin))) %>% 
    mutate(trial_time = as.character(round(trial_time, 3)))  %>% 
    select(-bin)
    
  
  # merge 
  elec_full_data <- inner_join(elec_theta_data, sl02_data_distance)
  
  elec_full_data <- elec_full_data %>%
     mutate(trial_numeric = factor(trial_numeric))

    
  lag_vec <- c()   
  for(trial in unique(elec_full_data$trial_numeric)){
    
    # print(paste0("Trial: ", trial))
    
    elec_full_data_single_trial <- elec_full_data %>%
      filter(trial_numeric == trial)
  
    tmp <- ccf(elec_full_data_single_trial$distance_to_ghost, elec_full_data_single_trial$theta, 
               lag.max = (length(elec_full_data_single_trial$theta) - 1), plot = F)
    
    # print(paste0("Best Lag: ", tmp$lag[which(min(tmp$acf) == tmp$acf)]))
    
    lag_vec <- c(lag_vec,  tmp$lag[which(min(tmp$acf) == tmp$acf)])
    
  }
  
  print(paste0("Electrode: ", file))
  hist_tmp <- hist(lag_vec, breaks = 179/2)
  print(paste0("Best overall lag: ", lag_vec[which(max(hist_tmp$counts) == hist_tmp$counts)]) ) 
  best_lags <- c(best_lags, lag_vec[which(max(hist_tmp$counts) == hist_tmp$counts)])
}
  
```





```{r hc-bjh016}


hc_elecs <- list.files(path(here(), "data", "theta_csvs", "hc", "BJH016"))


for(file in hc_elecs){

  print(file)
  
  elec_theta_data <- read_csv(path(here(), "data", "theta_csvs", "hc", "BJH016", file))
  
  # fix col names
  elec_theta_data <- elec_theta_data %>%
    select(-X1)
  colnames(elec_theta_data) <- c(paste0("bin_", colnames(elec_theta_data)[1:281]), 'trial_numeric')
  
  
  # pivot
  elec_theta_data <- elec_theta_data %>%
    pivot_longer(names_to = 'bin', values_to = 'theta', cols = starts_with("bin")) %>%
    mutate(trial_numeric = trial_numeric + 1) %>%
    mutate(trial_time = .05 * as.numeric(gsub("bin_", "", bin))) %>% 
    mutate(trial_time = as.character(round(trial_time, 3)))  %>% 
    select(-bin)
    
  
  # merge 
  elec_full_data <- inner_join(elec_theta_data, bjh16_data_distance)
  
  elec_full_data <- elec_full_data %>%
     mutate(trial_numeric = factor(trial_numeric))

    
  lag_vec <- c()   
  for(trial in unique(elec_full_data$trial_numeric)){
    
    # print(paste0("Trial: ", trial))
    
    elec_full_data_single_trial <- elec_full_data %>%
      filter(trial_numeric == trial)
  
    tmp <- ccf(elec_full_data_single_trial$distance_to_ghost, elec_full_data_single_trial$theta, 
               lag.max = (length(elec_full_data_single_trial$theta) - 1), plot = T)
    
    # print(paste0("Best Lag: ", tmp$lag[which(min(tmp$acf) == tmp$acf)]))
    
    lag_vec <- c(lag_vec,  tmp$lag[which(min(tmp$acf) == tmp$acf)])
    
  }
  
  print(paste0("Electrode: ", file))
  hist(lag_vec, breaks = 279)
  print(paste0("Best overall lag: ", lag_vec[which(max(hist_tmp$counts) == hist_tmp$counts)]) ) 
}
  
```

```{r hc-ll10}


hc_elecs <- list.files(path(here(), "data", "theta_csvs", "hc", "LL10"))


for(file in hc_elecs){

  print(file)
  
  elec_theta_data <- read_csv(path(here(), "data", "theta_csvs", "hc", "LL10", file))
  
  # fix col names
  elec_theta_data <- elec_theta_data %>%
    select(-X1)
  colnames(elec_theta_data) <- c(paste0("bin_", colnames(elec_theta_data)[1:181]), 'trial_numeric')
  
  
  # pivot
  elec_theta_data <- elec_theta_data %>%
    pivot_longer(names_to = 'bin', values_to = 'theta', cols = starts_with("bin")) %>%
    mutate(trial_numeric = trial_numeric + 1) %>%
    mutate(trial_time = .05 * as.numeric(gsub("bin_", "", bin))) %>% 
    mutate(trial_time = as.character(round(trial_time, 3)))  %>% 
    select(-bin)
    
  
  # merge 
  elec_full_data <- inner_join(elec_theta_data, ll10_data_distance)
  
  elec_full_data <- elec_full_data %>%
     mutate(trial_numeric = factor(trial_numeric))

    
  lag_vec <- c()   
  for(trial in unique(elec_full_data$trial_numeric)){
    
    # print(paste0("Trial: ", trial))
    
    elec_full_data_single_trial <- elec_full_data %>%
      filter(trial_numeric == trial)
  
    tmp <- ccf(elec_full_data_single_trial$distance_to_ghost, elec_full_data_single_trial$theta, 
               lag.max = (length(elec_full_data_single_trial$theta) - 1), plot = F)
    
    # print(paste0("Best Lag: ", tmp$lag[which(min(tmp$acf) == tmp$acf)]))
    
    lag_vec <- c(lag_vec,  tmp$lag[which(min(tmp$acf) == tmp$acf)])
    
  }
  
  print(paste0("Electrode: ", file))
  hist(lag_vec, breaks = 179)
  print(paste0("Best overall lag: ", lag_vec[which(max(hist_tmp$counts) == hist_tmp$counts)]) ) 
}
  
```



