---
title: "Approach/Avoid Theta Prep"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(ggeffects)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lmerTest)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))
source(path(here(), "R", 'merge_theta_and_behavioral_data.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)



```


# Prep for theta ~ behavioral analyses

Takes the behavoioral data and theta power data and combines them by trial type (ghost vs no ghost), as well as combined. 

Run by knitting

## Load Data

```{r SLCH002-data-load}

sl02_data <- read_csv(path(here(), './data/ieeg_behave/SLCH002_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


bjh16_data <- read_csv(path(here(), './data/ieeg_behave/BJH016_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh21_data <- read_csv(path(here(), './data/ieeg_behave/BJH021_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

bjh25_data <- read_csv(path(here(), './data/ieeg_behave/BJH016_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


ll10_data <- read_csv(path(here(), './data/ieeg_behave/LL10_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll12_data <- read_csv(path(here(), './data/ieeg_behave/LL12_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))

ll13_data <- read_csv(path(here(), './data/ieeg_behave/LL13_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))





```

## Prep Behavioral Data

```{r SLCH002-data-prep}


# clean df #
sl02_data_clean <- clean_bci_data(sl02_data, 2000)

# create distance df # 
sl02_data_distance <- create_distance_df_bci(sl02_data_clean)
sl02_data_distance_no_ghost <- create_distance_df_bci(sl02_data_clean, ghost = F)

```

```{r BJH016-data-prep}


# clean df #
bjh16_data_clean <- clean_bci_data(bjh16_data, 2000)

# create distance df # 
bjh16_data_distance <- create_distance_df_bci(bjh16_data_clean)
bjh16_data_distance_no_ghost <- create_distance_df_bci(bjh16_data_clean, ghost = F)

```
```{r BJH0121-data-prep}


# clean df #
bjh21_data_clean <- clean_bci_data(bjh21_data, 2000)

# create distance df # 
bjh21_data_distance <- create_distance_df_bci(bjh21_data_clean)
bjh21_data_distance_no_ghost <- create_distance_df_bci(bjh21_data_clean, ghost = F)

```

```{r BJH025-data-prep}

## Prep #
# Subject paused to get out of dying and that resulted in an incorrect trial count
bjh25_data <- bjh25_data %>%
  mutate(Trial = as.numeric(Trial)) %>%
  filter(Trial != 7) %>%
  mutate(Trial = if_else(Trial < 7, Trial, Trial -1)) %>%
  mutate(Trial = as.character(Trial))

# clean df #
bjh25_data_clean <- clean_bci_data(bjh25_data, 2000)

# create distance df # 
bjh25_data_distance <- create_distance_df_bci(bjh25_data_clean)
bjh25_data_distance_no_ghost <- create_distance_df_bci(bjh25_data_clean, ghost = F)


```


```{r LL10-data-prep}


# clean df #
ll10_data_clean <- clean_bci_data(ll10_data, 512)

# create distance df # 
ll10_data_distance <- create_distance_df_bci(ll10_data_clean)
ll10_data_distance_no_ghost <- create_distance_df_bci(ll10_data_clean, ghost = F)

```

```{r LL12-data-prep}


# clean df #
ll12_data_clean <- clean_bci_data(ll12_data, 512)

# create distance df # 
ll12_data_distance <- create_distance_df_bci(ll12_data_clean)
ll12_data_distance_no_ghost <- create_distance_df_bci(ll12_data_clean, ghost = F)

```

```{r LL10-data-prep}


# clean df #
ll13_data_clean <- clean_bci_data(ll13_data, 512)

# create distance df # 
ll13_data_distance <- create_distance_df_bci(ll13_data_clean)
ll13_data_distance_no_ghost <- create_distance_df_bci(ll13_data_clean, ghost = F)

```

## All subjects behavior data

```{r all_subs_behavior}

all_subs_data_clean <- rbind(sl02_data_clean, bjh16_data_clean, bjh21_data_clean, bjh25_data_clean,
                             ll10_data_clean, ll12_data_clean, ll13_data_clean)

write_csv(all_subs_data_clean, path(here(), "munge", "all_subs_behavior_df.csv"))
```

## Merge with Theta

```{r merge-theta-data-and-combine-hc}

#  onset Data
slch2_onset_df <- merge_theta_and_behavioral_data(roi = "hc", 
                                                  sub = "SLCH002", 
                                                  distance_df = sl02_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")
  
bjh16_onset_df <- merge_theta_and_behavioral_data(roi = "hc", 
                                                  sub = "BJH016", 
                                                  distance_df = bjh16_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh21_onset_df <- merge_theta_and_behavioral_data(roi = "hc", 
                                                  sub = "BJH021", 
                                                  distance_df = bjh21_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh25_onset_df <- merge_theta_and_behavioral_data(roi = "hc", 
                                                  sub = "BJH025", 
                                                  distance_df = bjh25_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")


ll10_onset_df <- merge_theta_and_behavioral_data(roi = "hc", 
                                                  sub = "LL10", 
                                                  distance_df = ll10_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll12_onset_df <- merge_theta_and_behavioral_data(roi = "hc", 
                                                  sub = "LL12", 
                                                  distance_df = ll12_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll13_onset_df <- merge_theta_and_behavioral_data(roi = "hc", 
                                                  sub = "LL13", 
                                                  distance_df = ll13_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")


# Bind together
onset_df <- rbind(slch2_onset_df, bjh16_onset_df, bjh21_onset_df, bjh25_onset_df,
                  ll10_onset_df, ll12_onset_df, ll13_onset_df)

# save #
write_csv(onset_df, path(here(), "munge", "theta_behavior_hc_all_subs_onset.csv"))

```


```{r merge-theta-data-and-combine-ofc}

#  onset Data
slch2_onset_df <- merge_theta_and_behavioral_data(roi = "ofc", 
                                                  sub = "SLCH002", 
                                                  distance_df = sl02_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")
  
bjh16_onset_df <- merge_theta_and_behavioral_data(roi = "ofc", 
                                                  sub = "BJH016", 
                                                  distance_df = bjh16_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh21_onset_df <- merge_theta_and_behavioral_data(roi = "ofc", 
                                                  sub = "BJH021", 
                                                  distance_df = bjh21_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh25_onset_df <- merge_theta_and_behavioral_data(roi = "ofc", 
                                                  sub = "BJH025", 
                                                  distance_df = bjh25_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")


ll10_onset_df <- merge_theta_and_behavioral_data(roi = "ofc", 
                                                  sub = "LL10", 
                                                  distance_df = ll10_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll12_onset_df <- merge_theta_and_behavioral_data(roi = "ofc", 
                                                  sub = "LL12", 
                                                  distance_df = ll12_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll13_onset_df <- merge_theta_and_behavioral_data(roi = "ofc", 
                                                  sub = "LL13", 
                                                  distance_df = ll13_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")


# Bind together
onset_df <- rbind(slch2_onset_df, bjh16_onset_df, bjh21_onset_df, bjh25_onset_df,
                  ll10_onset_df, ll12_onset_df, ll13_onset_df)

# save #
write_csv(onset_df, path(here(), "munge", "theta_behavior_ofc_all_subs_onset.csv"))


```


```{r merge-theta-data-and-combine-ac}

#  onset Data
slch2_onset_df <- merge_theta_and_behavioral_data(roi = "cing", 
                                                  sub = "SLCH002", 
                                                  distance_df = sl02_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")
  
bjh16_onset_df <- merge_theta_and_behavioral_data(roi = "cing", 
                                                  sub = "BJH016", 
                                                  distance_df = bjh16_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh21_onset_df <- merge_theta_and_behavioral_data(roi = "cing", 
                                                  sub = "BJH021", 
                                                  distance_df = bjh21_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh25_onset_df <- merge_theta_and_behavioral_data(roi = "cing", 
                                                  sub = "BJH025", 
                                                  distance_df = bjh25_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")


ll10_onset_df <- merge_theta_and_behavioral_data(roi = "cing", 
                                                  sub = "LL10", 
                                                  distance_df = ll10_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll12_onset_df <- merge_theta_and_behavioral_data(roi = "cing", 
                                                  sub = "LL12", 
                                                  distance_df = ll12_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll13_onset_df <- merge_theta_and_behavioral_data(roi = "cing", 
                                                  sub = "LL13", 
                                                  distance_df = ll13_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")


# Bind together
onset_df <- rbind(slch2_onset_df, bjh16_onset_df, bjh21_onset_df, bjh25_onset_df,
                  ll10_onset_df, ll12_onset_df, ll13_onset_df)

# save #
write_csv(onset_df, path(here(), "munge", "theta_behavior_cing_all_subs_onset.csv"))


```


```{r merge-theta-data-and-combine-amyg}

#  onset Data
slch2_onset_df <- merge_theta_and_behavioral_data(roi = "amyg", 
                                                  sub = "SLCH002", 
                                                  distance_df = sl02_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")
  
bjh16_onset_df <- merge_theta_and_behavioral_data(roi = "amyg", 
                                                  sub = "BJH016", 
                                                  distance_df = bjh16_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh21_onset_df <- merge_theta_and_behavioral_data(roi = "amyg", 
                                                  sub = "BJH021", 
                                                  distance_df = bjh21_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh25_onset_df <- merge_theta_and_behavioral_data(roi = "amyg", 
                                                  sub = "BJH025", 
                                                  distance_df = bjh25_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")


ll10_onset_df <- merge_theta_and_behavioral_data(roi = "amyg", 
                                                  sub = "LL10", 
                                                  distance_df = ll10_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll12_onset_df <- merge_theta_and_behavioral_data(roi = "amyg", 
                                                  sub = "LL12", 
                                                  distance_df = ll12_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll13_onset_df <- merge_theta_and_behavioral_data(roi = "amyg", 
                                                  sub = "LL13", 
                                                  distance_df = ll13_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")


# Bind together
onset_df <- rbind(slch2_onset_df, bjh16_onset_df, bjh21_onset_df, bjh25_onset_df,
                  ll10_onset_df, ll12_onset_df, ll13_onset_df)

# save #
write_csv(onset_df, path(here(), "munge", "theta_behavior_amyg_all_subs_onset.csv"))


```

```{r merge-theta-data-and-combine-dlpfc}

#  onset Data
slch2_onset_df <- merge_theta_and_behavioral_data(roi = "dlpfc", 
                                                  sub = "SLCH002", 
                                                  distance_df = sl02_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")
  
bjh16_onset_df <- merge_theta_and_behavioral_data(roi = "dlpfc", 
                                                  sub = "BJH016", 
                                                  distance_df = bjh16_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh21_onset_df <- merge_theta_and_behavioral_data(roi = "dlpfc", 
                                                  sub = "BJH021", 
                                                  distance_df = bjh21_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh25_onset_df <- merge_theta_and_behavioral_data(roi = "dlpfc", 
                                                  sub = "BJH025", 
                                                  distance_df = bjh25_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")


ll10_onset_df <- merge_theta_and_behavioral_data(roi = "dlpfc", 
                                                  sub = "LL10", 
                                                  distance_df = ll10_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll12_onset_df <- merge_theta_and_behavioral_data(roi = "dlpfc", 
                                                  sub = "LL12", 
                                                  distance_df = ll12_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll13_onset_df <- merge_theta_and_behavioral_data(roi = "dlpfc", 
                                                  sub = "LL13", 
                                                  distance_df = ll13_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")


# Bind together
onset_df <- rbind(slch2_onset_df, bjh16_onset_df, bjh21_onset_df, bjh25_onset_df,
                  ll10_onset_df, ll12_onset_df, ll13_onset_df)

# save #
write_csv(onset_df, path(here(), "munge", "theta_behavior_dlpfc_all_subs_onset.csv"))


```


```{r merge-theta-data-and-combine-insula}

#  onset Data
slch2_onset_df <- merge_theta_and_behavioral_data(roi = "insula", 
                                                  sub = "SLCH002", 
                                                  distance_df = sl02_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")
  
bjh16_onset_df <- merge_theta_and_behavioral_data(roi = "insula", 
                                                  sub = "BJH016", 
                                                  distance_df = bjh16_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh21_onset_df <- merge_theta_and_behavioral_data(roi = "insula", 
                                                  sub = "BJH021", 
                                                  distance_df = bjh21_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

bjh25_onset_df <- merge_theta_and_behavioral_data(roi = "insula", 
                                                  sub = "BJH025", 
                                                  distance_df = bjh25_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

ll12_onset_df <- merge_theta_and_behavioral_data(roi = "insula", 
                                                  sub = "LL12", 
                                                  distance_df = ll12_data_clean, 
                                                  timelock_folder = "trial_onset",
                                                  keyword_include = "trial_theta_onset_locked_ghost.csv", keyword_exclude = "_noghost.csv")

# Bind together
onset_df <- rbind(slch2_onset_df, bjh16_onset_df, bjh21_onset_df, bjh25_onset_df,
                  ll10_onset_df, ll12_onset_df, ll13_onset_df)

# save #
write_csv(onset_df, path(here(), "munge", "theta_behavior_insula_all_subs_onset.csv"))


```





# Choice

```{r merge-theta-data-and-combine-choice}

#  Ghost Data
slch2_ghost_choice_df <- merge_theta_and_behavioral_data("hc", "SLCH002", sl02_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")
bjh16_ghost_choice_df <- merge_theta_and_behavioral_data("hc", "BJH016", bjh16_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")
ll10_ghost_choice_df <- merge_theta_and_behavioral_data("hc", "LL10", ll10_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")


# No Ghost Data
slch2_no_ghost_choice_df <- merge_theta_and_behavioral_data("hc", "SLCH002", sl02_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")
bjh16_no_ghost_choice_df <- merge_theta_and_behavioral_data("hc", "BJH016", bjh16_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")
ll10_no_ghost_choice_df <- merge_theta_and_behavioral_data("hc", "LL10", ll10_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")

# Bind together
choice_ghost_df <- rbind(slch2_ghost_choice_df %>% mutate(subject = "SLCH002"),
                  bjh16_ghost_choice_df %>% mutate(subject = "BJH016"),
                  ll10_ghost_choice_df %>% mutate(subject = "LL10"))

choice_no_ghost_df <- rbind(slch2_no_ghost_choice_df %>% mutate(subject = "SLCH002"),
                  bjh16_no_ghost_choice_df %>% mutate(subject = "BJH016"),
                  ll10_no_ghost_choice_df %>% mutate(subject = "LL10"))


# save #
write_csv(choice_ghost_df, path(here(), "results", "theta", "theta_behavior_hc_choice_all_subs_ghost.csv"))
write_csv(choice_no_ghost_df, path(here(), "results", "theta", "theta_behavior_hc_choice_all_subs_noghost.csv"))

```


```{r ofc-merge-theta-data-and-combine-choice}

#  Ghost Data
slch2_ghost_choice_df <- merge_theta_and_behavioral_data("OFC", "SLCH002", sl02_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")
bjh16_ghost_choice_df <- merge_theta_and_behavioral_data("OFC", "BJH016", bjh16_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")


# No Ghost Data
slch2_no_ghost_choice_df <- merge_theta_and_behavioral_data("OFC", "SLCH002", sl02_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")
bjh16_no_ghost_choice_df <- merge_theta_and_behavioral_data("OFC", "BJH016", bjh16_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")

# Bind together
choice_ghost_df <- rbind(slch2_ghost_choice_df %>% mutate(subject = "SLCH002"),
                  bjh16_ghost_choice_df %>% mutate(subject = "BJH016"))

choice_no_ghost_df <- rbind(slch2_no_ghost_choice_df %>% mutate(subject = "SLCH002"),
                  bjh16_no_ghost_choice_df %>% mutate(subject = "BJH016"))

# save #
write_csv(choice_ghost_df, path(here(), "results", "theta", "theta_behavior_ofc_choice_all_subs_ghost.csv"))
write_csv(choice_no_ghost_df, path(here(), "results", "theta", "theta_behavior_ofc_choice_all_subs_noghost.csv"))

```


```{r ac-merge-theta-data-and-combine-choice}

#  Ghost Data
slch2_ghost_choice_df <- merge_theta_and_behavioral_data("cing", "SLCH002", sl02_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")
bjh16_ghost_choice_df <- merge_theta_and_behavioral_data("cing", "BJH016", bjh16_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")
ll10_ghost_choice_df <- merge_theta_and_behavioral_data("cing", "LL10", ll10_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")


# No Ghost Data
slch2_no_ghost_choice_df <- merge_theta_and_behavioral_data("cing", "SLCH002", sl02_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")
bjh16_no_ghost_choice_df <- merge_theta_and_behavioral_data("cing", "BJH016", bjh16_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")
ll10_no_ghost_choice_df <- merge_theta_and_behavioral_data("cing", "LL10", ll10_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")

# Bind together
choice_ghost_df <- rbind(slch2_ghost_choice_df %>% mutate(subject = "SLCH002"),
                  bjh16_ghost_choice_df %>% mutate(subject = "BJH016"),
                  ll10_ghost_choice_df %>% mutate(subject = "LL10"))

choice_no_ghost_df <- rbind(slch2_no_ghost_choice_df %>% mutate(subject = "SLCH002"),
                  bjh16_no_ghost_choice_df %>% mutate(subject = "BJH016"),
                  ll10_no_ghost_choice_df %>% mutate(subject = "LL10"))

# save #
write_csv(choice_ghost_df, path(here(), "results", "theta", "theta_behavior_ac_choice_all_subs_ghost.csv"))
write_csv(choice_no_ghost_df, path(here(), "results", "theta", "theta_behavior_ac_choice_all_subs_noghost.csv"))

```


```{r amyg-merge-theta-data-and-combine-choice}

#  Ghost Data
slch2_ghost_choice_df <- merge_theta_and_behavioral_data("amygdala", "SLCH002", sl02_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")
bjh16_ghost_choice_df <- merge_theta_and_behavioral_data("amygdala", "BJH016", bjh16_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")
ll10_ghost_choice_df <- merge_theta_and_behavioral_data("amygdala", "LL10", ll10_data_distance, timepoints = 81,
                                                  keyword_include = "choice_locked_ghost", keyword_exclude = "none")


# No Ghost Data
slch2_no_ghost_choice_df <- merge_theta_and_behavioral_data("amygdala", "SLCH002", sl02_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")
bjh16_no_ghost_choice_df <- merge_theta_and_behavioral_data("amygdala", "BJH016", bjh16_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")
ll10_no_ghost_choice_df <- merge_theta_and_behavioral_data("amygdala", "LL10", ll10_data_distance_no_ghost, timepoints = 81,
                                                  keyword_include = "choice_locked_noghost", keyword_exclude = "none")

# Bind together
choice_ghost_df <- rbind(slch2_ghost_choice_df %>% mutate(subject = "SLCH002"),
                  bjh16_ghost_choice_df %>% mutate(subject = "BJH016"),
                  ll10_ghost_choice_df %>% mutate(subject = "LL10"))

choice_no_ghost_df <- rbind(slch2_no_ghost_choice_df %>% mutate(subject = "SLCH002"),
                  bjh16_no_ghost_choice_df %>% mutate(subject = "BJH016"),
                  ll10_no_ghost_choice_df %>% mutate(subject = "LL10"))

# save #
write_csv(choice_ghost_df, path(here(), "results", "theta", "theta_behavior_amyg_choice_all_subs_ghost.csv"))
write_csv(choice_no_ghost_df, path(here(), "results", "theta", "theta_behavior_amyg_choice_all_subs_noghost.csv"))

```
