---
title: "J6-J7 Theta Power"
output: html_document
date: '2022-08-11'
---

## SLCH002

```{r SLCH002-data-load}

sl02_data <- read_csv(path(here(), './data/ieeg_behave/SLCH002_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


```

```{r SLCH002-data-prep}


# clean Biscuits #
sl02_data_clean <- sl02_data %>%
  rename(subject = Subject) %>%
  # ungrouped timing variables
  rename(sample = Time) %>%
  mutate(Time = sample /2000) %>%
  mutate(time_step = c(FALSE, diff(Time))) %>%
  mutate(trial_numeric = as.numeric(gsub("Trial_", "", Trial))) %>%
  ## grouped by trial variables
  group_by(subject, Trial) %>%
  mutate(jittered_start_location = first(UserLocation)) %>%
  mutate(base_start_location = if_else(TrialType %in% c(16, 8), 30,
                                       if_else(TrialType %in% c(19, 15, 14, 7, 6), 50,
                                               if_else(TrialType %in% c(20, 13, 5), 70,
                                                   if_else(TrialType %in% c(17, 12, 4), 110,
                                                       if_else(TrialType %in% c(18, 11, 10, 3, 2), 130,
                                                               if_else(TrialType %in% c(9, 1), 150, 999))))))) %>%
  # get correct trial type info (sometimes trial type switches early/ lags)
  mutate(TrialType = as.numeric(names(sort(table(TrialType),decreasing=TRUE))[1])) %>%
  # same deal with lives
  mutate(Lives = as.numeric(names(sort(table(Lives),decreasing=TRUE))[1])) %>%
  # biscuit location
  mutate(Biscuit1 = if_else(Biscuit1 == FALSE & base_start_location <= 80,  base_start_location + 12, 
                            if_else(Biscuit1 == FALSE & base_start_location > 80, base_start_location -12, 1111)))  %>%
  mutate(Biscuit2 = if_else(Biscuit2 == FALSE & base_start_location <= 80,  base_start_location + 22, 
                            if_else(Biscuit2 == FALSE & base_start_location > 80, base_start_location -22, 1111)))  %>%
  mutate(Biscuit3 = if_else(Biscuit3 == FALSE & base_start_location <= 80,  base_start_location + 32, 
                            if_else(Biscuit3 == FALSE & base_start_location > 80, base_start_location -32, 1111)))  %>%
  mutate(Biscuit4 = if_else(Biscuit4 == FALSE & base_start_location <= 80,  base_start_location + 42, 
                            if_else(Biscuit4 == FALSE & base_start_location > 80, base_start_location -42, 1111)))  %>%
  mutate(Biscuit5 = if_else(Biscuit5 == FALSE & base_start_location <= 80,  base_start_location + 52, 
                            if_else(Biscuit5 == FALSE & base_start_location > 80, base_start_location -52, 1111)))  %>%
  # get starting side
  mutate(starting_side = if_else(base_start_location < 95, "Left", "Right")) %>%
  # trial timing information
  mutate(Trial = if_else(Trial_on_off == 0, "ITI", Trial)) %>%
  mutate_cond(Trial == "ITI", 
              GhostLocation = NA, UserLocation = NA, Lives = NA, starting_side = NA,
              Biscuit1 = NA, Biscuit2 = NA, Biscuit3 = NA, Biscuit4 = NA, Biscuit5 = NA, 
              Attack = NA, Chase = NA, Eaten = NA, TrialType = NA) %>%
  mutate(trial_time = if_else(Trial == "ITI", 999, Time - first(Time))) %>%
  mutate(trial_flip = 1:n()) %>%
  mutate(time_lag = c(FALSE, diff(trial_time))) %>%
  mutate(trial_end = as.numeric(c(diff(trial_numeric) > 0, FALSE))) %>%
  mutate(trial_length = max(trial_time)) %>%
  # trial grouping variables
  mutate(reward_groups = if_else(TrialType %in% c(1, 5, 9, 13), 2, 
                                 if_else(TrialType %in% c(2, 6, 10, 14), 3, 
                                         if_else(TrialType %in% c(3, 7, 11, 15), 1, 
                                                 if_else(TrialType %in% c(4, 8, 12, 16), 4, 99))))) %>%
  mutate(ghost_start_dir = if_else(TrialType > 16, "no_ghost", 
                                   if_else(TrialType <= 4 | TrialType >= 13, "away", "towards"))) %>%
  mutate(rewards_direction_groups = paste0(reward_groups, "_", ghost_start_dir)) %>%
  mutate(attack_chase_bob = if_else(Attack == T, "Attack", if_else(Chase == T, "Chase", "Bob"))) %>%
  ungroup() %>%
  group_by(subject) %>%
  arrange(subject, trial_numeric) %>%
  mutate(life_change = as.numeric(c(diff(Score) < 0, FALSE))) %>%
  group_by(subject, Trial) %>%
  mutate(died = sum(life_change)) %>%
  select(-life_change) %>%
  ungroup()

# get rid of paused trials  don't think they exist for this subject#
# sl02_paused_trials <- sl02_data_clean %>%
#   filter(ghost_start_dir != "no_ghost" & Trial != "ITI") %>%
#   group_by(Trial) %>%
#   mutate(ghost_step = c(FALSE, diff(GhostLocation))) %>%
#   mutate(user_step = c(FALSE, diff(UserLocation))) %>%
#   filter(ghost_step == 0 & user_step == 0) %>%
#   filter(c(0, diff(trial_flip)) == 1)
# 
# 
# pilot_game_data_clean <- pilot_game_data_clean %>%
#   ungroup() %>%
#    mutate(trial_ids = paste0(subject, "_", trial_numeric)) %>%
#   filter(!trial_ids %in% paused_trials)
 
sl02_data_distance <- sl02_data_clean %>%
  filter(Trial != "ITI") %>%
  filter(!is.na(GhostLocation)) %>%
  # filter(died == 0) %>%
  group_by(subject, Trial) %>%
  # user movement and distance measures
  mutate(distance_to_ghost = abs(GhostLocation - UserLocation)) %>%
  mutate(min_distance = min(distance_to_ghost)) %>%
  mutate(towards_ghost = if_else(Direction == 2 & GhostLocation < UserLocation, "Towards",  # Left:2 Right :11
                                 if_else(Direction == 11 & GhostLocation > UserLocation, "Towards",
                                         if_else(Direction == 4, "Still", "Away")))) %>%
  mutate(away_choice_tmp = c(0, diff(factor(towards_ghost)))) %>%
  mutate(away_choice = if_else( (away_choice_tmp == -2 & towards_ghost == "Away") | 
                                  (away_choice_tmp == -1 & towards_ghost == "Away"), distance_to_ghost, 0)) %>%
  select(-away_choice_tmp) %>%
  mutate(number_of_runs = sum(away_choice > 0, na.rm = T)) %>%
  mutate(last_away = if_else(number_of_runs == 0, 0, last(away_choice[away_choice > 0]) )) %>%
  ungroup()


sl02_all_vars_df <- sl02_data_clean %>%
  group_by(subject) %>%
  filter(!is.na(Score)) %>%
  filter(Trial != "ITI") %>%
  filter(Trial != 0) %>%
  # calculate number of deaths
  mutate(death_check = as.numeric(c(diff(Score) < 0, FALSE))) %>%
  mutate(total_deaths = sum(death_check)) %>%
  mutate(max_trial = max(trial_numeric)) %>%
  mutate(trial_in_block = trial_numeric %% 20) %>%
  mutate(trial_in_block = if_else(trial_in_block == 0, 20, trial_in_block)) %>%
  # new minigame
  mutate(lives_check = as.numeric(c(diff(Lives) > 0, FALSE))) %>%
  mutate(total_games = sum(lives_check) + 1) %>%
  group_by(subject, Trial) %>%
  mutate(dots_eaten = max(Eaten)) %>%
  mutate(max_score = max(Score, na.rm = T)) %>%
  mutate(trial_died = sum(death_check)) %>%
  mutate(last_trial_in_minigame = sum(lives_check)) %>% # if lose all lives, mark as last trial
  mutate(last_trial_in_minigame = if_else(trial_in_block == 20, 1, last_trial_in_minigame)) %>% # 20 is always last trial 
  group_by(subject) %>%
  mutate(average_score = mean(max_score)) %>%
  mutate(max_time = max(Time)) %>%
  select(subject, Trial, trial_numeric, trial_in_block, TrialType, trial_length,
         trial_died, last_trial_in_minigame, Lives, dots_eaten,
         max_trial, total_deaths, average_score, max_time) %>%
  distinct()

# get trials in minigame
round <- 1
game <- 1
sl02_all_vars_df$trial_in_minigame <- 0
sl02_all_vars_df$minigame <- 0
for(idx in 1:nrow(sl02_all_vars_df)){
  # add to df
  sl02_all_vars_df$trial_in_minigame[idx] <- round
  sl02_all_vars_df$minigame[idx] <- game
  if(sl02_all_vars_df$last_trial_in_minigame[idx] == 1){
    round <- 1
    game <- game + 1
  } else {
    round <- round + 1
  }
  
  if(sl02_all_vars_df$subject[idx + 1] != sl02_all_vars_df$subject[idx] & idx != nrow(sl02_all_vars_df)) {
    round <- 1
    game <- 1
  }
  
}

# max trials in minigame and such
sl02_all_vars_df <- sl02_all_vars_df %>%
  group_by(subject) %>%
  mutate(longest_minigame = max(trial_in_minigame)) %>%
  mutate(longest_minigame_under20 = max(trial_in_minigame[trial_in_minigame < 20])) %>%
  mutate(number_of_minigames = max(minigame)) %>%
  mutate(block = ceiling(trial_numeric/20)) %>%
  group_by(subject, block) %>%
  mutate(block_deaths = sum(trial_died)) %>%
  mutate(average_dots_per_block = mean(dots_eaten)) %>%
  ungroup()
  

```


```{r trials-no-biscuits}


sl02_data_clean %>%
  filter(Trial != "ITI") %>%
  group_by(trial_numeric) %>%
  mutate(total_eaten = max(Eaten)) %>%
  filter(total_eaten == 0) %>%
  pivot_longer(cols = c(GhostLocation, UserLocation), values_to = "location", names_to = "unit") %>%
  ggplot(., aes(x = trial_flip, y = location, color = unit)) +
  geom_hline(yintercept = 170, color = "black") +
  geom_hline(yintercept = 10, color = "black") +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~trial_numeric)

no_biscuits_trials <- sl02_data_clean %>%
  filter(Trial != "ITI") %>%
  group_by(trial_numeric) %>%
  mutate(total_eaten = max(Eaten)) %>%
  select(trial_numeric, total_eaten) %>%
  distinct() %>%
  filter(total_eaten == 0) %>%
  mutate(neural_trial_numeric = trial_numeric - 1) %>%
  # exclude fake trial 0 
  filter(neural_trial_numeric >= 0) %>%
  ungroup() %>%
  select(neural_trial_numeric)



```



```{r compile-bad-trials}

# bad_trials <- rbind(pasued_trials, no_biscuits_trials)

bad_trials <- no_biscuits_trials

write_csv(bad_trials, path(here(), './data/ieeg_behave/SLCH002_bad_trials.csv'))

```


```{r last-away}

last_away_events <- read_csv(path(here(), './data/ieeg_behave/SLCH002_last_away_events.csv'))



```

```{r bad-epochs}

good_epochs <- c(0,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 22,
 23,
 24,
 25,
 26,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 49,
 50,
 51,
 54,
 55,
 56,
 57,
 60,
 61,
 62,
 64,
 65,
 66,
 67,
 68,
 71,
 72,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 87,
 88,
 91,
 92,
 96,
 97,
 98,
 100,
 101,
 102,
 103,
 104,
 106,
 107,
 108,
 109,
 110,
 111,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 125,
 126,
 127,
 128,
 129,
 130,
 133,
 134,
 135,
 136,
 137,
 138,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220)

good_epochs <- good_epochs + 1

good_last_away_events <- last_away_events[good_epochs, ]

good_last_away_events_ghost <- good_last_away_events %>%
  mutate(neural_trial_numeric = trial_numeric - 1) %>%
  filter(TrialType <= 16)


```

```{r}

theta_power <- read_csv('../data/trial_theta_power_elec_J6_J7_SLCH002.csv', col_names = FALSE)
theta_power<- theta_power[, 3000:7000]
theta_power <- theta_power %>%
  mutate(neural_trial_numeric = good_last_away_events_ghost$neural_trial_numeric)

single_trial_theta <- theta_power %>%
  filter(neural_trial_numeric == 17)


sl02_data_distance_theta <- sl02_data_distance %>%
  mutate(neural_trial_numeric = trial_numeric - 1) %>%
  filter(!neural_trial_numeric %in% bad_trials$neural_trial_numeric) %>%
  filter(neural_trial_numeric %in% good_last_away_events_ghost$neural_trial_numeric) %>%
  filter(died == 0)

single_trial_distance <- sl02_data_distance_theta %>%
  filter(neural_trial_numeric == 17)

```
