---
title: "Slices of Trials ~ Theta ~ HC"
output: html_document
date: '2022-10-24'
---
---
title: "Trial Theta ~ SLCH002"
output: html_document
date: '2022-09-11'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lmerTest)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(effectsize)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)



```




## SLCH002

```{r SLCH002-data-load}

sl02_data <- read_csv(path(here(), './data/ieeg_behave/SLCH002_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


```

```{r SLCH002-data-prep}


# clean df #
sl02_data_clean <- clean_bci_data(sl02_data, 2000)

# create distance df # 
sl02_data_distance <- create_distance_df_bci(sl02_data_clean)

# round trial time to match theta analyses #
sl02_data_distance <- sl02_data_distance %>%
    mutate(trial_time = as.character(round(trial_time, 3)))
  


```


## Hippocampus

```{r exploartion}

shift <- 0
file <- "K7-K8_trial_theta.csv"
elec_theta_data <- read_csv(path(here(), "data", "theta_csvs", "hc", "SLCH002", file))

 # fix col names
elec_theta_data <- elec_theta_data %>%
  select(-X1)
colnames(elec_theta_data) <- c(paste0("bin_", colnames(elec_theta_data)[1:181]), 'trial_numeric')

# pivot
elec_theta_data <- elec_theta_data %>%
  pivot_longer(names_to = 'bin', values_to = 'theta', cols = starts_with("bin")) %>%
  mutate(bin = as.numeric(gsub("bin_", "", bin))) %>%
  mutate(bin = paste0("bin_", if_else(bin - shift > -1, bin - shift, 999))) %>%
  filter(bin != "bin_999") %>%
  mutate(trial_numeric = trial_numeric + 1) %>%
  mutate(trial_time = .05 * as.numeric(gsub("bin_", "", bin))) %>% 
  mutate(trial_time = as.character(round(trial_time, 3)))  %>% 
  select(-bin)
  

# merge 
elec_full_data <- inner_join(elec_theta_data, sl02_data_distance)

elec_full_data <- elec_full_data %>%
   mutate(trial_numeric = factor(trial_numeric))

# 1 sec data 
elec_sec_data <- elec_full_data %>%
  filter(trial_time == 1)

# grouped data
elec_group_data <- elec_full_data %>%
  group_by(trial_numeric) %>%
  mutate(discrete_distance_ghost = ntile(distance_to_ghost, 20)) %>%
  group_by(trial_numeric, discrete_distance_ghost, towards_ghost) %>%
  mutate(grouped_theta = mean(theta)) %>%
  ungroup() %>%
  select(trial_numeric, discrete_distance_ghost, grouped_theta, towards_ghost) %>%
  distinct()

## Models

# threat, time covariate model
threat_model <- lmerTest::lmer(theta ~ distance_to_ghost +
                           UserLocation + GhostLocation + Direction + Time +
                          (1|trial_numeric), data = elec_full_data)
print(summary(threat_model))

# threat, discrete ghost
discrete_theta_model <- lmerTest::lmer(grouped_theta ~ discrete_distance_ghost*towards_ghost +
                          (1|trial_numeric), data = elec_group_data)
print(summary(discrete_theta_model))


elec_full_data %>%
  ggplot(., aes(x = distance_to_ghost)) +
  geom_histogram(binwidth = 1, color = "black", alpha = .7) +
  geom_vline(xintercept = 73, color = "black") +
  theme(panel.background = element_rect(fill = "white"))

```

```{r}

elec_group_data %>%
  filter(towards_ghost != "Still") %>%
  ggplot(., aes(x = factor(discrete_distance_ghost), fill= towards_ghost, y = grouped_theta)) +
  geom_boxplot(notch = T) +
  theme(panel.background = element_rect(fill = "white"))

```


```{r rolling-regression-model}

shift <- 0
hc_elecs <- list.files(path(here(), "data", "theta_csvs", "hc", "SLCH002"))

slchool2_trial_theta_results <- tibble()
for(file in hc_elecs){

  print(file)
  
  elec_theta_data <- read_csv(path(here(), "data", "theta_csvs", "hc", "SLCH002", file))
  
   # fix col names
  elec_theta_data <- elec_theta_data %>%
    select(-X1)
  colnames(elec_theta_data) <- c(paste0("bin_", colnames(elec_theta_data)[1:181]), 'trial_numeric')
  
  # pivot
  elec_theta_data <- elec_theta_data %>%
    pivot_longer(names_to = 'bin', values_to = 'theta', cols = starts_with("bin")) %>%
    mutate(bin = as.numeric(gsub("bin_", "", bin))) %>%
    mutate(bin = paste0("bin_", if_else(bin - shift > -1, bin - shift, 999))) %>%
    filter(bin != "bin_999") %>%
    mutate(trial_numeric = trial_numeric + 1) %>%
    mutate(trial_time = .05 * as.numeric(gsub("bin_", "", bin))) %>% 
    mutate(trial_time = as.character(round(trial_time, 3)))  %>% 
    select(-bin)
    
  
  # merge 
  elec_full_data <- inner_join(elec_theta_data, sl02_data_distance)
  
  elec_full_data <- elec_full_data %>%
     mutate(trial_numeric = factor(trial_numeric))


  elec_full_data_sec <- elec_full_data %>%
    filter(trial_time != 0 & trial_time < 2)
  
  time_vec <- c()
  p_val <- c()
  for(time_tmp in unique(elec_full_data_sec$trial_time)){
    
    # 1 sec data 
    elec_sec_data <- elec_full_data %>%
      filter(towards_ghost == "Towards") %>%
      filter(trial_time == time_tmp)
    
    # threat, 1 second model
    # threat_sec_model <- lm(theta ~ sample(elec_sec_data$distance_to_ghost, length(elec_sec_data$distance_to_ghost)) +
    #                            UserLocation + GhostLocation, data = elec_sec_data)
    
    if(nrow(elec_sec_data) > 20){
    
    threat_sec_model <- lm(theta ~ distance_to_ghost +
                               UserLocation + GhostLocation, data = elec_sec_data)
    tmp <- summary(threat_sec_model)
    
    time_vec <- c(time_vec, time_tmp)
    p_val <- c(p_val, tmp$coefficients[3, 4])
    
    }
    
  }
  
  
  time_reg_df <- tibble("time" = time_vec, "p_val" = p_val)
  
  
  plot_tmp <- time_reg_df %>%
    filter(!is.na(p_val)) %>%
    mutate(time = as.numeric(time)) %>%
    ggplot(., aes(x = time, y = p_val)) +
    geom_line() +
    geom_hline(yintercept = .05, color = "black") +
    theme(panel.background = element_rect(fill = "white")) +
    ggtitle(file)
  
  print(plot_tmp)

}
```

```{r theta-eda}

elec_full_data_all_elecs %>%
  ggplot(., aes(x = as.numeric(trial_time), y = theta)) +
  geom_point(alpha =  .4) +
  theme(panel.background = element_rect(fill= "white")) +
  facet_wrap(~electrode)


elec_full_data_all_elecs %>%
  ggplot(., aes(x =  theta)) +
  geom_histogram(binwidth = .05,  alpha =  .7) +
  theme(panel.background = element_rect(fill= "white")) +
  facet_wrap(~electrode)


```



```{r lme-olling-model}

time_vec <- c()
p_val <- c()

elec_rolling_data_all_elecs <-  elec_full_data_all_elecs %>%
    filter(trial_time != 0 & trial_time < 3)

for(time_tmp in unique(elec_rolling_data_all_elecs$trial_time)){
  
  # 1 sec data 
  elec_sec_data <- elec_rolling_data_all_elecs %>%
    # filter(towards_ghost == "Towards") %>%
    filter(trial_time == time_tmp) %>%
    ungroup()
  
  # threat, 1 second model
  # threat_sec_model <- lm(theta ~ sample(elec_sec_data$distance_to_ghost, length(elec_sec_data$distance_to_ghost)) +
  #                            UserLocation + GhostLocation, data = elec_sec_data)
  
  if(nrow(elec_sec_data) > 20){
  
    threat_rollling_model_all_elecs <- lmerTest::lmer(theta ~ towards_ghost +
                             UserLocation + GhostLocation +
                             (1|electrode), data = elec_sec_data, REML = F)
    
    tmp <- summary(threat_rollling_model_all_elecs)
    
    time_vec <- c(time_vec, time_tmp)
    p_val <- c(p_val, tmp$coefficients[2, 5])
  
  }
  
}


time_reg_df <- tibble("time" = time_vec, "p_val" = p_val)

time_reg_df %>%
    filter(!is.na(p_val)) %>%
    mutate(time = as.numeric(time)) %>%
    ggplot(., aes(x = time, y = p_val)) +
    geom_line() +
    geom_hline(yintercept = .05, color = "black") +
    theme(panel.background = element_rect(fill = "white")) 
```




```{r hc-elecs}

# shift <- 20
shift <- 0
hc_elecs <- list.files(path(here(), "data", "theta_csvs", "hc", "SLCH002"))

slchool2_trial_theta_results <- tibble()
for(file in hc_elecs){

  print(file)
  
  elec_theta_data <- read_csv(path(here(), "data", "theta_csvs", "hc", "SLCH002", file))
  
   # fix col names
  elec_theta_data <- elec_theta_data %>%
    select(-X1)
  colnames(elec_theta_data) <- c(paste0("bin_", colnames(elec_theta_data)[1:181]), 'trial_numeric')
  
  # pivot
  elec_theta_data <- elec_theta_data %>%
    pivot_longer(names_to = 'bin', values_to = 'theta', cols = starts_with("bin")) %>%
    mutate(bin = as.numeric(gsub("bin_", "", bin))) %>%
    mutate(bin = paste0("bin_", if_else(bin - shift > -1, bin - shift, 999))) %>%
    filter(bin != "bin_999") %>%
    mutate(trial_numeric = trial_numeric + 1) %>%
    mutate(trial_time = .05 * as.numeric(gsub("bin_", "", bin))) %>% 
    mutate(trial_time = as.character(round(trial_time, 3)))  %>% 
    select(-bin)
    
  
  # merge 
  elec_full_data <- inner_join(elec_theta_data, sl02_data_distance)
  
  elec_full_data <- elec_full_data %>%
     mutate(trial_numeric = factor(trial_numeric))
 
  
  ## Basic models
  
  # threat model
  threat_model <- lmerTest::lmer(theta ~ distance_to_ghost +
                             UserLocation + GhostLocation + Direction + 
                            (1|trial_numeric), data = elec_full_data)
  print(summary(threat_model))
  summary_model <- summary(threat_model) 
  
  tmp <- as_tibble(summary_model$coefficients) %>%
    mutate(model = "threat") %>%
    mutate(file = file)%>%
    mutate(predictor = rownames(summary_model$coefficients))
  
  slchool2_trial_theta_results <- rbind(slchool2_trial_theta_results, tmp)  
  
  # aac model
  aac_model <- lmerTest::lmer(theta ~ towards_ghost +
                             UserLocation + GhostLocation + 
                            (1|trial_numeric), data = elec_full_data)
  print(summary(aac_model))
  summary_model <- summary(aac_model) 
  
  tmp <- as_tibble(summary_model$coefficients) %>%
    mutate(model = "aac") %>%
    mutate(file = file)%>%
    mutate(predictor = rownames(summary_model$coefficients))
  
  slchool2_trial_theta_results <- rbind(slchool2_trial_theta_results, tmp)  
  
  # reward model
  reward_model <- lmerTest::lmer(theta ~ discounted_reward +
                             UserLocation + GhostLocation + Direction + 
                            (1|trial_numeric), data = elec_full_data)
  print(summary(reward_model))
  summary_model <- summary(reward_model) 
  
  tmp <- as_tibble(summary_model$coefficients) %>%
    mutate(model = "reward") %>%
    mutate(file = file)%>%
    mutate(predictor = rownames(summary_model$coefficients))
  
  slchool2_trial_theta_results <- rbind(slchool2_trial_theta_results, tmp)  
  
  ## Interaction
  
  ## threat, aac
  threat_aac_model <- lmerTest::lmer(theta ~ distance_to_ghost*towards_ghost +
                             UserLocation + GhostLocation + 
                            (1|trial_numeric), data = elec_full_data)
  print(summary(threat_aac_model))
  summary_model <- summary(threat_aac_model) 
  
  tmp <- as_tibble(summary_model$coefficients) %>%
    mutate(model = "threat_aac") %>%
    mutate(file = file)%>%
    mutate(predictor = rownames(summary_model$coefficients))
  
  slchool2_trial_theta_results <- rbind(slchool2_trial_theta_results, tmp)  
  
  ## reward, aac
  reward_aac_model <- lmerTest::lmer(theta ~ discounted_reward*towards_ghost +
                             UserLocation + GhostLocation +
                            (1|trial_numeric), data = elec_full_data)
  print(summary(reward_aac_model))  
  summary_model <- summary(reward_aac_model) 
  
  tmp <- as_tibble(summary_model$coefficients) %>%
    mutate(model = "reward_aac") %>%
    mutate(file = file)%>%
    mutate(predictor = rownames(summary_model$coefficients))
  
  slchool2_trial_theta_results <- rbind(slchool2_trial_theta_results, tmp)  
  
  # full model
  full_model <- lmerTest::lmer(theta ~ distance_to_ghost + towards_ghost + discounted_reward +
                             UserLocation + GhostLocation + 
                               (1|trial_numeric), data = elec_full_data)
  print(summary(full_model))
  summary_model <- summary(full_model) 
  
  tmp <- as_tibble(summary_model$coefficients) %>%
    mutate(model = "full") %>%
    mutate(file = file) %>%
    mutate(predictor = rownames(summary_model$coefficients))
  
  slchool2_trial_theta_results <- rbind(slchool2_trial_theta_results, tmp)
  
  
  # fullish model
  fullish_model <- lmerTest::lmer(theta ~ distance_to_ghost + discounted_reward +
                             UserLocation + GhostLocation + 
                               (1|trial_numeric), data = elec_full_data)
  print(summary(fullish_model))
  summary_model <- summary(fullish_model) 
  
  tmp <- as_tibble(summary_model$coefficients) %>%
    mutate(model = "fullish") %>%
    mutate(file = file) %>%
    mutate(predictor = rownames(summary_model$coefficients))
  
  slchool2_trial_theta_results <- rbind(slchool2_trial_theta_results, tmp)
    


}

```


```{r effect-eda}

# distance to ghost is similar 


# # plot
# elec_before_turn %>%
#   select(distance_to_ghost, theta, trial_time, trial_numeric) %>%
#   # filter(trial_numeric < 50) %>%
#   ggplot(., aes(x = distance_to_ghost, y = theta, color = trial_time)) +
#   geom_point(size = 2, alpha = .7) +
#   geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
#   theme(panel.background = element_rect(fill = "white")) +
#   scale_color_viridis_b() +
#   facet_wrap(~trial_numeric)



# # plot
elec_full_data %>%
  # select(distance_to_ghost, theta, trial_time, trial_numeric) %>%
  # filter(trial_numeric == 216) %>%
  filter(trial_numeric %in% c(6, 84, 219)) %>%
  ggplot(., aes(x = distance_to_ghost, y = theta)) +
  geom_point(size = 3, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Distance to Ghost") +
  scale_color_viridis_b() +
  facet_wrap(~trial_numeric)

# # plot
elec_full_data %>%
  # select(distance_to_ghost, theta, trial_time, trial_numeric) %>%
  # filter(trial_numeric == 216) %>%
  filter(trial_numeric %in% sample(trial_numeric, 20)) %>%
  ggplot(., aes(x = distance_to_ghost, y = theta)) +
  geom_point(size = 3, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Distance to Ghost") +
  scale_color_viridis_b() +
  facet_wrap(~trial_numeric)

elec_full_data_all_elecs %>%
  filter(electrode == "J4-J5_trial_theta.csv") %>% # 6, 111, 140
  filter(trial_numeric %in% c(83, 153, 190)) %>%
  ggplot(., aes(x = distance_to_ghost, y = theta)) +
  geom_point(size = 3, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Distance to Ghost") +
  scale_color_viridis_b() +
  facet_wrap(~trial_numeric) 

elec_full_data_all_elecs %>%
  filter(electrode == "J4-J5_trial_theta.csv") %>%
  filter(trial_numeric %in% sample(trial_numeric, 3)) %>%
  filter(towards_ghost != "Still") %>%
  ggplot(., aes(x = distance_to_ghost, color = towards_ghost, y = theta)) +
  geom_point(size = 4, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  facet_wrap(~trial_numeric)


```


```{r}
  
# # plot
elec_full_data %>%
  # select(distance_to_ghost, theta, trial_time, trial_numeric) %>%
  # filter(trial_numeric == 216) %>%
  filter(trial_numeric %in% c(6, 84, 219)) %>%
  ggplot(., aes(x = discounted_reward, y = theta)) +
  geom_point(size = 3, alpha = .7, color = "#87C8B7") +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', color = "#FCC673", alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Distance to Ghost") +
  facet_wrap(~trial_numeric)


elec_full_data %>%
  # select(distance_to_ghost, theta, trial_time, trial_numeric) %>%
  # filter(trial_numeric == 216) %>%
  filter(trial_numeric %in% sample(trial_numeric, 20)) %>%
  ggplot(., aes(x = distance_to_ghost, y = theta)) +
  geom_point(size = 3, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Discounted Reward") +
  scale_color_viridis_b() +
  facet_wrap(~trial_numeric)

```

```{r aac-model}

shift <- 0
hc_elecs <- list.files(path(here(), "data", "theta_csvs", "hc", "SLCH002"))

slchool2_trial_theta_results <- tibble()
elec_full_data_all_elecs <- NULL
for(file in hc_elecs){

  print(file)
  
  elec_theta_data <- read_csv(path(here(), "data", "theta_csvs", "hc", "SLCH002", file))
  
   # fix col names
  elec_theta_data <- elec_theta_data %>%
    select(-X1)
  colnames(elec_theta_data) <- c(paste0("bin_", colnames(elec_theta_data)[1:181]), 'trial_numeric')
  
  # pivot
  elec_theta_data <- elec_theta_data %>%
    pivot_longer(names_to = 'bin', values_to = 'theta', cols = starts_with("bin")) %>%
    mutate(bin = as.numeric(gsub("bin_", "", bin))) %>%
    mutate(bin = paste0("bin_", if_else(bin - shift > -1, bin - shift, 999))) %>%
    filter(bin != "bin_999") %>%
    mutate(trial_numeric = trial_numeric + 1) %>%
    mutate(trial_time = .05 * as.numeric(gsub("bin_", "", bin))) %>% 
    mutate(trial_time = as.character(round(trial_time, 3)))  %>% 
    select(-bin)
    
  
  # merge 
  elec_full_data <- inner_join(elec_theta_data, sl02_data_distance)
  
  elec_full_data <- elec_full_data %>%
     mutate(trial_numeric = factor(trial_numeric)) %>%
    mutate(electrode = file)
  
  # rbind
  elec_full_data_all_elecs <- rbind(elec_full_data_all_elecs, elec_full_data)

}

hc_threat_sig_elecs <- slchool2_trial_theta_results_clean %>%
  filter(sig == TRUE & model == "threat" & predictor == "distance_to_ghost") %>%
  pull(file) %>%
  unique()


# threat model
elec_full_data_all_elecs %>%
  filter(electrode %in% hc_threat_sig_elecs) %>%
  mutate(trial_id = paste0(electrode, "_", trial_numeric)) %>%
  filter(trial_numeric %in% sample(trial_numeric, 4)) %>%
  ggplot(., aes(x = distance_to_ghost, y = theta)) +
  geom_point(size = 3, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Distance to Ghost") +
  scale_color_viridis_b() +
  facet_wrap(~trial_id)

```

```{r reward-model, fig.height=8, fig.width=12}

hc_rewardt_sig_elecs <- slchool2_trial_theta_results_clean %>%
  filter(sig == TRUE & model == "reward" & predictor == "distance_to_ghost") %>%
  pull(file) %>%
  unique()


# reward model
elec_full_data_all_elecs %>%
  filter(electrode %in% hc_threat_sig_elecs) %>%
  mutate(trial_id = paste0(electrode, "_", trial_numeric)) %>%
  filter(trial_numeric %in% sample(trial_numeric, 6)) %>%
  ggplot(., aes(x = discounted_reward, y = theta)) +
  geom_point(size = 3, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Discounted Reward") +
  facet_wrap(~trial_id)


# reward model
elec_full_data_all_elecs %>%
  filter(electrode %in% hc_threat_sig_elecs) %>%
  filter(towards_ghost != "Still") %>%
  mutate(trial_id = paste0(electrode, "_", trial_numeric)) %>%
  filter(trial_numeric %in% sample(trial_numeric, 6)) %>%
  ggplot(., aes(x = discounted_reward, y = theta)) +
  geom_point(size = 3, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Discounted Reward") +
  facet_wrap(~trial_id)

```


```{r reward-aac}

# reward model
elec_full_data_all_elecs %>%
  filter(electrode %in% hc_threat_sig_elecs) %>%
  filter(towards_ghost == "Towards") %>%
  mutate(trial_id = paste0(electrode, "_", trial_numeric)) %>%
  filter(trial_numeric %in% sample(trial_numeric, 6)) %>%
  ggplot(., aes(x = discounted_reward, color = towards_ghost, y = theta)) +
  geom_point(size = 3, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Discounted Reward") +
  facet_wrap(~trial_id)


```

```{r}

elec_full_data_all_elecs %>%
  mutate(trial_id = paste0(electrode, "_", trial_numeric)) %>%
  filter(trial_numeric %in% sample(trial_numeric, 2)) %>%
  filter(towards_ghost != "Still") %>%
  ggplot(., aes(x = distance_to_ghost, color = towards_ghost, y = theta)) +
  geom_point(size = 4, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Distance to Ghost") +
  facet_wrap(~trial_id)


elec_full_data_all_elecs %>%
  filter(towards_ghost != "Still") %>%
  ungroup() %>%
  group_by(electrode) %>%
  mutate(pval = round(t.test(theta ~ towards_ghost)$p.value, 7)) %>%
  mutate(electrode = gsub("_trial_theta.csv", "", electrode)) %>%
  mutate(facet_title = paste0(electrode, ": ", pval)) %>%
  ggplot(., aes(x = towards_ghost, fill =towards_ghost, y = theta)) +
  geom_boxplot(notch = T) +
  theme(panel.background = element_rect(fill = "white"), legend.position = "none") +
  labs(y = "Theta Power", x = "Approaching or Avoiding Ghost") +
  facet_wrap(~facet_title, nrow = 2) +
  ggtitle("SLCH002 HC Electrode Theta Power by Approach/Avoid Behavior", subtitle = "T tests ran on each elec, p value rounded to the 7th decimal place")



elec_full_data_all_elecs %>%
  mutate(trial_id = paste0(electrode, "_", trial_numeric)) %>%
  filter(trial_numeric %in% sample(trial_numeric, 4)) %>%
  filter(towards_ghost == "Towards") %>%
  ggplot(., aes(x = distance_to_ghost, y = theta)) +
  geom_point(size = 4, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  labs(y = "Theta Power", x = "Distance to Ghost") +
  facet_wrap(~trial_id)


```


```{r across-electrodes}



# threat model
threat_model_all_elecs <- lmerTest::lmer(theta ~ distance_to_ghost +
                           UserLocation + GhostLocation + Direction + 
                          (1|trial_numeric) + (1|electrode), data = elec_full_data_all_elecs, REML = F)
print(summary(threat_model_all_elecs))


threat_model_all_elecs %>%
  broom::tidy() %>%
  kable(table.attr = "style = \"color: black;\"") %>%
  kable_styling() %>%
  add_header_above(c("SLCH002: LME Threat Model" = 8))


# aac model
aac_model_all_elecs <- lmerTest::lmer(theta ~ towards_ghost +
                           UserLocation + GhostLocation + 
                          (1|trial_numeric) + (1|electrode), data = elec_full_data_all_elecs, REML = F)
print(summary(aac_model_all_elecs))

aac_model_all_elecs %>%
  broom::tidy() %>%
  kable(table.attr = "style = \"color: black;\"") %>%
  kable_styling() %>%
  add_header_above(c("SLCH002: LME Apr/Av Model" = 8))

# reward model
reward_model_all_elecs <- lmerTest::lmer(theta ~ discounted_reward +
                           UserLocation + GhostLocation + Direction + 
                          (1|trial_numeric) + (1|electrode), data = elec_full_data_all_elecs, REML = F)
print(summary(reward_model_all_elecs))

reward_model_all_elecs %>%
  broom::tidy() %>%
  kable(table.attr = "style = \"color: black;\"") %>%
  kable_styling() %>%
  add_header_above(c("SLCH002: LME Reward Model" = 8))

## threat, aac
threat_aac_model_all_elecs <- lmerTest::lmer(theta ~ distance_to_ghost*towards_ghost +
                           UserLocation + GhostLocation + 
                          (1|trial_numeric) + (1|electrode), data = elec_full_data_all_elecs, REML = F)
print(summary(threat_aac_model_all_elecs))


## reward, aac
reward_aac_model_all_elecs <- lmerTest::lmer(theta ~ discounted_reward*towards_ghost +
                           UserLocation + GhostLocation + 
                          (1|trial_numeric) + (1|electrode), data = elec_full_data_all_elecs, REML = F)
print(summary(reward_aac_model_all_elecs))


## reward, aac
complete_model_all_elecs <- lmerTest::lmer(theta ~ discounted_reward*towards_ghost + distance_to_ghost*towards_ghost +
                           UserLocation + GhostLocation + 
                          (1|trial_numeric) + (1|electrode), data = elec_full_data_all_elecs, REML = F)
print(summary(complete_model_all_elecs))

complete_model_all_elecs %>%
  broom::tidy() %>%
  kable(table.attr = "style = \"color: black;\"") %>%
  kable_styling() %>%
  add_header_above(c("SLCH002: LME Full Model" = 8))


```


```{r model-results-hc}

slchool2_trial_theta_results_clean <- slchool2_trial_theta_results %>%
  mutate(sig = `Pr(>|t|)` < .05) %>%
  group_by(model, predictor) %>%
  mutate("Number of Sig. HC Elecs" = sum(sig)) %>%
  mutate("Average T" = mean(`t value`)) %>%
  mutate("Average Beta" = mean(Estimate)) %>%
  select(model, predictor, `Average Beta`, `Average T`, `Number of Sig. HC Elecs`) %>%
  distinct() %>%
  ungroup()



slchool2_trial_theta_results_clean %>%
  filter(model == "threat") %>%
  select(-model) %>%
  kable() %>%
  kable_styling() %>%
  add_header_above(c("Threat Model" = 4))


slchool2_trial_theta_results_clean %>%
  filter(model == "reward") %>%
  select(-model) %>%
  kable() %>%
  kable_styling() %>%
  add_header_above(c("Reward Model" = 4))


slchool2_trial_theta_results_clean %>%
  filter(model == "aac") %>%
  select(-model) %>%
  kable() %>%
  kable_styling() %>%
  add_header_above(c("AAC Model" = 4))

slchool2_trial_theta_results_clean %>%
  filter(model == "threat_aac") %>%
  select(-model) %>%
  kable() %>%
  kable_styling() %>%
  add_header_above(c("Threat + AAC Model" = 4))

slchool2_trial_theta_results_clean %>%
  filter(model == "reward_aac") %>%
  select(-model) %>%
  kable() %>%
  kable_styling() %>%
  add_header_above(c("Reward + AAC Model" = 4))

slchool2_trial_theta_results_clean %>%
  filter(model == "full") %>%
  select(-model) %>%
  kable() %>%
  kable_styling() %>%
  add_header_above(c("Fullest Model" = 4))

slchool2_trial_theta_results_clean %>%
  filter(model == "fullish") %>%
  select(-model) %>%
  kable() %>%
  kable_styling() %>%
  add_header_above(c("Hippocampus: Full Model" = 4))

```

