---
title: "Trial Theta"
output: html_document
date: '2022-09-11'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(effectsize)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)

```




## SLCH002

```{r SLCH002-data-load}

sl02_data <- read_csv(path(here(), './data/ieeg_behave/SLCH002_raw_behave.csv'), col_types = cols(X1 = col_double(),
                                                                                              Subject = col_character(),
                                                                                              Trial = col_character(),
                                                                                              Lives = col_double(),
                                                                                              Trial_on_off = col_double(),
                                                                                              TrialType = col_double(),
                                                                                              Time = col_double(),
                                                                                              GhostLocation = col_double(),
                                                                                              UserLocation = col_double(),
                                                                                              Direction = col_double(),
                                                                                              Biscuit1 = col_logical(),
                                                                                              Biscuit2 = col_logical(),
                                                                                              Biscuit3 = col_logical(),
                                                                                              Biscuit4 = col_logical(),
                                                                                              Biscuit5 = col_logical(),
                                                                                              Attack = col_logical(),
                                                                                              Chase = col_logical(),
                                                                                              Eaten = col_double(),
                                                                                              Score = col_double()))


```

```{r SLCH002-data-prep}


# clean Biscuits #
sl02_data_clean <- sl02_data %>%
  rename(subject = Subject) %>%
  # ungrouped timing variables
  rename(sample = Time) %>%
  mutate(Time = sample /2000) %>%
  mutate(time_step = c(FALSE, diff(Time))) %>%
  mutate(trial_numeric = as.numeric(gsub("Trial_", "", Trial))) %>%
  ## grouped by trial variables
  group_by(subject, Trial) %>%
  mutate(jittered_start_location = first(UserLocation)) %>%
  mutate(base_start_location = if_else(TrialType %in% c(16, 8), 30,
                                       if_else(TrialType %in% c(19, 15, 14, 7, 6), 50,
                                               if_else(TrialType %in% c(20, 13, 5), 70,
                                                   if_else(TrialType %in% c(17, 12, 4), 110,
                                                       if_else(TrialType %in% c(18, 11, 10, 3, 2), 130,
                                                               if_else(TrialType %in% c(9, 1), 150, 999))))))) %>%
  # get correct trial type info (sometimes trial type switches early/ lags)
  mutate(TrialType = as.numeric(names(sort(table(TrialType),decreasing=TRUE))[1])) %>%
  # same deal with lives
  mutate(Lives = as.numeric(names(sort(table(Lives),decreasing=TRUE))[1])) %>%
  # biscuit location
  mutate(Biscuit1 = if_else(Biscuit1 == FALSE & base_start_location <= 80,  base_start_location + 12, 
                            if_else(Biscuit1 == FALSE & base_start_location > 80, base_start_location -12, 1111)))  %>%
  mutate(Biscuit2 = if_else(Biscuit2 == FALSE & base_start_location <= 80,  base_start_location + 22, 
                            if_else(Biscuit2 == FALSE & base_start_location > 80, base_start_location -22, 1111)))  %>%
  mutate(Biscuit3 = if_else(Biscuit3 == FALSE & base_start_location <= 80,  base_start_location + 32, 
                            if_else(Biscuit3 == FALSE & base_start_location > 80, base_start_location -32, 1111)))  %>%
  mutate(Biscuit4 = if_else(Biscuit4 == FALSE & base_start_location <= 80,  base_start_location + 42, 
                            if_else(Biscuit4 == FALSE & base_start_location > 80, base_start_location -42, 1111)))  %>%
  mutate(Biscuit5 = if_else(Biscuit5 == FALSE & base_start_location <= 80,  base_start_location + 52, 
                            if_else(Biscuit5 == FALSE & base_start_location > 80, base_start_location -52, 1111)))  %>%
  # get starting side
  mutate(starting_side = if_else(base_start_location < 95, "Left", "Right")) %>%
  # trial timing information
  mutate(Trial = if_else(Trial_on_off == 0, "ITI", Trial)) %>%
  mutate_cond(Trial == "ITI", 
              GhostLocation = NA, UserLocation = NA, Lives = NA, starting_side = NA,
              Biscuit1 = NA, Biscuit2 = NA, Biscuit3 = NA, Biscuit4 = NA, Biscuit5 = NA, 
              Attack = NA, Chase = NA, Eaten = NA, TrialType = NA) %>%
  mutate(trial_time = if_else(Trial == "ITI", 999, Time - first(Time))) %>%
  mutate(trial_flip = 1:n()) %>%
  mutate(time_lag = c(FALSE, diff(trial_time))) %>%
  mutate(trial_end = as.numeric(c(diff(trial_numeric) > 0, FALSE))) %>%
  mutate(trial_length = max(trial_time)) %>%
  # trial grouping variables
  mutate(reward_groups = if_else(TrialType %in% c(1, 5, 9, 13), 2, 
                                 if_else(TrialType %in% c(2, 6, 10, 14), 3, 
                                         if_else(TrialType %in% c(3, 7, 11, 15), 1, 
                                                 if_else(TrialType %in% c(4, 8, 12, 16), 4, 99))))) %>%
  mutate(ghost_start_dir = if_else(TrialType > 16, "no_ghost", 
                                   if_else(TrialType <= 4 | TrialType >= 13, "away", "towards"))) %>%
  mutate(rewards_direction_groups = paste0(reward_groups, "_", ghost_start_dir)) %>%
  mutate(attack_chase_bob = if_else(Attack == T, "Attack", if_else(Chase == T, "Chase", "Bob"))) %>%
  ungroup() %>%
  group_by(subject) %>%
  arrange(subject, trial_numeric) %>%
  mutate(life_change = as.numeric(c(diff(Score) < 0, FALSE))) %>%
  group_by(subject, Trial) %>%
  mutate(died = sum(life_change)) %>%
  select(-life_change) %>%
  ungroup()

# get rid of paused trials  don't think they exist for this subject#
# sl02_paused_trials <- sl02_data_clean %>%
#   filter(ghost_start_dir != "no_ghost" & Trial != "ITI") %>%
#   group_by(Trial) %>%
#   mutate(ghost_step = c(FALSE, diff(GhostLocation))) %>%
#   mutate(user_step = c(FALSE, diff(UserLocation))) %>%
#   filter(ghost_step == 0 & user_step == 0) %>%
#   filter(c(0, diff(trial_flip)) == 1)
# 
# 
# pilot_game_data_clean <- pilot_game_data_clean %>%
#   ungroup() %>%
#    mutate(trial_ids = paste0(subject, "_", trial_numeric)) %>%
#   filter(!trial_ids %in% paused_trials)
 


sl02_data_distance <- sl02_data_clean %>%
  filter(Trial != "ITI") %>%
  filter(!is.na(GhostLocation)) %>%
  filter(died == 0) %>%
  group_by(trial_numeric) %>%
  # user movement and distance measures
  mutate(distance_to_ghost = abs(GhostLocation - UserLocation)) %>%
  mutate(min_distance = min(distance_to_ghost)) %>%
  mutate(towards_ghost = if_else(Direction == 2 & GhostLocation < UserLocation, "Towards",  # Left:2 Right :11
                                 if_else(Direction == 11 & GhostLocation > UserLocation, "Towards",
                                         if_else(Direction == 4, "Still", "Away")))) %>%
  mutate(away_choice_tmp = c(0, diff(factor(towards_ghost)))) %>%
  mutate(away_choice = if_else( (away_choice_tmp == -2 & towards_ghost == "Away") | 
                                  (away_choice_tmp == -1 & towards_ghost == "Away"), distance_to_ghost, 0)) %>%
  # select(-away_choice_tmp) %>%
  mutate(number_of_runs = sum(away_choice > 0, na.rm = T)) %>%
  mutate(last_away = if_else(number_of_runs == 0, 0, last(away_choice[away_choice > 0]) )) %>%
  ungroup()


sl02_all_vars_df <- sl02_data_clean %>%
  group_by(subject) %>%
  filter(!is.na(Score)) %>%
  filter(Trial != "ITI") %>%
  filter(Trial != 0) %>%
  # calculate number of deaths
  mutate(death_check = as.numeric(c(diff(Score) < 0, FALSE))) %>%
  mutate(total_deaths = sum(death_check)) %>%
  mutate(max_trial = max(trial_numeric)) %>%
  mutate(trial_in_block = trial_numeric %% 20) %>%
  mutate(trial_in_block = if_else(trial_in_block == 0, 20, trial_in_block)) %>%
  # new minigame
  mutate(lives_check = as.numeric(c(diff(Lives) > 0, FALSE))) %>%
  mutate(total_games = sum(lives_check) + 1) %>%
  group_by(subject, Trial) %>%
  mutate(dots_eaten = max(Eaten)) %>%
  mutate(max_score = max(Score, na.rm = T)) %>%
  mutate(trial_died = sum(death_check)) %>%
  mutate(last_trial_in_minigame = sum(lives_check)) %>% # if lose all lives, mark as last trial
  mutate(last_trial_in_minigame = if_else(trial_in_block == 20, 1, last_trial_in_minigame)) %>% # 20 is always last trial 
  group_by(subject) %>%
  mutate(average_score = mean(max_score)) %>%
  mutate(max_time = max(Time)) %>%
  select(subject, Trial, trial_numeric, trial_in_block, TrialType, trial_length,
         trial_died, last_trial_in_minigame, Lives, dots_eaten,
         max_trial, total_deaths, average_score, max_time) %>%
  distinct()

# get trials in minigame
round <- 1
game <- 1
sl02_all_vars_df$trial_in_minigame <- 0
sl02_all_vars_df$minigame <- 0
for(idx in 1:nrow(sl02_all_vars_df)){
  # add to df
  sl02_all_vars_df$trial_in_minigame[idx] <- round
  sl02_all_vars_df$minigame[idx] <- game
  if(sl02_all_vars_df$last_trial_in_minigame[idx] == 1){
    round <- 1
    game <- game + 1
  } else {
    round <- round + 1
  }
  
  if(sl02_all_vars_df$subject[idx + 1] != sl02_all_vars_df$subject[idx] & idx != nrow(sl02_all_vars_df)) {
    round <- 1
    game <- 1
  }
  
}

# max trials in minigame and such
sl02_all_vars_df <- sl02_all_vars_df %>%
  group_by(subject) %>%
  mutate(longest_minigame = max(trial_in_minigame)) %>%
  mutate(longest_minigame_under20 = max(trial_in_minigame[trial_in_minigame < 20])) %>%
  mutate(number_of_minigames = max(minigame)) %>%
  mutate(block = ceiling(trial_numeric/20)) %>%
  group_by(subject, block) %>%
  mutate(block_deaths = sum(trial_died)) %>%
  mutate(average_dots_per_block = mean(dots_eaten)) %>%
  ungroup()
  

```



```{r load-j5-j6-data}


j5j6_theta_data <- read_csv(path(here(), "data", "theta_csvs", "J5-J6_trial_theta.csv"))

# fix col names
j5j6_theta_data <- j5j6_theta_data %>%
  select(-X1)
colnames(j5j6_theta_data) <- c(paste0("bin_", colnames(j5j6_theta_data)[1:201]), 'trial_numeric')

# pivot
j5j6_theta_data <- j5j6_theta_data %>%
  pivot_longer(names_to = 'bin', values_to = 'theta', cols = starts_with("bin")) %>%
  mutate(trial_numeric = trial_numeric + 1) %>%
  mutate(trial_time = .05 * as.numeric(gsub("bin_", "", bin))) %>% 
  mutate(trial_time = as.character(round(trial_time, 3)))  %>% 
  select(-bin)
  

```


```{r merge-with-behave}

# fix issue with trial time
sl02_data_distance <- sl02_data_distance %>%
  mutate(trial_time = as.character(round(trial_time, 3)))

# merge 
j5j6_full_data <- inner_join(j5j6_theta_data, sl02_data_distance)

# only before last turn around, less total trials because excluding trials where pacman died
j5j6_before_turn <- j5j6_full_data %>%
  mutate(trial_time = as.numeric(trial_time)) %>%
  # get rid of no ghost
  filter(TrialType <= 16) %>%
  # filter out anything after last away
  group_by(trial_numeric) %>%
  filter(trial_time <= max(trial_time[away_choice == last_away])) %>%
  ungroup() %>%
  mutate(trial_numeric = factor(trial_numeric))

# plot
j5j6_before_turn %>%
  select(distance_to_ghost, theta, trial_time, trial_numeric) %>%
  # filter(trial_numeric < 50) %>%
  ggplot(., aes(x = distance_to_ghost, y = theta, color = trial_time)) +
  geom_point(size = 2, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_viridis_b() +
  facet_wrap(~trial_numeric)

```

```{r regression, eval = F}

model1 <- lmer(theta ~ distance_to_ghost + UserLocation + jittered_start_location + reward_groups +(1|trial_numeric), data = j5j6_before_turn)

summary(model1)
effectsize(model1)

t <- -5.006
n <- 5312
p_val <- 2*pt(-abs(t),df=n-1)


plot(model1)



qqnorm(model1, ~ranef(., level=2))
```


```{r other-elecs}
threat_function <- distributions3::Beta(2, 5.5)

hc_elecs <- list.files(path(here(), "data", "theta_csvs"))

for(file in hc_elecs){

  print(file)
  
  elec_theta_data <- read_csv(path(here(), "data", "theta_csvs", file))
  
  # fix col names
  elec_theta_data <- elec_theta_data %>%
    select(-X1)
  colnames(elec_theta_data) <- c(paste0("bin_", colnames(elec_theta_data)[1:201]), 'trial_numeric')
  
  # pivot
  elec_theta_data <- elec_theta_data %>%
    pivot_longer(names_to = 'bin', values_to = 'theta', cols = starts_with("bin")) %>%
    mutate(trial_numeric = trial_numeric + 1) %>%
    mutate(trial_time = .05 * as.numeric(gsub("bin_", "", bin))) %>% 
    mutate(trial_time = as.character(round(trial_time, 3)))  %>% 
    select(-bin)
    
  
  # merge 
  elec_full_data <- inner_join(elec_theta_data, sl02_data_distance)
  
  # only before last turn around, less total trials because excluding trials where pacman died
  elec_before_turn <- elec_full_data %>%
    mutate(trial_time = as.numeric(trial_time)) %>%
    # get rid of no ghost
    filter(TrialType <= 16) %>%
    # filter out anything after last away
    group_by(trial_numeric) %>%
    filter(trial_time <= max(trial_time[away_choice == last_away])) %>%
    ungroup() %>%
    mutate(trial_numeric = factor(trial_numeric)) %>%
    mutate(cdf_distance = distributions3::cdf(threat_function, distance_to_ghost/100))
  
  
  # # model distance 
  # model1 <- lmer(theta ~ distance_to_ghost + UserLocation + jittered_start_location + reward_groups +(1|trial_numeric), data = elec_before_turn)
  # print(summary(model1))
  # print(effectsize(model1))
  # 
  # # model cdf 
  # model2 <- lmer(theta ~ cdf_distance + UserLocation + jittered_start_location + reward_groups +(1|trial_numeric), data = elec_before_turn)
  # print(summary(model2))
  # print(effectsize(model2))
  # 
  # # model dist + ghost
  # model3 <- lmer(theta ~ distance_to_ghost + GhostLocation + jittered_start_location + reward_groups +(1|trial_numeric), data = elec_before_turn)
  # print(summary(model3))
  # print(effectsize(model3))
  # 
  # # model cdf + ghost
  # model4 <- lmer(theta ~ cdf_distance + GhostLocation + jittered_start_location + reward_groups +(1|trial_numeric), data = elec_before_turn)
  # print(summary(model4))
  # print(effectsize(model4))
  # 
  # # model user + ghost
  # model5 <- lmer(theta ~ UserLocation + GhostLocation + jittered_start_location + reward_groups +(1|trial_numeric), data = elec_before_turn)
  # print(summary(model5))
  # print(effectsize(model5))
  # 
  # # model user + ghost + cdf
  # model6 <- lmer(theta ~ cdf_distance + UserLocation + GhostLocation + jittered_start_location + reward_groups +(1|trial_numeric), data = elec_before_turn)
  # print(summary(model6))
  # print(effectsize(model6))
  
  # model user + ghost + cdf
  model7 <- lmer(theta ~ distance_to_ghost + UserLocation + GhostLocation + jittered_start_location + reward_groups +(1|trial_numeric), data = elec_before_turn)
  print(summary(model7))
  print(effectsize(model7))  

}



# plot
elec_before_turn %>%
  select(distance_to_ghost, theta, trial_time, trial_numeric) %>%
  # filter(trial_numeric < 50) %>%
  ggplot(., aes(x = distance_to_ghost, y = theta, color = trial_time)) +
  geom_point(size = 2, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_viridis_b() +
  facet_wrap(~trial_numeric)



# plot
elec_before_turn %>%
  select(distance_to_ghost, theta, trial_time, trial_numeric) %>%
  filter(trial_numeric == 216) %>%
  ggplot(., aes(x = distance_to_ghost, y = theta, color = trial_time)) +
  geom_point(size = 4, alpha = .7) +
  geom_smooth(method = 'lm', formula = 'y ~ x', fill = 'grey', alpha = .7) +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_viridis_b()

```

