---
title: "Onset Across Region Analysis"
output: html_document
date: "2023-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(ggeffects)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lmerTest)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)



```

# Delta

```{r load-delta-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "delta_behavior_hc_all_subs_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "delta_behavior_amyg_all_subs_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "delta_behavior_ofc_all_subs_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "delta_behavior_cing_all_subs_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "delta_behavior_dlpfc_all_subs_onset.csv"))
insula_onset_df <- read_csv(path(here(), "munge", "delta_behavior_insula_all_subs_onset.csv"))

## Bind together ##
delta_onset_df <- rbind(hc_onset_df %>% mutate(region = "hc"),
                  amyg_onset_df %>% mutate(region = "amyg"),
                  ofc_onset_df %>% mutate(region = "ofc"),
                  cing_onset_df %>% mutate(region = "cing"),
                  dlpfc_onset_df %>% mutate(region = "dlpfc"),
                  insula_onset_df %>% mutate(region = "insula"))

```


```{r plot-scaled}

delta_onset_plot_df <- delta_onset_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 4.5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta)) %>%
  group_by(region) %>%
  mutate(region_avg_theta = scale(region_avg_theta))
  

delta_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), alpha = .2) +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("Delta")
  

delta_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject)

```
# Theta 

```{r load-theta-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "theta_behavior_hc_all_subs_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "theta_behavior_amyg_all_subs_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "theta_behavior_ofc_all_subs_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "theta_behavior_cing_all_subs_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "theta_behavior_dlpfc_all_subs_onset.csv"))
insula_onset_df <- read_csv(path(here(), "munge", "theta_behavior_insula_all_subs_onset.csv"))

## Bind together ##
theta_onset_df <- rbind(hc_onset_df %>% mutate(region = "hc"),
                  amyg_onset_df %>% mutate(region = "amyg"),
                  ofc_onset_df %>% mutate(region = "ofc"),
                  cing_onset_df %>% mutate(region = "cing"),
                  dlpfc_onset_df %>% mutate(region = "dlpfc"),
                  insula_onset_df %>% mutate(region = "insula"))

```

```{r plot-scaled}

theta_onset_plot_df <- theta_onset_df %>%
  # filter(subject != "LL10") %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 4.5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta)) %>%
  group_by(region) %>%
  mutate(region_avg_theta = scale(region_avg_theta))
  

theta_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), alpha = .2) +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#F97791", "#CC0029", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#F97791", "#CC0029", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("Theta")
  

```


```{r by-subject}

theta_onset_plot_df <- theta_onset_df %>%
  # filter(subject != "LL10") %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 4.5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region) %>%
  mutate(sub_avg_theta = scale(sub_avg_theta))


theta_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#F97791", "#A20021", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#F97791", "#A20021", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject, scales = "free_y")

```


```{r dlpfc}

dlpfc_onset_plot_df <- theta_onset_df %>%
  filter(region %in% c("dlpfc")) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  mutate(case = if_else(grepl("noghost", electrode), "No Ghost", "Ghost")) %>%
  filter(case == "Ghost") %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  mutate(upper_theta = t.test(elec_avg_theta)$conf.int[2], conf.level = .95) %>%
  mutate(lower_theta = t.test(elec_avg_theta)$conf.int[1], conf.level = .95) %>%
  ungroup() %>%
  select(region, trial_time, subject, sub_avg_theta, upper_theta, lower_theta) %>%
  # select(region, trial_time, subject, sub_avg_theta) %>%
  distinct() 
  # group_by(region, trial_time) %>%
  # mutate(roi_average = mean(sub_avg_theta)) %>%
  # mutate(upper_theta = t.test(sub_avg_theta)$conf.int[2], conf.level = .95) %>%
  # mutate(lower_theta = t.test(sub_avg_theta)$conf.int[1], conf.level = .95)


dlpfc_onset_plot_df %>%
  # filter(region == "cing") %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  # geom_ribbon(aes(ymin = lower_theta, ymax = upper_theta), alpha =.5) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_hline(yintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c( "#FFD680")) +
  scale_fill_manual(values = c("#FFD680")) +
  facet_wrap(~subject, scales = "free_y") +
  ggtitle("dlPFC")


hc_onset_plot_df <- theta_onset_df %>%
  filter(region %in% c("hc")) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  mutate(case = if_else(grepl("noghost", electrode), "No Ghost", "Ghost")) %>%
  filter(case == "Ghost") %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  mutate(upper_theta = t.test(elec_avg_theta)$conf.int[2], conf.level = .95) %>%
  mutate(lower_theta = t.test(elec_avg_theta)$conf.int[1], conf.level = .95) %>%
  ungroup() %>%
  select(region, trial_time, subject, sub_avg_theta, upper_theta, lower_theta) %>%
  # select(region, trial_time, subject, sub_avg_theta) %>%
  distinct() %>%
  group_by(subject) %>%
  mutate(sub_avg_theta = scale(sub_avg_theta))
  # group_by(region, trial_time) %>%
  # mutate(roi_average = mean(sub_avg_theta)) %>%
  # mutate(upper_theta = t.test(sub_avg_theta)$conf.int[2], conf.level = .95) %>%
  # mutate(lower_theta = t.test(sub_avg_theta)$conf.int[1], conf.level = .95)


hc_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  # geom_ribbon(aes(ymin = lower_theta, ymax = upper_theta), alpha =.5) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_hline(yintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c( "#88D1A3")) +
  scale_fill_manual(values = c("#88D1A3")) +
  facet_wrap(~subject, scales = "free_y") +
  ggtitle("HC")

```

```{r}

hc_ac_onset_plot_df <- theta_onset_df %>%
  filter(region %in% c("hc", "cing")) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  mutate(case = if_else(grepl("noghost", electrode), "No Ghost", "Ghost")) %>%
  filter(case == "Ghost") %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, sub_avg_theta) %>%
  distinct() %>%
  group_by(region) %>%
  mutate(sub_avg_theta = scale(sub_avg_theta))


hc_ac_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  # geom_ribbon(aes(ymin = lower_theta, ymax = upper_theta), alpha =.5) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_hline(yintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#CC0029", "#88D1A3")) +
  scale_fill_manual(values = c("#CC0029", "#88D1A3")) +
  facet_wrap(~subject, scales = "free_y") +
  ggtitle("HC + AC")

hc_dlpfc_onset_plot_df <- theta_onset_df %>%
  filter(region %in% c("hc", "dlpfc")) %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  mutate(case = if_else(grepl("noghost", electrode), "No Ghost", "Ghost")) %>%
  filter(case == "Ghost") %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, sub_avg_theta) %>%
  distinct() %>%
  group_by(region) %>%
  mutate(sub_avg_theta = scale(sub_avg_theta))


hc_dlpfc_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_hline(yintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#FFD680", "#88D1A3")) +
  scale_fill_manual(values = c("#FFD680", "#88D1A3")) +
  facet_wrap(~subject, scales = "free_y") +
  ggtitle("HC + dlPFC")

```



```{r dlpfc-plot}


dlpfc_onset_plot_df <- theta_onset_df %>%
  filter(region %in% c("dlpfc")) %>%
  filter(trial_time < 4.5) %>%
  mutate(case = if_else(grepl("noghost", electrode), "No Ghost", "Ghost")) %>%
  filter(case == "Ghost") %>%
  select(trial_time, subject, electrode, trial_numeric, theta) %>%
  group_by(trial_time, subject, electrode) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  group_by(trial_time) %>%
  mutate(roi_average = mean(sub_avg_theta)) %>%
  mutate(upper_theta = t.test(sub_avg_theta)$conf.int[2], conf.level = .95) %>%
  mutate(lower_theta = t.test(sub_avg_theta)$conf.int[1], conf.level = .95) %>%
  mutate(pval = t.test(sub_avg_theta)$p.value) %>%
  ungroup() %>%
  mutate(pval_fdr = p.adjust(pval, method = "fdr")) %>%
  mutate(sig = if_else((pval_fdr < .05) == T, .2, 1)) %>%
  mutate(sig_time = if_else((pval_fdr < .05) == T, trial_time, 999))


dlpfc_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = roi_average)) +
  geom_ribbon(aes(ymin = lower_theta, ymax = upper_theta), alpha =.5, fill = "#FFD680", color = "#FFD680") +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_hline(yintercept = 0, linetype = "dashed", color = 'black') +
  geom_point(color = "#FFD680") +
  geom_line(color = "#FFD680") +
  geom_line(aes(y = sig), color = "black", size =2) +
  ylim(-.2, .22) +
  theme(panel.background = element_rect(fill = "white")) +
  ggtitle("dlPFC Theta Power at Trial Onset")


```


```{r hc}

hc_onset_plot_df <- theta_onset_df %>%
  filter(region %in% c("hc")) %>%
  filter(trial_time < 4.5) %>%
  mutate(case = if_else(grepl("noghost", electrode), "No Ghost", "Ghost")) %>%
  filter(case == "Ghost") %>%
  select(trial_time, subject, electrode, trial_numeric, theta) %>%
  group_by(trial_time, subject, electrode) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  group_by(trial_time) %>%
  mutate(roi_average = mean(sub_avg_theta)) %>%
  mutate(upper_theta = t.test(sub_avg_theta)$conf.int[2], conf.level = .95) %>%
  mutate(lower_theta = t.test(sub_avg_theta)$conf.int[1], conf.level = .95) %>%
  mutate(pval = t.test(sub_avg_theta)$p.value) %>%
  ungroup() %>%
  mutate(pval_fdr = p.adjust(pval, method = "fdr")) %>%
  mutate(sig = if_else((pval_fdr < .05) == T, .11, 1)) %>%
  mutate(sig_time = if_else((pval_fdr < .05) == T, trial_time, 999))


hc_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = roi_average)) +
  geom_ribbon(aes(ymin = lower_theta, ymax = upper_theta), alpha =.5, fill = "#88D1A3", color = "#88D1A3") +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_hline(yintercept = 0, linetype = "dashed", color = 'black') +
  geom_point(color = "#88D1A3") +
  geom_line(color = "#88D1A3") +
  geom_line(aes(y = sig), color = "black", size =2) +
  ylim(-.1, .12) +
  theme(panel.background = element_rect(fill = "white")) +
  ggtitle("Hippocampal Theta Power at Trial Onset")


```

```{r ac}

ac_onset_plot_df <- theta_onset_df %>%
  filter(region %in% c("cing")) %>%
  filter(trial_time < 4.5) %>%
  mutate(case = if_else(grepl("noghost", electrode), "No Ghost", "Ghost")) %>%
  filter(case == "Ghost") %>%
  select(trial_time, subject, electrode, trial_numeric, theta) %>%
  group_by(trial_time, subject, electrode) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  group_by(trial_time) %>%
  mutate(roi_average = mean(sub_avg_theta)) %>%
  mutate(upper_theta = t.test(sub_avg_theta)$conf.int[2], conf.level = .95) %>%
  mutate(lower_theta = t.test(sub_avg_theta)$conf.int[1], conf.level = .95) %>%
  mutate(pval = t.test(sub_avg_theta)$p.value) %>%
  ungroup() %>%
  mutate(pval_fdr = p.adjust(pval, method = "fdr")) %>%
  mutate(sig = if_else((pval_fdr < .05) == T, .14, 1))%>%
  mutate(sig_time = if_else((pval_fdr < .05) == T, trial_time, 999))


ac_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = roi_average)) +
  geom_ribbon(aes(ymin = lower_theta, ymax = upper_theta), alpha =.5, fill = "#CC0029", color = "#CC0029") +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_hline(yintercept = 0, linetype = "dashed", color = 'black') +
  geom_point(color = "#CC0029") +
  geom_line(color = "#CC0029") +
  geom_line(aes(y = sig), color = "black", size =2) +
  ylim(-.1, .15) +
  theme(panel.background = element_rect(fill = "white")) +
  ggtitle("Anterior Cingulate Theta Power at Trial Onset")

```





# Alpha

```{r load-alpha-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "alpha_behavior_hc_all_subs_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "alpha_behavior_amyg_all_subs_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "alpha_behavior_ofc_all_subs_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "alpha_behavior_cing_all_subs_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "alpha_behavior_dlpfc_all_subs_onset.csv"))
insula_onset_df <- read_csv(path(here(), "munge", "alpha_behavior_insula_all_subs_onset.csv"))

## Bind together ##
alpha_onset_df <- rbind(hc_onset_df %>% mutate(region = "hc"),
                  amyg_onset_df %>% mutate(region = "amyg"),
                  ofc_onset_df %>% mutate(region = "ofc"),
                  cing_onset_df %>% mutate(region = "cing"),
                  dlpfc_onset_df %>% mutate(region = "dlpfc"),
                  insula_onset_df %>% mutate(region = "insula"))

```


```{r plot-scaled}

alpha_onset_plot_df <- alpha_onset_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 4.5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta)) %>%
  group_by(region) %>%
  mutate(region_avg_theta = scale(region_avg_theta))
  

alpha_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), alpha = .2) +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("alpha")
  

```
```{r by-subject}


alpha_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject)

```


# Beta

```{r load-beta-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "beta_behavior_hc_all_subs_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "beta_behavior_amyg_all_subs_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "beta_behavior_ofc_all_subs_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "beta_behavior_cing_all_subs_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "beta_behavior_dlpfc_all_subs_onset.csv"))
insula_onset_df <- read_csv(path(here(), "munge", "beta_behavior_insula_all_subs_onset.csv"))

## Bind together ##
beta_onset_df <- rbind(hc_onset_df %>% mutate(region = "hc"),
                  amyg_onset_df %>% mutate(region = "amyg"),
                  ofc_onset_df %>% mutate(region = "ofc"),
                  cing_onset_df %>% mutate(region = "cing"),
                  dlpfc_onset_df %>% mutate(region = "dlpfc"),
                  insula_onset_df %>% mutate(region = "insula"))

```


```{r plot-scaled}

beta_onset_plot_df <- beta_onset_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 4.5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta)) %>%
  group_by(region) %>%
  mutate(region_avg_theta = scale(region_avg_theta))
  

beta_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), beta = .2) +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("beta")
  

```

```{r by-subject}


beta_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject)

```




# Gamma

```{r load-gamma-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "gamma_behavior_hc_all_subs_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "gamma_behavior_amyg_all_subs_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "gamma_behavior_ofc_all_subs_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "gamma_behavior_cing_all_subs_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "gamma_behavior_dlpfc_all_subs_onset.csv"))
insula_onset_df <- read_csv(path(here(), "munge", "gamma_behavior_insula_all_subs_onset.csv"))

## Bind together ##
gamma_onset_df <- rbind(hc_onset_df %>% mutate(region = "hc"),
                  amyg_onset_df %>% mutate(region = "amyg"),
                  ofc_onset_df %>% mutate(region = "ofc"),
                  cing_onset_df %>% mutate(region = "cing"),
                  dlpfc_onset_df %>% mutate(region = "dlpfc"),
                  insula_onset_df %>% mutate(region = "insula"))

```


```{r plot-scaled}

gamma_onset_plot_df <- gamma_onset_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 4.5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta)) %>%
  group_by(region) %>%
  mutate(region_avg_theta = scale(region_avg_theta))
  

gamma_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), gamma = .2) +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("gamma")
  

```

```{r by-subject}


gamma_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject)

```


# HFA

```{r load-hfa-data}

## Load Region specific csvs ##
hc_onset_df <- read_csv(path(here(), "munge", "hfa_behavior_hc_all_subs_onset.csv"))
amyg_onset_df <- read_csv(path(here(), "munge", "hfa_behavior_amyg_all_subs_onset.csv"))
ofc_onset_df <- read_csv(path(here(), "munge", "hfa_behavior_ofc_all_subs_onset.csv"))
cing_onset_df <- read_csv(path(here(), "munge", "hfa_behavior_cing_all_subs_onset.csv"))
dlpfc_onset_df <- read_csv(path(here(), "munge", "hfa_behavior_dlpfc_all_subs_onset.csv"))
insula_onset_df <- read_csv(path(here(), "munge", "hfa_behavior_insula_all_subs_onset.csv"))

## Bind together ##
hfa_onset_df <- rbind(hc_onset_df %>% mutate(region = "hc"),
                  amyg_onset_df %>% mutate(region = "amyg"),
                  ofc_onset_df %>% mutate(region = "ofc"),
                  cing_onset_df %>% mutate(region = "cing"),
                  dlpfc_onset_df %>% mutate(region = "dlpfc"),
                  insula_onset_df %>% mutate(region = "insula"))

```


```{r plot-scaled}

hfa_onset_plot_df <- hfa_onset_df %>%
  select(region, trial_time, electrode, subject, trial_numeric, theta) %>%
  filter(trial_time < 4.5) %>%
  group_by(region, trial_time, electrode, subject) %>%
  mutate(elec_avg_theta = mean(theta)) %>%
  ungroup() %>%
  select(region, trial_time, subject, electrode, elec_avg_theta) %>%
  distinct() %>%
  group_by(region, trial_time, subject) %>%
  mutate(sub_avg_theta = mean(elec_avg_theta)) %>%
  ungroup() %>%
  select(region, trial_time, sub_avg_theta, subject) %>%
  distinct() %>%
  group_by(region, trial_time) %>%
  mutate(region_avg_theta = mean(sub_avg_theta)) %>%
  group_by(region) 
  

hfa_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = region_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  # geom_ribbon(aes(ymin = conf_lower, ymax = conf_upper), hfa = .2) +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  ggtitle("hfa")
  

```

```{r by-subject}


hfa_onset_plot_df %>%
  ggplot(., aes(x = trial_time, y = sub_avg_theta, color = region, fill = region)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = 'black') +
  geom_point() +
  geom_line() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_color_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  scale_fill_manual(values = c("#DE4A4D", "#FFA602", "#FFD680", "#88D1A3", "#3D99BA", "#876194")) +
  facet_wrap(~subject)

```