---
title: "Amygdala"
output: html_document
date: "2023-08-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(ggeffects)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lmerTest)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(survminer)
library(survival)
library(scales)

## hand written functions ##
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", 'create_distance_df.R'))
source(path(here(), "R", 'clean_behavioral_data.R'))

## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(17, "Set1"))
ghost_colors <- c("#E48DB7","#55BBC8", "#DE0D16")

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 2
# registerDoParallel(nCores)



```

## Notes

No ghost trials included

```{r load-data}
# brain data #
amyg_onset_df <- read_csv(path(here(), "munge", "theta_behavior_amyg_all_subs_onset.csv"))
amyg_onset_df <- amyg_onset_df %>%
  mutate(trial_time = round(trial_time, 2))

# behavior data #
all_subs_dist_clean <- read_csv(path(here(), "munge", "all_subs_distance_df.csv"))
all_subs_dist_clean <- all_subs_dist_clean %>%
  mutate(trial_time = round(trial_time, 2))

# join data #
amyg_behavior_df <- inner_join(amyg_onset_df, all_subs_dist_clean)

amyg_behavior_df <- amyg_behavior_df %>%
  mutate(ghost = if_else(grepl("noghost", electrode), "noghost", "ghost")) %>%
  mutate(electrode = gsub("_.*", "", electrode))


```


```{r, fig.height= 8, fig.width= 4.5}

amyg_rt_df <- amyg_behavior_df %>%
  group_by(subject, trial_numeric) %>%
  mutate(rt_tmp = if_else(last_away == away_choice & away_choice !=0, trial_time, -1)) %>%
  mutate(rt = max(rt_tmp, na.rm = T)) %>%
  filter(rt != -1) %>%
  select(-min_distance, -trial_flip, -move_step, -trial_end) %>%
  group_by(subject) 

amyg_rt_plot <- amyg_rt_df %>%
  filter(subject == "BJH016") %>%
  group_by(trial_time, trial_numeric) %>%
  mutate(mean_theta = mean(theta)) %>%
  ungroup() %>%
  arrange(rt) %>%
  mutate(trial_numeric = factor(trial_numeric, 
                                levels = unique(trial_numeric), 
                                labels = unique(trial_numeric),
                                ordered = T)) 

amyg_rt_plot %>%
  ggplot(., aes(x = trial_time, y = factor(trial_numeric), fill = scale(mean_theta))) +
  geom_tile() +
  geom_text(aes(x = rt, label = "*"), color = "white") +
  theme(panel.background = element_rect(fill = "white"),
        axis.text.y = element_blank()) +
  scale_fill_viridis(option = "turbo") 



```


```{r load-data}
# brain data #
hfa_onset_df <- read_csv(path(here(), "munge", "hfa_behavior_dlpfc_all_subs_onset.csv"))
hfa_onset_df <- hfa_onset_df %>%
  mutate(trial_time = round(trial_time, 2))

# behavior data #
all_subs_dist_clean <- read_csv(path(here(), "munge", "all_subs_distance_df.csv"))
all_subs_dist_clean <- all_subs_dist_clean %>%
  mutate(trial_time = round(trial_time, 2))

# join data #
hfa_behavior_df <- inner_join(hfa_onset_df, all_subs_dist_clean)

hfa_behavior_df <- hfa_behavior_df %>%
  mutate(ghost = if_else(grepl("noghost", electrode), "noghost", "ghost")) %>%
  mutate(electrode = gsub("_.*", "", electrode))


```


```{r, fig.height= 8, fig.width= 4.5}

hfa_rt_df <- hfa_behavior_df %>%
  group_by(subject, trial_numeric) %>%
  mutate(rt_tmp = if_else(last_away == away_choice & away_choice !=0, trial_time, -1)) %>%
  mutate(rt = max(rt_tmp, na.rm = T)) %>%
  filter(rt != -1) %>%
  select(-min_distance, -trial_flip, -move_step, -trial_end) %>%
  group_by(subject) 

hfa_rt_plot <- hfa_rt_df %>%
  filter(subject == "SLCH002") %>%
  group_by(trial_time, trial_numeric) %>%
  mutate(mean_theta = mean(theta)) %>%
  ungroup() %>%
  arrange(rt) %>%
  mutate(trial_numeric = factor(trial_numeric, 
                                levels = unique(trial_numeric), 
                                labels = unique(trial_numeric),
                                ordered = T)) 

hfa_rt_plot %>%
  ggplot(., aes(x = trial_time, y = factor(trial_numeric), fill = scale(mean_theta))) +
  geom_tile() +
  geom_text(aes(x = rt, label = "*"), color = "white") +
  theme(panel.background = element_rect(fill = "white"),
        axis.text.y = element_blank()) +
  scale_fill_viridis(option = "turbo") 



```


